- juju/charm.py
StopEvent type should be used instead of StartEvent
> Fix stop event attribute

- juju/charm.py
- juju/framework.py
- test/test_charm.py
Probably not particularly useful in this state, but should be something to build upon.
> First pass at dynamic events (relations, storage)

- juju/charm.py
- juju/framework.py
- test/test_charm.py
Added TODO for more contextual info to be passed to these events later.
> Remove name passed into relation and storage events

- juju/charm.py
- juju/framework.py
- juju/main.py
- juju/model.py
- test/charms/test_main/lib/charm.py
- test/test_charm.py
- test/test_framework.py
- test/test_main.py
- test/test_model.py
Supports either pre-loading or lazy-loading data until we decide which we want to go with.
> Implement classes to represent Juju model

- juju/model.py
- test/test_model.py
Add implementation for accessing config option values on the model.
> Add ConfigData to model

- op/model.py
- test/test_charm.py
- test/test_model.py
Expose unit and app locality
ModelCache: Separate out a cache key and init args
> Expose unit and app locality

- op/model.py
- test/test_model.py
Change is_local to is_our and change visibility
Expose is_leader as a Unit property
> Change is_local to is_our and change visibility

- op/charm.py
- op/main.py
- op/model.py
- test/charms/test_main/lib/charm.py
- test/test_main.py
- test/test_model.py
Add application relation data and event handling
> Add application relation data and event handling

- test/test_main.py
Use a temp directory for a charm under test
> Use a temp directory for a charm under test

- .gitignore
- README.md
Updated instructions to use the new `git submodule` approach as discussed.
> Update Getting Started instructions in README

- ops/jujuversion.py
- test/test_jujuversion.py
- test/test_model.py
https://github.com/canonical/operator/pull/100/files
> Fixes per the jujuversion review

- .travis.yml
- Makefile
- ops/jujuversion.py
Add a makefile showing how to run lint and tests, and fix lint
> Add a makefile showing how to run lint and tests, and fix lint

- LICENSE.txt
- Makefile
- ops/charm.py
- ops/framework.py
- ops/jujuversion.py
- ops/main.py
- ops/model.py
- setup.py
- test/charms/test_main/src/charm.py
- test/test_charm.py
- test/test_framework.py
- test/test_helpers.py
- test/test_jujuversion.py
- test/test_main.py
- test/test_model.py
Update all the key files with the license header, and add the
LICENSE.txt explaining this is Apache 2.0.
> Update the LICENSE to be Apache 2.0.

- ops/model.py
- test/test_model.py
On Mac, $TMP isn't '/tmp' so don't assert that the path exactly matches
'/tmp'. I don't think we care about the path as much as we care about
the filename. Also use assertRegex so that when the regex fails, it
tells you the string that it was matching against.
Also on Mac, time.monotonic() is more the 'time since the process
started' and not sychronized to some global epoch. The code assumed that
'0' was always going to be >30s away from time.monotonic() which isn't
true.
> Fixes for the test suite on Mac OSX.

- ops/charm.py
- ops/framework.py
- test/test_charm.py
- test/test_framework.py
We think this better reflacts what we want/need to access often as
charm writers.
> ops, test: tweak the helper properties on Object and CharmBase

- ops/main.py
- test/test_main.py
> ops, test: build strings using logger infra, not format

- ops/main.py
- ops/model.py
- test/charms/test_main/src/charm.py
- test/test_main.py
- test/test_model.py
main.py now reads JUJU_MODEL_NAME to be able to set Model.name.
fixes: #274
> ops/model.py: Add Model.name

- ops/charm.py
- ops/model.py
- ops/testing.py
- test/test_model.py
This is one approach to fixing #271.
> charm: make role an enum, with 'peer' instead of 'peers'

- ops/testing.py
- test/test_testing.py
An implementation of add_oci_resource to close #295 / #262
> Oci resources

- CODE_OF_CONDUCT.md
> have a Code of Conduct

- ops/charm.py
- ops/main.py
- ops/model.py
- ops/testing.py
- test/test_charm.py
- test/test_main.py
- test/test_testing.py
We need to talk about deprecating/changing behaviour before we land this.
> Simplified the CharmBase init signature.

- ops/log.py
- test/charms/test_main/src/charm.py
- test/test_helpers.py
- test/test_main.py
> log: set up sys.excepthook to log exceptions

- test/test_helpers.py
- test/test_model.py
this magic brought to you by /bin/sh.
> make tests 15% faster

- ops/main.py
- test/test_main.py
> main: log ops version on startup

- ops/framework.py
- ops/storage.py
- test/test_framework.py
Put it into storage.py instead of framework.py
This is just the rename portion of #323
> ops/storage.py: Move SQLiteBackend

- ops/lib/__init__.py
- test/test_lib.py
fixes: #351
---
opening this so people don't work on it (it's already fixed), but leaving it draft so the other things land first (it includes #340 and the merge will already be complicated because #350, and it's not necessary for 0.7 AIUI).
> make ops.lib.use support relative submodules

- ops/lib/__init__.py
- test/test_lib.py
> make debug logs all along the ops.lib.use dance

- ops/model.py
- test/test_model.py
> use yaml instead of json for pod-spec-set call

- test/test_model.py
Now that Harness has resources and pod-spec support, use those instead
of fake-script in test_model.
> Move test_model to use Harness for resource, pod-spec tests

- ops/jujuversion.py
- test/test_jujuversion.py
> Assume version 0.0.0 if JUJU_VERSION is not set

- test/test_infra.py
> make test_infra pass on windows

- ops/model.py
> minor docs fix

- setup.py
> not all operating systems let you rename over an existing file

- ops/testing.py
- test/test_testing.py
This is a bit of an RFC of an idea that occurred to me while chatting with @axinojolais.
> adds Harness.hooks_disabled, a context manager

- .gitignore
these are created during setup.py calls on release
> add build dist and egg-info to gitignore

- ops/main.py
> Fix trivial typo in docstring

- ops/main.py
- ops/storage.py
- test/test_main.py
- test/test_storage.py
> bail out of main() if use_juju_for_storage=True and unsupported

- ops/model.py
- test/test_model.py
> make model.config immutable

- ops/framework.py
- test/test_framework.py
> Log event deferral and reëmission.

- .gitignore
- .travis.yml
- ops/main.py
- ops/model.py
- ops/storage.py
- run_tests
- test/bin/relation-ids.bat
- test/bin/relation-list.bat
- test/test_charm.py
- test/test_helpers.py
- test/test_main.py
- test/test_storage.py
Some areas for further work have been marked with notes.
> These changes make it so that the test suite passes on Windows.

- ops/model.py
- test/test_model.py
There are some cases where network-get may return less information than is currently expected. This mainly seems to happen in K8s charms, since not all of the info may be available yet. This makes the model more tolerant to missing information.
> Allow for missing fields in network-get response

- ops/model.py
- test/test_model.py
> Don't skip interfaces without names: they don't have names on k8s

- README.md
Some tweaks to language. There are still some TBD items in there, and some missing links, pls don't forget about those.
> Improve and extend README.md with operator intro

- ops/model.py
- test/test_model.py
Per @hpidcock's request as the container socket path has changed.
> Update Pebble container socket path

- ops/charm.py
- test/charms/test_main/src/charm.py
- test/test_charm.py
- test/test_main.py
Rewrites workload-ready to be pebble-ready.
> *-workload-ready becomes *-pebble-ready

- ops/model.py
- ops/pebble.py
- test/test_pebble.py
Matches Pebble change https://github.com/canonical/pebble/pull/20
> Update Pebble layer field from "default" to "startup"

- test/fake_pebble.py
Use a temp directory, and make sure that we clean up afterward.
> Don't leave a 'testing.sock' in the working dir.

- test/test_storage.py
If you don't explicitly call close() you end up with warnings about
leaked file descriptors.
On non-NT the NamedTemporaryFile wrapper has:
https://github.com/python/cpython/blob/3.9/Lib/tempfile.py#L420
```
def __del__(self):
self.close()
```
However, on nt it has a 'delete-on-close' primitive so it doesn't try to be fancy about close(), but it also fails to define `__del__` on the object.
This is mostly just test stipple on Windows, but I still prefer having it. (the hackier solution would be to add in the __del__ method on Windows, but I'd really rather not do that.
I could even live without the try/finally, though I do think it is better to use it.
> On Windows, NamedTemporaryFile should be explicitly closed.

- docs/index.rst
- ops/relation.py
- requirements.txt
- test/test_relation.py
This commit adds a utility module that handles relation events between
resource providers and consumers. The Provider and Consumer objects
check type and version compatibilty between the resource provider and
resource consumer.
> A pair of Provider and Consumer utility objects

- ops/model.py
- test/test_model.py
> Fix incorrect variadic arg wrangling in get_services

- ops/model.py
Answers questions in issue #711
> Updated docs on planned units.

- ops/charm.py
- ops/framework.py
- ops/main.py
- test/test_main.py
> DEPATING -> DEPARTING

- HACKING.md
> notes about documentation for contributers

- .github/workflows/framework-tests.yaml
- ops/charm.py
- ops/framework.py
- ops/model.py
- pyproject.toml
- requirements-dev.txt
- test/charms/test_main/src/charm.py
- tox.ini
> more typing

- ops/model.py
see:
https://github.com/juju/juju/pull/14037
Fixes #753
> Fixes address info value getter

- .github/workflows/framework-tests.yaml
- ops/jujuversion.py
- ops/log.py
- ops/model.py
- pyproject.toml
- setup.py
Typing for the remaining "small" modules of ops:
log.py
version.py
jujuversion.py
main.py
> Typing utils

- .github/pull_request_template.md
Includes a checklist of easily forgotten interface ergonomics, along
with requirements, like documentation and tests.
> Proposing a PR template.

- ops/model.py
Added direct pebble imports to circumvent:
Fixes https://github.com/canonical/operator/issues/798
Verified that importing ops in xenial with py 3.5.3 works (while from the main branch it gives the expected error)
#800 should pass 
- Fixed issue with imports on py 3.5.x (xenial)
> Fix model types

- ops/jujuversion.py
- ops/model.py
- tox.ini
Okay.  I turned on branch-protection rules for any `*-maintenance` branches.  I saved the last cherry-pick for 1.5.1 to put in this PR in order to test/check that CI works right for this maintenance branch.  I assume that the publishing checks and actions will work the same for releases no matter which branch they come from.
> Final patch for 1.5.1 release

- ops/framework.py
- ops/main.py
- pyproject.toml
> Typing main

- ops/charm.py
- ops/jujuversion.py
- test/test_jujuversion.py
add logic to check if secrets supported
```python
if juju_version.secrets_supported:
```
> Add JujuVersion.has_secrets()

- .github/workflows/framework-tests.yaml
- .github/workflows/hello-charm-tests.yaml
- .github/workflows/observability-charm-tests.yaml
- .github/workflows/publish.yml
- HACKING.md
- ops/__init__.py
- ops/_private/yaml.py
- ops/charm.py
- ops/framework.py
- ops/jujuversion.py
- ops/main.py
- ops/model.py
- ops/pebble.py
- ops/storage.py
- ops/testing.py
- pyproject.toml
- requirements-dev.txt
- test/test_charm.py
- test/test_jujuversion.py
- test/test_main.py
- test/test_model.py
- test/test_pebble.py
- test/test_testing.py
- tox.ini
Do what it says on the tin (title).
> Bring 1.5-maintenance branch up to date

- HACKING.md
Simply updates a couple of outdated hrefs in HACKING.md.
> Minor documentation changes

- .github/workflows/observability-charm-tests.yaml
See https://github.com/canonical/alertmanager-k8s-operator/pull/163
> Reinstate alertmanager-k8s-operator CI tests now that issue is fixed

- ops/model.py
> docs: note that status changes are immediate

- ops/model.py
- ops/testing.py
Closes https://github.com/canonical/operator/issues/1040.
Tests:
```bash
TOTAL                       6389    500   2386    209    90%
unit: OK (247.53=setup[0.02]+cmd[246.92,0.59] seconds)
congratulations :) (247.56 seconds)
```
> fix(model): change model.relation.app type from optional to mandatory

- CHANGES.md
- ops/version.py
Edit `CHANGES.md` and `version.py` for release 2.12.0.
> docs: release 2.12.0 CHANGES and version

- .github/dependabot.yaml
> ci: automate 3rd party GitHub Actions version updates

- ops/version.py
change version to dev flavour of the expected upcoming release, `2.15.0.dev0`
> release: change version back to .dev after release

- ops/version.py
Presumption that next time will be ops 2.15.0 :)
> chore: bump version for the coming month's work

- CHANGES.md
Discussion: https://matrix.to/#/!aEDlwVgqmZMLeZIcUP:ubuntu.com/$RUh8eHXug6HfcSM8cA4M1rOY61ZlTkjxKBDCkIywiLg?via=ubuntu.com
> docs: note CVE in change log

- .github/workflows/tiobe.yaml
As well as the monthly scheduled run, allow executing the TIOBE workflow manually.
> ci: allow executing the TIOBE workflow manually

- CHANGES.md
- ops/version.py
Add changes for 2.16 release and update version.
> chore: 2.16.0 release

- ops/version.py
Bump version after 2.16 release.
> chore: bump version

- CHANGES.md
- ops/version.py
- testing/CHANGES.md
- testing/pyproject.toml
> chore: prepare ops 2.18.1 and ops-scenario 7.1.2 releases

- docs/tutorial/write-your-first-machine-charm.md
This accounts for an incoming change in Charmcraft: https://github.com/canonical/charmcraft/pull/2169. The build will be breaking until that PR is merged.
@dwilding I didn't find anything in the contribution guidelines about branching. Let me know if it's OK to PR into main.
> docs: update ref to charmcraft.yaml reference

- CHANGES.md
- HACKING.md
- ops/version.py
- testing/pyproject.toml
Bumping versions for the next release.
> chore: update versions

- ops/version.py
- testing/pyproject.toml
Update ops and scenario versions to the next dev0.
> chore: bump versions

- testing/tests/test_context_on.py
Test refactor pulled from the OTEL branch
For #1589
> refactor: named event unpack in tests

- docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/index.md
This PR does some tidying up of the landing page of the Kubernetes charm tutorial.
**[Preview doc build](https://ops--1660.org.readthedocs.build/en/1660/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/index.html)**
> docs: improve landing page of Kubernetes charm tutorial

- .readthedocs.yaml
- tox.ini
Harmonise docs build between local and rtd.
> chore: build docs using tox

- docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/create-a-minimal-kubernetes-charm.md
- docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/integrate-your-charm-with-postgresql.md
- docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/make-your-charm-configurable.md
Fix a bug where the assertion should be done on state_out.
Closes https://github.com/canonical/operator/issues/1685, https://github.com/canonical/operator/issues/1690.
> docs: fix a bug in the k8s tutorial doc about unit test

- docs/reference/ops-tracing.rst
- tracing/ops_tracing/_backend.py
- tracing/test/conftest.py
- tracing/test/test_backend.py
Add Juju topology labels as used by the Observability team.
Fixes #1729
> feat: add juju topology labels

- docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/observe-your-charm-with-cos-lite.md
- examples/k8s-5-observe/charmcraft.yaml
- examples/k8s-5-observe/src/charm.py
Updates the "Zero to Hero" Kubernetes charm tutorial to reflect the current best practice for integrating with Loki.
Closes #1845
> docs: update Loki section on charming zero-to-hero tutorial

- CHANGES.md
- ops/version.py
- pyproject.toml
- testing/pyproject.toml
- tracing/pyproject.toml
- uv.lock
This PR prepares the release of version 3.1.0.
> chore: update changelog and versions for 3.1.0 release

- ops/version.py
- pyproject.toml
- testing/pyproject.toml
- tracing/pyproject.toml
- uv.lock
This PR updates the version files after the release.
> chore: adjust versions after release

- docs/conf.py
- docs/howto/manage-the-workload-version.md
- docs/howto/write-integration-tests-for-a-charm.md
- docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/create-a-minimal-kubernetes-charm.md
- docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/integrate-your-charm-with-postgresql.md
- examples/httpbin-demo/tests/integration/test_charm.py
- examples/k8s-1-minimal/tests/integration/conftest.py
- examples/k8s-1-minimal/tests/integration/test_charm.py
- examples/k8s-2-configurable/tests/integration/conftest.py
- examples/k8s-2-configurable/tests/integration/test_charm.py
- examples/k8s-3-postgresql/tests/integration/conftest.py
- examples/k8s-3-postgresql/tests/integration/test_charm.py
- examples/k8s-4-action/tests/integration/conftest.py
- examples/k8s-4-action/tests/integration/test_charm.py
- examples/k8s-5-observe/tests/integration/conftest.py
- examples/k8s-5-observe/tests/integration/test_charm.py
- add jubilant to intersphinx
- update docs/howto/manage-the-workload-version.md to jubilant
- update docs/howto/write-integration-tests-for-a-charm.md to jubilant
> docs: update how-to to feature Jubilant (1/2)

- docs/explanation/testing.md
- docs/howto/manage-actions.md
- docs/howto/manage-leadership-changes.md
- docs/howto/manage-opened-ports.md
- docs/howto/manage-relations.md
- docs/howto/manage-storage.md
- docs/howto/manage-the-charm-version.md
- test/smoke/test_smoke.py
Update the rest of the how-to docs.
Built on top of #2000
> docs: update how-to to feature Jubilant (2/2) 
