canonical/operator

juju/charm.py

"Event" suffix is used by convention.

Rename leader event types to match other events

---

juju/charm.py

According to the prior discussion, developers will extend CharmBase and
CharmEventsBase to define their own Charm and CharmEvents.

Rename Charm and CharmEvents to have Base suffix

---

juju/charm.py
juju/framework.py
juju/main.py
test/charms/test_main/metadata.yaml
test/test_charm.py

This adds the model classes to hold and represent the charm metadata information in a structured way.  It also adds helpers for looking up event groups by relation or storage name to enable more programmatic interaction with those events.

Add model classes for metadata and helpers for relation / storage events

---

test/charms/test_main/hooks/disks-storage-attached

This was intended to be added in #6 but got missed.  However, the tests will auto-create it, allowing them to pass even when it's missing.  It is, in fact, expected to be in place, though.

Add missing hook to test charm

---

juju/charm.py
juju/framework.py
test/test_charm.py
test/test_framework.py

In order to be able to access events via attributes, dashes need to be
converted to underscores in relation and storage endpoint names.
Moreover, define_event should check to make sure that event_kind is a
valid identifier, not a keyword and does not override an existing
attribute.

Use underscores when defining events

---

juju/charm.py
juju/main.py

Split out from #16 for independent review. This uses classes to allow filtering events based on their type rather than name, and uses that filtering to ensure that symlinks are created only for hook events, rather than for charm-defined custom events.

Ensure that hook symlinks are only created for hook events

---

juju/framework.py
test/test_charm.py
test/test_framework.py

Persist stored state before framework commit
Currently stored state is persisted only on when `__setattr__` is called
on BoundStoredState which means any operations on data structures like
sets, lists or dicts are not persisted unless something like the
following is done:
self.state.myset = self.state.myset
Moreover, calling save_snapshot on every `__setattr__` is expensive and
semantically incorrect.
In order to notify BoundStoredState objects about a commit that is about
to happen a pre-commit event is defined on the framework itself and
BoundStoredState objects subscribe themselves to it in their `__init__`
method.
Framework events need to have a correct handle which includes the
Framework type, e.g. "Framework/on/pre_commit", as opposed to having
something like "on/pre_commit".
In …

Persist stored state before framework commit

---

juju/model.py
test/test_model.py

Relation data for the local unit can be changed, which are translated into calls to `relation-set`. This ensures that remote unit relation data cannot be modified and that the in-memory cache of relation data is kept in sync with updated values.

Add support for mutable relation data

---

juju/model.py

Avoid calling relation-ids for relation names which are not accessed.

Make loading of relation-ids lazy

---

juju/framework.py
test/test_framework.py

Sets are a bit special because they provide operations that generate
completely new sets instead of modifying the existing ones in-place:
* difference;
* symmetric_difference;
* union;
* intersection;
* copy (not present in MutableSet, only in built-in sets).
All of those operations return a new set object and rely on
_from_iterable classmethod defined on MutableSet to provide a new
instance of a class that derives from MutableSet based on an iterable.
StoredSet extends the signature of the __init__ function with an
additional argument (stored_data) and thus the library implementation of
_from_iterable fails to instantiate a new StoredSet.
Moreover, for the case where a binary operation * is performed with s1
as a StoredSet and s2 is a built-in set, the expected result is that a
new …

Implement _from_iterable for StoredSet

---

juju/framework.py
test/test_framework.py

* dict comparison works based on the abstract implementation that
compares items;
* for sets, `__eq__` has an abstract implementation based on `__le__`
and https://docs.python.org/3/library/collections.abc.html documents
that `__le__` and `__ge__` both need to be implemented to make other
operations work. Lib/_collections_abc.py in cpython reveals that they
`__le__` and `__ge__` do not depend on each other and so need to be
reimplemented separately;
* for lists, besides `__eq__`, there are also other comparison
operations that need to be implemented for lexicographical comparison.
https://docs.python.org/3/tutorial/datastructures.html#comparing-sequences-and-other-types

Implement comparison operators for stored types

---

juju/charm.py
juju/main.py
juju/model.py
test/bin/relation-ids
test/bin/relation-list
test/charms/test_main/lib/charm.py
test/test_charm.py
test/test_main.py
test/test_model.py

Add the args required for relation events to be meaningful. Must also handle the case where the unit or even relation is no longer available.

Add relation and unit instances to relation events

---

juju/charm.py
juju/model.py
test/bin/relation-list
test/test_model.py

Instead of treating dead relations as a separate type, handle missing relation errors more consistently and just treat them as not having any remove members or data.

Remove DeadRelation in favor of empty relations

---

juju/framework.py
test/test_charm.py

Allow for lookup of events scoped by a prefix, per continued discussion on how to handle relation and storage events which have a dynamic prefix.

Support scoped event lookup

---

juju/model.py
test/test_charm.py

Each relation ID (and thus Relation instance) is associated with a single remote application. Therefore, it doesn't make sense to have a set of Applications on the Relation, since it will always contain a single item.

Change Relation.apps to Relation.app

---

op/framework.py
op/main.py
test/charms/test_main/hooks/install
test/charms/test_main/lib/charm.py
test/test_main.py
test/test_model.py

By making the user code the target of the symlinks and relying on them to call into the framework (and explicitly passing in the charm class), we can eliminate the need to do path manipulation or require specific file and class names. It also frees us up to package the framework as a proper Python package and use standard dependency management tools.
This also includes fixing a few warnings that were picked up when I happened to use [`pytest`](https://docs.pytest.org/) rather than the plain `unittest` runner.
With this change, the hooks will instead point to the file containing the charm class, which would look like this:
```python
from op.charm import CharmBase
from op.main import main
class MyCharm(CharmBase):
if __name__ == '__main__':
main(MyCharm)
```

Refactor entry point handling

---

op/framework.py
test/test_charm.py
test/test_framework.py
test/test_main.py

Using addCleanup makes sure the cleanups happen in the right order (LIFO).
If you mix addCleanup with tearDown they don't happen in predictable ordering.
(tearDown happens before addCleanup triggers).

Use addCleanup instead of tearDown.

---

op/framework.py
test/test_framework.py

The Framework needs to trigger save_snapshot for StoredStateData only
when the state has actually changed.
The change also extends testing of nested data types to make sure
save_snapshot is called after changes to nested data types.

Implement dirty flag for StoredStateData

---

op/model.py
test/test_model.py

Adding is_leader is necessary for:
* the framework itself to determine if application relation data can be
modified;
* framework developers to implement leader-related behavior.

Expose is_leader as a Unit property

---

.gitignore
op/framework.py
test/test_framework.py

This means that setting up an observe() won't keep your object alive
indefinitely. This is safe, because we don't ever iterate the _observer
slice, and we already handled the case where we have a registered
observer_path but no matching observer.

Change Framework._observer to be a WeakValueDictionary

---

.travis.yml
op/charm.py
op/model.py

This is a much lighter touch than python-black. It seems to respect the
existing line lengths, even with --aggressive.
There are only some small tweaks of adding whitespace after class doc
strings before the __init__ function, which seems reasonable, and much
lighter than the python-black changes.
I ran
```
pip install autopep8
~/.local/bin/autopep8 --aggressive --in-place -r .
```
and it resulted in these changes. I also configured my editor to run "autopep8 --aggressive --in-place $file", which seems to be fine and doesn't disturb the project like python-black did.
I don't know where we'll run into interesting reformatting, but this looks better than nothing without being a strong rewrite.

Reformat the code using autopep8

---

op/model.py
test/test_model.py

Surface pod_spec as an attribute on the model which can be read and written. Juju currently doesn't support reading, but we expect to get it soon.

Add pod_spec to model

---

op/model.py
test/test_model.py

In order to avoid is-leader hook tool executions on every write to
application relation data bags caching of is-leader return values is
introduced. It relies on the implementation detail in Juju where it
grants a lease for 30 seconds when either of the following happens:
1) a unit agent renews the lease;
2) is-leader is called;
3) leader-set is called.

Optimize is_leader checks by caching temporarily

---

op/model.py
test/test_model.py

* CalledProcessError is no longer propagated up and ModelError is raised
instead;
* A ModelError exception can be more specific based on parameters of
CalledProccessError. For now this is used for RelationNotFoundError
only.
* relation hook tool execution errors are now tested via the fake_script
mechanism;
* use_json is now set to False for relation_set;
* command output is now always captured but returned only if asked for
(which is True by default).

Rework error handling in the model module

---

op/model.py
test/test_model.py

* --file needs to be used instead of --spec;
* the current implementation of pod_spec_set function does not allow for
easy testing of hook tool calls as temporary directories created for
json files are hidden from the caller and contain a randomized 8-byte
component. The current test is an attempt to do an immediate fix
without reworking pod_spec_set to solve an immediate problem of it
being broken.

Fix an argument name passed to pod-spec-set

---

op/model.py
test/test_model.py

A rework of model testing to make sure hook tool execution and result
handling is exercised.

Do away with FakeModelBackend

---

.flake8
op/charm.py
op/framework.py
op/main.py
op/model.py
test/test_model.py

* 1 line between groups of 'import' and 'from ... import' statements;
* 2 lines between types;
* 1 line between `__init__` and the class declaration.

Fix spacing in different files

---

op/model.py
test/test_model.py

RuntimeError is currently used instead of TypeError in multiple places
in ModelBackend where incorrect argument type is handled. There is a
more specific exception for that purpose:
https://docs.python.org/3/library/exceptions.html#TypeError
"Passing arguments of the wrong type (e.g. passing a list when an int is
expected) should result in a TypeError"

Use TypeError for invalid argument type errors

---

op/charm.py
op/model.py
test/test_charm.py
test/test_model.py

* Storage support modeled closely relation support and types;
* Storage can be requested dynamically via a hook tool (count is the
only constraint supported by the hook tool) in addition to Juju client
commands that can be issued by an operator to do the same;
* storage ids are in the form of <storage-name>/<id> compared to
relation ids;
* The plural wording of storage ("storages") is intentional. Although it
is marked as uncountable in several dictionaries, it looks like it has
become a norm in the IT world.
* https://en.wiktionary.org/wiki/storage#Usage_notes;
* https://en.wiktionary.org/wiki/storages#English;
* https://www.merriam-webster.com/thesaurus/storages
* storage-get at the time of writing only exposes 2 attributes:
* kind (storage endpoint name which we already have from …

Add storage support into Model

---

op/framework.py
test/test_framework.py

Fixup for code TODO: Handle attributes really should not be changing at runtime, so this makes them read-only and pre-computes the path rather than doing it on demand.

Make Handle attributes read-only

---

op/model.py
test/test_model.py

While there is only one operator pod per application in CAAS models,
it periodically executes hooks for different units which may or may not
be leaders.
Charm developers should make sure that their unit is a leader before
trying to set a pod spec while the framework needs to check for
leadership early and raise an appropriate exception.

Raise an error if a minion calls set_podspec

---

op/framework.py
test/test_framework.py

Fixup for TODO: Make sure that registered observers won't blow up when called due to a mismatched method signature.

Validate call signatures for event handlers

---

op/framework.py
test/test_framework.py

Fixup for TODO: Not persisting the event count means that on subsequent hooks, new events of the same type will overwrite previous events, potentially leading to a loss of data.

Persist event count to avoid reused event handles

---

test/test_model.py

Unfortunately, test_storage_tool_errors was silently skipped due to a
missing prefix - it was counted as a method rather than a test case.

Storage tests: add a missing test_ method prefix

---

ops/charm.py
ops/framework.py
test/test_charm.py
test/test_framework.py

Per discussions, we're keeping the wrapping of event types explicit but renaming `Event` to avoid confusion between it and `EventBase`.

Rename Event to EventSource

---

ops/charm.py

Resources of the type `oci-image` do not actually define a filename, since they are actually just metadata about an image in a registry.

Fix ResourceMeta for oci-image type resources

---

ops/framework.py
test/test_framework.py

Ensure that `Object.__init__` doesn't ever create 2 objects that have the same handle path.
This will raise a RuntimeError if 2 objects are created that have the same path. It also won't let you create an Object that matches one that has been created by load_snapshot(), and load_snapshot will also fail if the same object gets loaded 2 times.
The test suite has been updated to use _forget where appropriate. And the Event _reemit also uses _forget. But that seems to be the only cases where we need to use it.

Object singularity

---

ops/framework.py
test/test_framework.py

Always having to write `self.framework.model` gets repetitive and has to be done frequently enough that having a short-cut of `self.model` is worth doing.

Add convience properties for accessing model, meta, and charm_dir

---

ops/jujuversion.py
test/test_jujuversion.py

Introduce support for Juju version comparison in order to allow for
version-specific checks and warnings in the framework.

Add a Juju version comparison module

---

ops/framework.py
test/test_framework.py

Keeping a reference to a bound event, even for a short period such as when [looping over a set of events][1], will lead to an "two objects claiming to be GitLabK8sCharm/on have been created" error due to new `EventsBase` instances being created each time, while the `BoundEvent` instance keeps a reference to the instance it was bound to.
Fixes #103
[1]: https://github.com/johnsca/charm-gitlab-k8s/blob/fe834fbe42a1ee478c3522663c063afdf7e5a869/src/charm.py#L29-L33

Cache EventsBase and BoundEvent instances to prevent error

---

test/charms/test_main/src/charm.py
test/test_main.py

Readme was updated to account for the new recommended directory structure but not the test_main charm.

Move charm.py to src in test_main

---

ops/framework.py
test/test_framework.py

This solves one of the big "how do I initialize my State" questions. The
implementation is fairly lean, and it avoids problems where things end
up dirty because you wanted to have a default value.

Include set_default as a method on BoundStoredState.

---

ops/framework.py

The only capital letters for error messages are when we are referring to a named Type.
This provides consistency for our error strings.

Error messages should start lowercase.

---

ops/charm.py
ops/main.py
ops/model.py
test/charms/test_main/src/charm.py
test/test_charm.py
test/test_main.py
test/test_model.py

Per sprint discussions it was decided to avoid the renaming of actions
to functions although this was included into 2.7.x.
Relevant Juju PR: https://github.com/juju/juju/pull/11148
This change removes the previous logic of preferring functions and
multiplexing for older versions and simply uses actions.

Rename functions back to actions

---

ops/charm.py
ops/main.py
test/test_charm.py

We had CharmMeta taking dicts that you could pass in, which made it
easier to set up in tests, etc. However, Python dicts still have a lot
of meta characters vs the YAML representation.
Also, by using YAML you more accurately understand the content that
would be put into metadata.yaml or actions.yaml.
Further, PyCharm has support for comments of the form "language=XXX"
which give you syntax highlighting for a string which follows. I added
them here, though we can discuss if we want comment artifacts for a
particular editor.
If we prefer, it wouldn't be hard to have a standalone function for tests, rather than having 'charm.py' depending on PyYAML. Though I don't think there is a real problem, since we depend on PyYAML already.

Implement CharmMeta.from_yaml.

---

ops/model.py
test/test_model.py

Currently .app property is None when a peer relation contains only one
unit (relation-list returns an empty list). This change addresses the
issue.

Fix .app population for single-unit peer relations

---

ops/model.py
test/test_model.py

Hook tool handling for network-get which may be a base for further
endpoint modeling in the model.

Add network-get support to ModelBackend

---

README.md

There are some potentially controversial changes here, so happy to discuss here or in another forum if appropriate: 
- Switching the import path to avoid needing to add to sys.path before imports (avoids violating E402).
- Shows how to publish to the charmstore as well as local deploy.
- Clarifies that because the operator framework requires python 3.6 or greater it only supports charms for bionic or later.

Clarify how Juju events map to operator framework functions

---

Makefile
test/test_framework.py
test/test_model.py

Python has a rich enough variety of quotes that you should never need
to use a backslash to protect a single quote in a string; it a silly
little thing but it hurts readability. So this fixes that, and adds a
linter to make sure it stays fixed.
Modulo bugs in the linter of course.

Makefile, test: avoid using backslash to protect quotes

---

ops/framework.py
test/test_framework.py

Rework handling of exclusive db access
* sqlite3 Python module provides an implicit transaction management
functionality when isolation_level argument is not None when passed to
a connect method;
* sqlite3 itself by default operates in the autocommit mode which can
be disabled by executing the "BEGIN" SQL command;
https://www.sqlite.org/lockingv3.html#transaction_control
* BEGIN without EXCLUSIVE does not obtain an exclusive lock for the
database and the default behavior is to run a transaction as DEFERRED;
https://www.sqlite.org/lang_transaction.html#immediate
The desired behavior for the framework is holding an exclusive access to
the DB while a Framework object exists and is not closed which requires
maintaining exclusive access across transactions. This is possible to
achieve by using …

Rework DB lock handling

---

ops/model.py
test/test_model.py

Hi there,
Here's a small ergonomics change that allows the `ActiveStatus` subclass of `StatusBase` accept a message. Currently all other subclasses do *except* for `ActiveStatus` (and `UnknownStatus`, but see note below), which is surprising and may catch people out when refactoring. This change also makes it easier to construct a status object conditionally, e.g. when the logic for determining the message and status are confined to methods (contrived example):
``` python
def self.on_some_event(self, event):
message = self.build_status_message()
self.model.app.status = self.current_status()(message)
```
The current behaviour is preserved when no argument is given. Thoughts?
Note the same could be done for `UnknownStatus` without issue, but that one doesn't seem to be meant for charm …

Allow ActiveStatus constructor to take optional message argument

---

.travis.yml
setup.py

3.8 is the default python in Focal, so we should start testing on it.
And travis lets you test things on arm also, so why not?

Add python 3.8 testing, and also test on arm

---

README.md

found a formatting typo and misspelled obseve - observe in readme

fixing two typos in readme

---

ops/charm.py
ops/model.py
test/charms/test_main/src/charm.py
test/test_helpers.py
test/test_main.py
test/test_model.py

* add CollectMetricsEvent and a relevant API for supporting add-metric
hook tool on that event;
* add CollectMetricsEvent to CharmEvents;
* At the time of writing, collect-metrics hooks can run concurrently to other hooks
ignoring the usual semantics, however, this is serialized via DB locking with
a long timeout;
* collect-metrics hooks run in a limited environment where regular hook
tools are not available;
* Utility of deferring collect-metrics hooks is questionable but this is not prevented;
* metrics keys, metric values, label keys and label values are sanity-checked, although
those restrictions are not yet in place at the time of writing.

Add support for collect-metrics events

---

ops/main.py
test/test_main.py

Juju doesn't run collect-metrics hooks with the same context as regular
hooks and so regular hook tools are not available in those. Re-emitting
regular deferred events makes them fail due to that.

Do not re-emit events in a metric event context

---

ops/framework.py
test/test_framework.py

Storing floats was not supported although we claimed to support basic types.

Add support for storing floats

---

.flake8
ops/charm.py
ops/framework.py
ops/jujuversion.py
ops/main.py
ops/model.py
test/charms/test_main/src/charm.py
test/test_framework.py
test/test_helpers.py
test/test_jujuversion.py
test/test_main.py
test/test_model.py

This changes the flake8 config in two ways:
* shrink max-line-width to 99
this is done in the first commit. 127 is the maximum width github can show without scrolling sideways
Also, considering
99 doesn't seem like a completely unreasonable target
* set the maximum [cyclomatic complexity](https://en.wikipedia.org/wiki/Cyclomatic_complexity) to 10. This only results in having to refactor jujuversion, today.

many: make flake8 rules stricter

---

ops/model.py

Let's mark ModelCache to be a type internal to the framework so that
charmers know not to use it.

Mark ModelCache as an internal type

---

ops/model.py
test/test_model.py

* Networking information associated with a relation endpoint can be
useful before the relations themselves exist;
* It is not possible to retrieve networking info for dead relations so
for those cases networking info is looked up as if a relation ID was
not specified.

Allow binding lookup without relation ids

---

ops/charm.py

This is an attempt to make sure we clearly identify what is the expected
interaction points for charm authors.
I started off wanting to flag things as private where appropriate, but I didn't end up marking anything private, I just ended up documenting all the public interfaces.

ops/charm.py: Document all of the public attributes

---

ops/framework.py
test/test_framework.py

Before this change, if you create a class that uses StoredState, e.g.
class MyClass(Object):
stored = StoredState()
and then subclassed it,
class Another(MyClass):
pass
things broke. This fixes that, and closes #193.

ops.framework: enable inheritance of classes that use StoredState

---

ops/framework.py
test/test_framework.py

People will look at our tests for inspiration about how to do things,
even if we had comprehensive documentation (which we currently
don't). This makes them a little better on this front.

test_framework: change all `state` StoredState attrs to `_stored`

---

ops/charm.py

"remove" is fired after stop when a unit is removed.
https://github.com/juju/juju/pull/11237

Add an event for the "remove" hook

---

ops/log.py
ops/main.py
test/test_log.py
test/test_main.py

When running under 'juju debug-hooks' JUJU_DEBUG is set, which we can
use to detect that we should also print to stderr, so that people
interactively running the charm can see what is going on. It also
changes the default log level to DEBUG (though juju-log is still at
INFO).
This should address #200.
I chose to include the log level, and went with right-aligned, and fixed width so the messages end up left aligned. I don't terribly care, if people prefer a different format, this is all stderr, so it didn't make sense to me to include timestamps, etc. I also considered including the logger name, and/or file/line. Since it is stderr, I didn't want to overwhelm the output, but I'm flexible.

Enable stderr logging if JUJU_DEBUG is set.

---

ops/framework.py

The implementation was buggy. We can either fix it (pull #226), or we
can get rid of it.
We've had a general feeling that Charm.state should become Charm._stored
because other attributes shouldn't be peeking at it. And waiting for an
event indicating the state has changed is very much peeking at it.
Nothing inside our own framework depends on it, so for now it seems
possible to remove it.

ops/framework.py: remove StoredStateChanged.

---

ops/testing.py
test/test_testing.py

Charms which define action handlers encounter exceptions when tested
via ops.testing.Harness as the metadata object doesn't contain
appropriate actions.yaml metadata for defining the action event
handlers.  This patch provides that metadata in the same way that we
allow metadata.yaml metadata to be supplied or auto-discovered.

ops.testing.Harness actions metadata support.  (#231)

---

ops/log.py
test/test_log.py
test/test_main.py

Pass DEBUG logging through to juju-log, and default to DEBUG level. That
way users can chose something different at runtime, if they actually
want/don't want to see DEBUG messages.
This goes along with https://github.com/juju/juju/pull/11476 which
changes Juju itself to default to not displaying DEBUG messages from
units.
This should address issue #198.

ops/log.py: Default to DEBUG logging.

---

ops/main.py
test/test_main.py

Without this change we supported `dispatch` being a symlink to the main charm file. However, the real power of dispatch comes from being able to be a shim to the charm code, so this change enables that.

ops/main: handle dispatch being a shim 

---

ops/charm.py
ops/main.py
ops/model.py
test/test_charm.py
test/test_framework.py
test/test_model.py

Make ModelBackend a private class (_ModelBackend), because it isn't
something we want charmers to directly engage with anyway.

ops/model.py: Document public methods and types

---

ops/model.py
ops/testing.py
test/test_model.py
test/test_testing.py

This also refactors some things to make statuses easier to test with.
Based on #264, obviously :-)

ops/model: cover app.status and unit.status better

---

ops/framework.py
test/charms/test_main/src/charm.py
test/test_charm.py
test/test_framework.py

Our experience so far has shown that the implicit dependencies for
Framework.observe push people down a path that actually makes their
charms less maintainable. Especially when it comes to writing
components, it is better to have clearly named functions and clearly
defined targets.  For components, it is usually better to have private
methods, because the handlers are an implementation detail rather than
something you want to advertise to people who want to interact with
your component.
This is a breaking change (all charms that have been using
self.framework.observe(self.on.config_changed, self) will break. So we
want to make this change before we do an official release version.
fixes: #297

ops.framework: Remove default target for Framework.observe

---

ops/model.py
test/charms/test_main/src/charm.py
test/test_lib.py
test/test_main.py
test/test_model.py

The StatusBase types weren't being properly registered without
instantiating one. Now they are registered once they are declared,
rather than only after being created.
Futher, actually parse the output of status-get properly, and the
application status output is structured differently from the unit status
output.
fixes: #288

ops/model.py: Proper support for status-get

---

ops/main.py
test/test_main.py

This avoids the situation where Juju is dispatch-aware but the charm
is not resulting in no symlinks getting created.
fixes: #310

ops.main: only do _init_dispatch() if dispatch exists

---

test/test_main.py

Without this change, if you had done a `pip install ops`, the tests
from test_main would be testing the installed ops instead of the one
in tree. This change fixes that.
Fixes: #313

test_main: set up PYTHONPATH so the sub-process picks up this ops

---

ops/__init__.py
ops/version.py
requirements.txt
setup.py

This rejuggles how we get the version info.
When running from git, the version will be retrieved via the
equivalent of
git describe --tags --long --dirty | sed -e 's/-/+/; y/-/./'
This produces a PEP440-compatible version from the semantic versioning
we're using and tagging, plus the git describe output. Meaning that if at
any point we need to compare versions, `packaging.version.parse` will do
the right thing.
Then, `setup.py` replaces the code that does that with a constant string
just before running `setup`, and swaps it back out after. The constant
version it replacs it with is the one it gets from the code it swapped out,
sneakily.
This means that people using ops from git will always report something we
can use to figure out what they're running (or as close as we can get to
that), …

ops: get version from git

---

ops/framework.py

For JujuStorage we want to try out something that isn't Pickle, so start
by moving the decision to use Pickle to the storage layer, instead of
the Framework layer.
No tests were harmed in the making of this patch. I'll be adding some more direct tests of the Storage layer in my follow up patches, to define what the expectations of that interface are, but I wanted to hopefully get this in without the extra controversial bits.

ops/framework.py: Move pickle into Storage.

---

ops/jujuversion.py
ops/model.py
test/test_jujuversion.py
test/test_model.py

Juju before 2.7.0 didn't support the `--app` parameter for
`relation-get` and `relation-set`, meaning that the current code
breaks in 2.6.9.
This fixes that by avoiding `--app` entirely when not needed,
raising an explicit `RuntimeError` when an attempt is made to get
or set app data in an old Juju (where we know adding `--app` will
fail).
fixes: #223

model: don't use --app for relation-get/-set before 2.7.0

---

test/charms/test_main/actions.yaml
test/test_main.py
test/test_testing.py

The test suite had been setting up actions.yaml for each test that
needed it, but we might as well just set it up always. This makes the
test suite a bit less special, and will make it easier to use
'test_main' as a real deployable charm.
This also fixes a small bug where the test suite was deleting TMPDIR/test_main but not TMPDIR itself. (I had 1200 /tmp/tmp* directories on my machine.) (I've confirmed that with this patch my /tmp ends up clean.)
Note that this isn't sufficient to deploy test_charm. The remaining differences are:
a) 'ops' is a symlink outside of the charm dir. This is papered over by the test suite because shutil.copytree() follows symlinks and copies the contents, if you don't pass `symlinks=True`. (So we are copying ops for each test.)
b) We don't have a 'dispatch' or …

test/test_main: move actions.yaml into the charm

---

ops/main.py
ops/model.py
ops/testing.py
test/test_charm.py
test/test_helpers.py
test/test_model.py
test/test_testing.py

Unit name was already being read by _ModelBackend, as well as being
read by main(). We wanted to eliminate the duplication. We could either
pass more names down the stack, or we can pull them out of the backend.
This ended up a bit cleaner because we pass the Backend into Model
anyway, so it means having fewer args to the same object.
This also gave me an opportunity to eliminate a bunch of code that was
poking at os.environ just to set JUJU_UNIT_NAME.

many: move Model.name to be read from _ModelBackend

---

ops/charm.py
ops/main.py

Testing shows that on a modest yaml file, it can be 2ms instead of 25ms
to load a config.yaml. (postgresql's config.yaml).
By default 'yaml.safe_load' doesn't use the C loader (neither does
yaml.load).
This also unifies the code path that loads YAML for both main.main() and our test suites.

ops/main.py: Use CSafeLoader

---

ops/main.py

This addresses the issues of using `state-get` for Framework state during collect-metrics when the functionality is not available.
Essentially, we still trigger a script (hooks/collect-metrics) so people can still implement support for metrics, but we do *not* fire a collect-metrics event, because we are unable to instantiate a Framework backed by state-get.
This doesn't address the issue when Juju finally will allow state-get to be called by a charm during collect-metrics, because the specific implementation plan there has not been defined. We cannot just `shutil.which()` because `state-get` is still in $PATH, it just returns an error when called. We could trap the exception during `Framework.__init__` instead of refusing, but this seemed cleaner. (We can always change the policy once it …

347 juju storage and collect metrics

---

ops/lib/__init__.py
test/test_lib.py

This makes `ops.lib.use` lazy-autoimport, meaning that autoimport is now optional, meaning we don't need to guess whether to use it from main or not.

make ops.lib.autoimport use optional

---

ops/lib/__init__.py
test/test_lib.py

*  correctly escaping hyphen
*  optional whitespace before and after =
*  let lines terminate with a comment
fixes: 341

Improve ops.lib line matching regexp

---

ops/version.py

With `--long`, the version is e.g. `0.7.0+0.g51234ce` even when 51234ce *is* 0.7.0 :-(

don't use --long in "get describe" for version

---

ops/testing.py
test/test_testing.py

Factor out some common bits between how we would want to handle OCI
Resources and how we want to handle File resources.
Move all of the code to lazily create the directory until the charm
actually calls resource_get(). That makes populate_oci_resources and
add_resource not have to hit disk unless we actually consume the
content.
Move the cleanup code to use Harness.cleanup() instead of using
finalizers to cleanup. This makes it more deterministic, it also allows
you to call cleanup multiple times.
Note that Model caches the path returned by resource-get, so can't
actually cleanup and then make another request.

ops/testing.py: Harness.add_resource

---

ops/model.py
ops/testing.py
test/test_testing.py

fixes: #261
This is minimal, but it is at the level of what we do in the Operator
framework for pod-spec-set. It allows for having a charm trigger and
event, and then checking that the pod spec matches expectations.

ops/testing.py: Basic support for checking pod spec

---

test/charms/test_main/src/charm.py
test/test_main.py

Change test_main charm to use StoredState instead of a custom pickle-based state file.
This touches a lot of tests but hopefully in a good way. It cleans up all the tests to use strings to pass what events fired, rather than types (because StoredState doesn't let you pass types).  It also simplifies all the tests so they don't need to pass in a 'charm_config' that just defines where the state file should be. We also now always have actions registered, rather than passing in what actions we want registered when. (We already had actions.yaml that defined them all anyway.)
fixes: #286

0.8 test charm no pickle

---

ops/testing.py
test/test_testing.py

This adds a new method to the testing Harness called `begin_with_initial_hooks()`.
This runs the same hooks that Juju would run when deploying a new charm. It also handles relation events that happen based on what is defined at the point that you trigger begin*. It will make sure that peer relations are initialized and it will fire relation-created for all defined relations and relation-joined for all units of related applications.
fixes: #237

ops/testing.py: Harness.begin_with_initial_hooks()

---

ops/jujuversion.py
ops/main.py
test/test_jujuversion.py
test/test_main.py

This branch introudces a change, and a simplification (or at least a
separation of concerns) for how the operator framework determines that
a juju is dispatch-aware, and how it determines what hook juju is
asking us to run.
In the existing code we used sys.argv[0] to determine the hook to run
unless JUJU_DISPATCH_PATH was set and a dispatch binary existed, in
which case that environment variable was used. This leads to
charmcraft setting this environment variable to signal what hook to
run (because it will be indirecting the call to the charm code to set
up PYTHONPATH etc). Together with it always creating a dispatch
binary, this means operator always thought it was running in a
dispatch-aware juju, which meant it never created all the missing
symlinks, which meant it never got events …

version-check to determine dispatch support

---

ops/testing.py

All mappings set into the `key_values` argument are only added or updated.
To remove a configuration item, use the `unset` parameter.

Clarify ops.testing.Harness.update_config usage

---

test/test_log.py
test/test_main.py

The way we were doing the log tests, and some main tests, meant that
we'd the logging module's global state was leaking, accumulating
handlers and otherwise messing things up. In some situations this
could lead to failures where logassert and our juju-log handling got
into a squabble due to arbitrary ordering of handlers.
This change means that we only actually set up our juju-log handler
when we need it, and actually reset the logging global state when we
do.
HTH, HAND.

fix up logging tests impacting global state so much

---

ops/lib/__init__.py
test/test_lib.py

with this, test/test_lib.py passes on windows (3 down, 8 to go...)

ops/lib: use repr less with paths, and os.path.join more

---

test/test_testing.py

this makes test_testing pass on windows.
With this, the remaining modules all use `fake_script`. Digging into that next.

do not assume / is path separator for resource paths

---

ops/jujuversion.py
ops/main.py
test/test_jujuversion.py
test/test_main.py

Before this change, controller-side storage needed to be asked for explicitly.
However, in some cases we _know_ you should probably be using it: When
running in k8s and on a new enough Juju you almost certainly want to
enable it so you don't need to have persistent storage for your
controller pod.
This change makes it so that when we detect that the charm is in this
exact scenario, it uses controller-side automatically unless
explicitly requested not to.

use controller-side storage automatically in some cases

---

test/test_infra.py

subprocess.run's universal_newlines decodes the output of the command,
but doesn't let you say which encoding to use and in some situations
that will not be the right guess. From 3.6 we could make things
explicit, but 3.5 doesn't yet expose that, so we need to do things by
hand.

turns out universal_newlines is the wrong answer, on 3.5

---

ops/model.py
test/test_model.py

'relation-set foo=' should not fail, even if the key does not
exist in the relation data.

Handle removal of non-existant relation data

---

ops/testing.py
test/test_testing.py

This returns an empty list if no relations added during setup of harness when the charm has a possible relation. If no relations specified, we hit a `TypeError: object of type 'NoneType' has no len()` when trying to `random.shuffle()` the `rel_ids` retrieved from `_relation_ids_map`.
Fixes canonical#405

Add empty list as default return if no relation ids in map

---

ops/testing.py
test/test_testing.py

This ensures that charms get the same behavior from the Harness regarding default config values that they get from Juju.  As with
metadata.yaml and actions.yaml, a snippet can be passed in or it will read the file from disk.
Fixes #345

Make Harness load default values from config.yaml

---

ops/framework.py
ops/model.py
test/test_framework.py
test/test_model.py

This indirectly gets a `__repr__` for `RelationDataContent`.
`RelationData.__repr__` will trigger backend call, but as it's used for
debugging that seems reasonable to me.
fixes: #250

add __repr__ for EventBase, LazyMapping, and RelationData

---

ops/charm.py
test/test_charm.py

As [discussed on Discourse][comment], using `self.model.config` can cause the charm author to believe they are accessing the model-level config. It's also extra typing for something that is going to be frequently accessed, so like the other frequently accessed attributes like `self.app`, `self.unit`, etc, a `self.config` alias seems easier and less likely to lead to confusion.
[comment]: https://discourse.juju.is/t/first-steps-with-the-operator-framework/3006/12

Add config alias to CharmBase

---

README.md
test/test_main.py

When running the tests locally, I ran into failures due to the log message checks in the tests not accounting for the extra warning emitted if the libyaml extensions were not available for PyYAML.

Fix tests when PyYAML is missing libyaml extensions

---

docs/conf.py
ops/charm.py
ops/framework.py
ops/model.py
ops/testing.py

A Proposal for doc strings to charm module.

Added a few doc strings to charm module

---

ops/testing.py
test/test_testing.py

This corrects behavior when a test is using the disable_hooks
context manager and calls a helper that also uses disable_hooks.

Allow nesting of disable_hooks context manager

---

ops/storage.py
test/test_storage.py

Without this change, JujuStorage's notices method would always check
that the notices it yields matched the `event_path` parameter, despite
the docstring saying it was optional.
This fixes that, and adds test for the documented behaviour.
All hail @davigar15 for spotting the bug that resulted from this.
Fixes: #438

Make JujuStorage.notices respect the api :-)

---

ops/framework.py
test/test_charm.py
test/test_framework.py

This change has ObjectEvents instances show useful information in
their `__repr__`, not just the default `<yadda object at 0xdeadbeef>`.
In particular, it now lists all the events the object can handle.
Fixes: #416

Give ObjectEvents a useful __repr__

---

ops/framework.py
ops/main.py

This is a small clarification for the doc string of event.defer().

Minor clarification for deferred event doc string

---

ops/framework.py
test/test_framework.py

Before this change the three StoredFoo classes (`StoredDict`,
`StoredList` and `StoredSet`) did not have a `__repr__`, meaning that
if for example you wrote them out to the log them you'd get e.g.
<ops.framework.StoredList object at 0x7f8b3dca0b50>
which is not particularly useful. With this change instead you'd get
ops.framework.StoredList(["hi"])
which is not completely correct (in that you can't `eval(repr(obj))`
to get back `obj`), but it is at least more useful than what was there
before.

give StoredFoo classes a useful __repr__

---

ops/model.py
test/test_log.py
test/test_main.py
test/test_model.py

Without this change, logging a message that starts with a dash will raise an exception in charm code.

protect calls to juju-log from messages starting with dashes

---

ops/charm.py
test/charms/test_main/src/charm.py
test/test_charm.py
test/test_main.py

Without this change the operator framework would fall over hard if a
charm had an empty `actions.yaml`.
This was found and reported by @davigar15 (thanks!).
Fixes: #458

Treat empty actions.yaml as no actions.yaml.

---

ops/pebble.py
test/test_pebble.py

Basic support for talking to the Pebble API (HTTP over Unix socket). This PR adds the low-level API and unit tests for it (though no functional tests -- still thinking about the best way to do that).
Note that this doesn't integrate the API into the Operator Framework model. We'll want a slightly higher-level layer of abstraction for that, attached to the operator framework model. Still working on the design for that -- coming in a subsequent PR.
To test manually, you can run pebble locally (check out the `operator/pebble` repo, `go build`, and `pebble run`). Then you can run `python3 ops/pebble.py` as a command line client to exercise the Python API. For example:
``` bash
PEBBLE=/pebble/dir python3 ops/pebble.py --help
PEBBLE=/pebble/dir python3 ops/pebble.py changes
```

Low-level Pebble API client

---

ops/_yaml.py
ops/charm.py
ops/model.py
ops/pebble.py
ops/testing.py
test/fake_pebble.py
test/pebble_cli.py
test/test_charm.py
test/test_helpers.py
test/test_main.py
test/test_model.py
test/test_pebble.py

Includes addition of container-related metadata parsing (this is under discussion and may change!) Also rename `pebble.API` to `pebble.PebbleClient` per discussion. Still need to add tests - doing that now.
Initial work / feedback was done on [benhoyt/operator PR #1](https://github.com/benhoyt/operator/pull/1) ... this is squashed and rebased onto master now that the initial pebble PR is merged.
Intended usage is something like this:
```python
container = model.unit.containers['pgweb']
container = model.unit.get_container('pgweb')  # same as above
container.add_layer("""
summary: Simple override layer
services:
srv1:
override: merge
environment:
- var1: val1
""")
container.add_layer({  # supplying a dict works too
'summary': 'Another layer',
'services': {
'srv1': {
'override': 'merge', …
```

Higher-level Pebble integration into Operator Framework

---

ops/model.py
test/test_model.py

This logic is specific to containers, so it shouldn't be in `_ModelBackend.get_pebble()`, but on `Container`. Pebble itself doesn't require containers to work.
This was from Gustavo's [comment on PR 472](https://github.com/canonical/operator/pull/472#discussion_r572791023).

Move "build container socket path" logic to Container where it belongs

---

ops/pebble.py
test/test_pebble.py

Z for +00:00 (UTC) is as per RFC3339 and also what Go produces (see [here](https://play.golang.org/p/yY52SIJH3Yp)). I had just missed it before, because I was testing on NZ time (+13:00).
Add a unit test for this, and also a few for failure cases.

Add support for time offset 'Z' (UTC) in pebble._parse_timestamp

---

ops/model.py
ops/pebble.py
test/pebble_cli.py
test/test_model.py
test/test_pebble.py

Also do some `isinstance` checks so you know sooner (rather than the Pebble server having to tell you).
This came from testing Harry did, where he was passing a list of service names like `['foo']` to `container.start()`, instead of varargs (partly because the low-level client takes a list not varargs). So this makes two improvements:
1) If an error like this did happen again, the traceback and error string would include the helpful error message from the server. While we're at it, we make all client errors subclasses of a new `pebble.Error`. Strictly speaking this is a breaking change, but we haven't released anything Pebble-related yet, so that's fine.
2) Make the `pebble.Client` `start_services` and `stop_services` methods do isinstance checks to check the types upfront. This just lets …

Add custom pebble.Error subtypes for better error handling

---

.github/workflows/ci.yaml

Python 3.9 was released on Oct 5, 2020, so add support for it. (I.e., run tests on it.) Fixes #470.

Run tests on Python 3.9

---

ops/model.py
ops/testing.py
test/test_model.py
test/test_testing.py

Charm errors were happening because we were setting `Relation.app` from the app of the first unit, but if an event was fired before any units had started up (this happens on `relation-created`, for example), the `app` field was None and this caused a `KeyError` later when charms did things like `event.relation.data[event.app]` (`event.app` was `None`).
The code still starts with the current method (first app of the units), but in the case when that doesn't work because there are no units, we fall back to:
1) If the relation in question is this event's relation (`JUJU_RELATION_ID`), then use `JUJU_REMOTE_APP` as the remote app name.
2) If it's not this event's relation, use `relation-list --app` to fetch the remote app name (`--app` was …

Set Relation.app via JUJU_REMOTE_APP or "relation-list --app" if no units

---

ops/model.py
ops/pebble.py
test/pebble_cli.py
test/test_model.py
test/test_pebble.py

The Python / Operator Framework end of https://github.com/canonical/pebble/pull/10
This adds `add_layer` and `get_plan` to both the `Pebble` instance as well as `model.Container`.
Note that these changes would be a breaking change, but the functions in question currently raise `NotImplementedError`, and nobody except me is using it yet anyway.

Dynamic add_layer API and get_plan API

---

ops/pebble.py
test/pebble_cli.py
test/test_pebble.py

Parse "environment" correctly from YAML: [{k: v}, ...], not {k: v, ...}

---

ops/model.py
ops/pebble.py
test/pebble_cli.py
test/test_model.py
test/test_pebble.py

This adds a `get_services` API to the Pebble client, and `get_services` to `model.Container` (along with a `get_service` helper to fetch a single service's status). This corresponds to the Pebble change https://github.com/canonical/pebble/pull/14

Get-services API to talk to Pebble /v1/services

---

ops/model.py
ops/pebble.py
test/test_model.py
test/test_pebble.py

Per https://github.com/canonical/operator/issues/495, a bare `True` at the end of an `add_layer()` call does not read well. Make `combine` a keyword-only parameter, so you have to say `combine=True`.

Make add_layer()'s "combine" a keyword-only parameter

---

ops/pebble.py
test/test_pebble.py

The original intention with the list of 1-item objects was so the
environment variables were ordered in case of dependencies, like
`PATH=$PATH:/foo/var` (not that we support interpolation right now).
However, it made for an awkward config format and awkward API,
especially in the Python Operator Framework. So we're going to a plain
dictionary for the environment, and we'll resolve any dependencies
using an explicit dependency check.
This is the Python Operator Framework change to go with the Pebble PR: https://github.com/canonical/pebble/pull/24
See also original issue: https://github.com/canonical/pebble/issues/23

Update service config's "environment" to plain dict

---

ops/model.py
ops/pebble.py
test/pebble_cli.py
test/test_model.py
test/test_pebble.py

This PR adds Python Operator Framework support for the new Pebble files API (https://github.com/canonical/pebble/pull/25). Two things to note:
* Per the [spec](https://docs.google.com/document/d/1NPPZZB_qCwtTru-YsKkRSAb6mXJzBiE0fG3GTZnx4fM/edit#), for now we're only supporting single-file operations in the client APIs, even though the HTTP API itself supports bulk operations.
* In addition, Python's standard library doesn't have good support for streaming writing/parsing of multipart, so the current code reads the whole file into memory. However, the API is such that we can fix this at a later date without changing the `read_file` and `write_file` signatures.

Pebble files API client functions

---

ops/model.py
ops/pebble.py
test/pebble_cli.py
test/test_model.py
test/test_pebble.py

This updates the name and signature so we get that right now, but doesn't change the implementation, which still reads the whole thing into memory. We'll address that later.
Fixes #512.

Rename read_content/write_content to pull/push; use file-like objects

---

ops/pebble.py
ops/testing.py
test/test_model.py
test/test_pebble.py
test/test_testing.py

Fixes #488 
This implements a fairly primitive pebble backend for the testing Harness. It allows you to publish layers and read what the overall plan is.
It only supports `override: replace` directives, and doesn't yet support `override:merge`. But for the straightforward cases of asking pebble to track a layer and start some services, you have the opportunity to set that up with the testing Harness, and assert that you have the right plan when you are done.

Pebble testing

---

ops/model.py

This is annoying, but Python 3.5.2 (but not the 3.5.10 version we're testing against in CI) seem to fail with an obscure typing.py problem due to the `pebble.Layer` type annotation -- see #517. Just remove the type annotation and add a comment for now. The comment in the docstring still mentions the three types, so it's not a big deal to drop this.
Fixes #517

Attempt to fix model.py for Python 3.5.2 (default on Xenial)

---

ops/testing.py
test/test_testing.py

This adds an easier syntax to triggering a PebbleReadyEvent.
Specifically you have to grab a container object as a parameter to the event, which isn't terribly awkward but enough that it is cleaner to just have a simple "container_ready_event('name')" rather than going via a roundabout method.

Harness.container_pebble_ready

---

ops/main.py

`main()` takes the class for CharmBase not an instance of CharmBase.
Fixes #521

We take a class, not an object.

---

test/pebble_cli.py

This is just a tiny tweak to the Pebble test CLI to clarify that the `pebble.APIError` it's displaying isn't a raw HTTP error, but a pebble-wrapped one. See related discussion on #514.

Make test CLI show error type for clarity

---

test/test_lib.py

Now that GitHub Actions is on Python 3.8.10, test_lib.test_cwd fails.
This is due to Python 3.8.10 changing (fixing?) importlib to resolves
relative paths when creating module spec objects from file locations.
This change should work on both 3.8.9 and 3.8.10.
See:
* https://docs.python.org/release/3.8.10/whatsnew/changelog.html#core-and-builtins
* https://bugs.python.org/issue43105

Fix test_lib on Python 3.8.10 due to importlib relative path changes

---

docs/index.rst
ops/model.py
ops/pebble.py
ops/testing.py

This will add docs for `pebble.py` to https://ops.readthedocs.io/en/latest/
This is so I can link it from the new Discourse docs page I'm writing. Also tweak `*.txt` quoting so Sphinx doesn't interpret it as the start of an emphasis block and complain. And fix a reference in `testing.py`.

Add ops.pebble module to the docs

---

ops/model.py
ops/pebble.py

This depends on https://github.com/canonical/pebble/pull/35, so will
only actually apply for (say) Juju >= 2.9.3. But seems reasonable to
just update the docs to the latest, as it's an edge case charmers are
very likely to run into.

Update push/make_dir docstrings with new user/user-id conflict behavior

---

ops/pebble.py
test/test_pebble.py

This adds up the new user, user-id, group, group-id fields added in https://github.com/canonical/pebble/pull/35 to the Layer.services dict, allowing you to pass a dict object to `add_layer` with those fields in it (without this change you have to specify the layer as a raw YAML string).

Add user/group fields to Service (layer configuration)

---

ops/log.py
ops/main.py

It seems there were a few functions that still used a different format. This should bring them all into a standard pattern. (At least I don't see any other functions with '--' style arguments.)

We standardized on Google style doc strings.

---

ops/model.py
test/test_model.py

It's a coding mistake not to specify at least one, so raise a TypeError if this happens.
Fixes #555

check that container.start() and .stop() have at least 1 service name

---

ops/testing.py

When writing tests, it is nice to be able to use `self.harness.charm.whatever` without type warnings.

change type hint of ops.testing.Harness.charm to the particular subtype

---

ops/charm.py
test/test_charm.py

This PR adds support to `limit` in the `RelationMeta` class, which is currently not accessible at runtime by charms, and adds type validation and correctly sets the default value for `RelationMeta.scope`.
The [metadata.yaml spec](https://discourse.charmhub.io/t/charm-metadata-v2/3674) allows to limit the cardinality of relations using the `limit` keyword, e.g., when we want _up to_ one relation in the model using the `mongodb-datasource` interface. Additionally, the enumeration of the possible values for `RelationMeta.scope` (namely: `global`, which is default, or `container`) are not validated, and unless the scope is explicitly set, `RelationMeta.scope` is set to `None` rather than the default `global`.

Expose 'limit' in RelationMeta and improve ‘scope’

---

ops/model.py
ops/testing.py
test/test_testing.py

In LMA, we need access to the Model UUID to be able to tag telemetry in a way that allows us to consistently deduplicate it based on the Juju topology (model name, model uuid, application name, unit id).
This PR exposes `uuid` as a property of `ops.model.Model` so that its value can be used to tag telemetry.

Expose model uuid in ops.model.Model

---

setup.py

No longer will users have to add `semantic_version` themselves because it's required as part of `ops.relation`.
Closes #561

Add semantic_version to setup.py so pip will properly resolve the deps

---

ops/testing.py
test/test_testing.py

This pull request add support for testing relation departed and relation broken events, by adding methods in the test harness to remove relations and their units.

Support tests for removed relations and units

---

ops/charm.py

After speaking with the Juju developers, the docstring here is not correct. Docs are already updated upstream. Update these to
match

RelationBroken does not fire RelationChanged. Update the docs

---

ops/framework.py
test/test_framework.py

Previously, `juju debug-code` required `--at=hook` when used with the operator framework, whereas Juju itself defaults to `--at=all` if no other options are specified. Now that we have some time using this to build real charms, change the behavior of the Operator Framework to do the same.
Closes #554

Let 'debug-code' catch all events by default

---

ops/model.py

Add a link in the docs so users can easily see what we do with `Relation`

Add a link between 'Relation' and 'RelationMeta' in the docs

---

ops/pebble.py
test/test_pebble.py

Python's mime code's msg.as_bytes() ends up [here](https://github.com/python/cpython/blob/0f55d21212a0fb6dec4479eb76249ab2b54e57a3/Lib/email/generator.py#L149-L163
). But that translates `\r\n` into `\n`, which is obviously horrible for binary files. I saw someone on StackOverflow that had subclassed Generator and overriden this private _write_lines method to avoid this, but that seems like a total hack. Besides, it's not hard to just do this ourselves and get control over it, so let's do that.
I've added regression tests for this (and verified the `push` tests fail before the fix), and I've also tested manually using `test/pebble_cli.py` against the real Pebble with both a small file with mixed line endings in it and a huge binary executable (again, fails before the fix, works fine …

Fix Pebble push() handling of binary files

---

ops/model.py
ops/pebble.py
test/test_model.py

Try to get a list of services from `Container`. If we get a `ConnectionError`, return False. This is a first-pass towards a better workflow for catching common errors when writing charms and Pebble is not ready yet (or is not ready again)
Since there are almost no operations we can actually perform if Pebble returns a `ConnectionError`, check for it first and log it if that's the case to give a hint to Charm authors in case they forget to check.
This required some extra test mocking due to the way `MockPebbleClient` is implemented.
Add a .ready property to Model.Container to see if Pebble is usable
Closes #553

Check whether Pebble is ready before 

---

ops/testing.py

when units are removed out-of-order things break (some unit data bags are not removed).
with `sorted(..., reverse=True)` it works.
Tested with: https://github.com/canonical/alertmanager-operator/pull/24/commits/52b1f6944ec03b61a61548fdab611fe2b1f1486e

test harness: remove units via a copy rather than in-place

---

ops/testing.py
test/test_testing.py

When removing a relation via the test Harness, the charm model is not correctly updated, leaving stale relations around when iterating over `harness.charm.model.relations.values()`

Fix desynch of charm model on Harness.remove_relation

---

ops/model.py

Check whether the services are running before stopping them so we don't hit `pebble.ChangeError` if they're stopped, and the semantics are more familiar to anyone who may expect it to behave like systemd/sysvinit/etc.

Make Container.restart() semantics operate more like system services

---

ops/model.py
test/test_model.py

My fault for writing patches first thing in the morning and not adding a test...

Fix Container.restart() accidentally operating on strings, add a testcase

---

ops/pebble.py
test/pebble_cli.py
test/test_pebble.py

Corresponds to the new wait-change API endpoint in https://github.com/canonical/pebble/pull/63. This uses the new API if it's present, otherwise falls back to the existing polling-every-100ms method.

Add support for the new wait-change API

---

ops/model.py

As the header, really.
Closes #599

Remove triple backticks from ops.model docs since Sphinx doesn't like them

---

ops/testing.py

* Implements storage_add, storage_list, storage_get in testing.py backend;
* Implements add_storage to be used to write unit tests.
---
As specified in Juju documentation: https://juju.is/docs/sdk/storage
StorageAttachedEvents should be called prior to InstallEvent. That is accomplished by emitting a storage_attached events just before install on begin_with_initial_hooks:
```
for storage_name in self._meta.storages:
if len(self._backend.storage_list(storage_name)) > 0:
storage_name = storage_name.replace('-', '_')
self._charm.on[storage_name].storage_attached.emit()
self._charm.on.install.emit()
```
---
Examples:
The user can run add_storage to attach a number of disks to the charm unit.
```
...
harness.add_storage("data", count=2)
harness.update_config({
...
}) …
```

Add storage unit tests

---

ops/model.py
ops/testing.py
test/test_model.py

This is the simplest possible implementation of goal state, designed
to give folks a way to access goal state info, without implementing a
more complete representation of goal state.

Added "planned unit count" to model.

---

.gitignore
ops/model.py
test/test_model.py

Proposed implementation for `is_ready()` as a method for checking that a given Pebble instance is 'up' and its API is reachable. The primary difference here is removal of the context manager in favour of a simpler approach. This implementation also renames `is_ready` -> `can_connect`.
The primary logic here is that checking whether the Pebble API is available should only be a point-in-time check. This change was initially implemented to catch the case where some hook (usually `config-changed`) fires before the Pebble API was up, and prevent *all the charms* from needing a big long try/except in the same place.
With this implementation, we only provide that point-in-time check, that can be used before some operation in an event handler. If the Pebble API becomes unavailable *later in the …

Proposed update to container.is_ready implementation

---

ops/model.py
ops/pebble.py

Per discussion on Mattermost, this is a bit confusing due to the name. This update will appear in the online docs: https://ops.readthedocs.io/en/latest/#ops.model.Container.list_files

Clarify in list_files docstrings that it returns files and directories

---

README.md

Even if we're still using IRC (and I don't think we are); references to Freenode should be replace with Libera Chat instead.

Update reference to chat system.

---

ops/charm.py
ops/main.py
ops/model.py
test/test_charm.py
test/test_main.py

When any storage event fires, look up the appropriate Storage
object and attach it to the event. Since `juju storage-get` on
any attach or detach will return the type and location without
any additional arguments, it's necessary to iterate through the
list of known storages until we find the location for the appropriate
object.
Once we find it, we can operate by Storage.name and Storage.id for
restoring/deserializing the snapshot data, and further lookups are
not necessary.
Closes #571

Add storage details to StorageEvents

---

ops/model.py
test/test_model.py

Fixes #660 
The docstring about `ops.model.Resources.fetch` states that a `ModelError` is thrown when a path to the resource cannot be found on disk. The current implementation raises a `RuntimeError`. Either the docstring or the code need changing, and I think throwing a `ModelError` is appropriate.
Update: changed to `NameError` after review feedback

Adjust the ops.model.Resources.fetch method to throw a NameError

---

ops/main.py
test/test_charm.py

Don't throw exceptions if storage names have multiple hyphens. 
Closes #662

Fix storage events with multiple hyphens

---

ops/framework.py

This PR addresses a repeating mypy error for observer:
```
lib/charms/alertmanager_k8s/v0/alertmanager_dispatch.py:149: error: Argument 2 to "observe" of "Framework" has incompatible type "Callable[[RelationChangedEvent], Any]"; expected
"MethodType"  [arg-type]
self.charm.on[self.name].relation_changed, self._on_relation_changed
^
lib/charms/alertmanager_k8s/v0/alertmanager_dispatch.py:153: error: Argument 2 to "observe" of "Framework" has incompatible type "Callable[[Any], Any]"; expected "MethodType"  [arg-type]
self._on_relation_departed,
^
```
The mypy errors go away if you either
1. run mypy without `--check-untyped-defs` ([playground](https://mypy-play.net/?mypy=0.800&python=3.5&flags=check-untyped-defs&gist=c01b11ed64f19090c0e24928261dc2c2)); or
2. change ops type hint

fix observer type hint

---

ops/testing.py
test/test_model.py

Closes gh#636
In many cases, someone testing code that calls planned units will not
want to make calls to the harness to setup virtual peer units. This PR
provides a nice, relatively clean way to set the return from planned
units (and only the return from planned units) in the harness backend.

Add a method to set planned unit count in the testing harness.

---

ops/testing.py
test/test_testing.py

In the current implementation of the fake pebble filesystem in harness, the following would fail:
```python
client.make_dir("/mydir")
client.make_dir("/mydir", make_parents=True)
```
With a `FileExistsError`. This PR corrects that, and makes the fake FS behave like a real Pebble Files API (and more like `mkdir -p`), and ignores when a folder already exists if `make_parents` is specified.

Adjust the behaviour of the create_dir function in the fake Pebble FS

---

tox.ini

Make the test output more colourful in CI, and remove some environment variables from the list of those to explicitly passthrough that are automatically passed through.

Upkeep: Update tox.ini

---

ops/model.py
ops/pebble.py
ops/testing.py
test/test_model.py
test/test_pebble.py

This is the Python Operator Framework client part of the send-signals spec. The new `/v1/signals` Pebble API is being added in https://github.com/canonical/pebble/pull/92

Add send_signal method to pebble.Client and model.Container

---

ops/testing.py
test/test_testing.py

#645 added harness support for filesystem operations such as push/pull.
A call to `create_dir` in the original implementation omitted the `make_dirs` args, which failed `container.push` when parent dirs did not exist.
This bug became visible only when the nesting level was higher than 1.

pass missing make_dirs arg

---

ops/model.py
ops/testing.py
test/test_testing.py

* Added detach, attach and remove functions to simulate storage being
attached/detached/removed via the Juju CLI.
* Renamed some test names.
* Added firing of hooks post-Harness.begin() when appropriate Harness
functions are called.
* Hook firing counts changed to mimic Juju behavior, e.g. if 3 storage
units get attached (even via a single call), 3 events should be
emitted.
* Some minor tweaks to the existing testing backend implementation for
tracking storage state.

Extended and modified Harness storage API

---

ops/testing.py
test/test_testing.py

This PR modifies the harness's `remove_path` to succeed even if path does not exist.
Per comment by @benhoyt in #676, this matches pebble's behavior.
Fixes #676.

remove_path succeeds even if path does not exist

---

ops/testing.py
test/test_testing.py

Don't replace '-' with '_' until after we find the index. This is
essentially an off-by-one error which prevents any storage key
which uses hyphens from being looked up, and causes a difference
in behavior between actual charm behavior and harness behavior.
Add a small helper to the tests and an additional test to verify
that it works.

Make the storage harness work when metadata keys have hyphens

---

ops/testing.py

docfix: mention `add_relation_unit` in the docstring for `add_relation`

---

ops/testing.py
test/test_testing.py

Ensured that an APIError is raised instead of FileNotFoundError on list_files('/not/existing/path'); 
Fixes #679

conformed list_files behaviour on failure with pebble's

---

.github/workflows/framework-tests.yaml
ops/pebble.py
ops/testing.py
test/test_testing.py
tox.ini

This adds a real pebble tests step to all our workflow permutations.  After running the regular unit tests, it builds and starts the latest pebble and then runs the real pebble tests in the framework.  This exercise caught a couple of small bugs lying dormant that I have included fixes for.

Add real pebble tests to our CI

---

ops/pebble.py

The `recursive=True` argument in `remove_path` [method behaves like a `rm -rf`](https://chat.charmhub.io/charmhub/pl/rh9jykcd8tnaiex5zz8rjk9qpr) ([recursive + ignore nonexistent](https://www.man7.org/linux/man-pages/man1/rm.1.html#OPTIONS))
This PR fixes docstring to reflect current behaviour.

FIX remove_path docstring to relfect current behaviour.

---

HACKING.md
README.md
test/test_testing.py
tox.ini

Make sure the pebble binary is in your path and run `tox -e pebble`.  This should help facilitate smoother ops dev iteration.

add tox config for real pebble tests

---

tox.ini

Our CI started failing randomly on some ipython related stuff.  Internet search let me know that this has happened to other projects within the last day or so.  So skip the bad ipython version for now.

skip broken ipython version to fix CI

---

ops/model.py
test/test_testing.py

These are common file io patterns that previously required a fair bit of
boilerplate for users to accomplish.
Before:
```python
try:
f = container.list_files(path, itself=True)[0]
isdir = f.type == pebble.FileType.DIRECTORY
except pebble.APIError as err:
if err.code == 404:
isdir = False
raise err
```
After:
```python
container.isdir(path)
```
Similar pattern for `exists`.
@mmanciop

Add Container.isdir and Container.exists helpers

---

ops/charm.py
ops/main.py
test/test_main.py

I refactored a bit of the _get_event_args func logic.  I'd appreciate
some review focus on that to make sure I didn't subtley change/break
behavior.
Fixes #707

expose the departing unit on RelationDeparted events

---

ops/testing.py
test/test_testing.py

This PR implements `send_signal` for the test harness.
Apart from error handling, this is implemented as a no-op.
Without this change, unit tests would have to include a mock for every test:
```python
@patch("ops.testing._TestingPebbleClient.send_signal")
```

Implement send-signal for harness

---

ops/testing.py
test/test_testing.py

~~Attempting to run unit tests with an empty config file errors out with:~~
```
ops/testing.py", line 294, in _load_config_defaults
charm_config = charm_config.get('options', {})
AttributeError: 'NoneType' object has no attribute 'get'
```
~~because `yaml.safe_load` returns a None (instead of an empty dict).~~
Attempting to run unit tests with an empty config file errors out, as expected (cf. #618):
https://github.com/juju/charm/blob/965348bad4ccc62f5bcca591fdbbe03a7de02e4e/config.go#L100
This PR adds a unit test to that effect.
Closes #617

Harness: add test for an empty config file

---

ops/testing.py
test/test_testing.py

Change the behavior of the begin_with_initial_hooks test fixture to
better reflect the behavior of production Juju.
Specifically, after the fixture runs the install hook, we check unit
status. If the status is "maintenance" with an empty message, we
assume that the install hook did not set a status, and set the unit's
status to Unknown.
Resolves #726

begin_with_initial_hooks now sets post install status correctly

---

ops/testing.py
test/test_testing.py

This introduces tracking of can_connect state for containers/pebble-clients in the test harness.  Container.can_connect uses the PebbleClient.get_system_info function to determine connectability.  I've added a _check_connection call to every mock client method (including get_system_info) that consults the testing backend for whether or not pebble is "available" to connect to. It raises a ConnectionError if we are simulating can_connect=False.
By default, can_connect is true for all containers - this is to help not break tests in other charms.  Calling harness.begin() causes can_connect to become false for all containers.  And calling harness.container_pebble_ready automatically switches can_connect to true before running the hook code.
I suspect introducing a change like this will break a …

track can_connect state for mock pebble clients

---

ops/framework.py
ops/model.py
ops/testing.py
test/test_testing.py

Previously you could do this:
```python
harness.begin()
harness.set_leader(True)
peer_rel_id = harness.add_relation('test-peer', 'test-peer')
```
and get unexpected results. This is because when leader-elected fires, the peer relation may not have existed which doesn't make sense because one of the purposes of the leader-elected event is to manage peer/application relation data.  To fix the problem, this PR now raises an exception if set_leader is used to call a leader-elected hook without an existing peer relation.
Another problem is trying to replicate the "normal" juju behavior with Harness.begin().  Normally, the leader has already been chosen by juju when the peer relation created hook runs.  To reproduce this with the harness you previously had to:
```python
harness.set_leader(True) …
```

modify Harness.set_leader to be more robust, less finicky

---

test/charms/test_main/metadata.yaml

Removed deprecated fields.
Added new required `bases` field.
Testing and verifying bases is left for a separate PR, adding bases
support. (If we desire to do so -- bases are not necessarily a runtime
concern per the discussion in the metadata v2 spec.)

Edited test charm to support metadata v2, drop untested v1 fields

---

ops/model.py
test/test_model.py

Just trying to be more helpful to users.  Pretty self explanitory.
@sed-i had this idea [on discourse](https://discourse.charmhub.io/t/operator-framework-1-5-0/6533/2)
- Incorrect storage access (via model.storages) now provides a more helpful message - e.g. "Did you mean x, or y?".

Improved error message for invalid storage key usage

---

ops/testing.py

The behaviour was updated in 9a1ad5d9a5cd4b84fa40bcb4d9af37553c41b9df,
so update the related note to be consistent.

Update docs for unset param in update_config

---

ops/model.py
ops/testing.py
test/test_model.py
test/test_testing.py

Fixes #693.
- Fixes a bug during relation-broken events where an Application instance was created with an empty app name; also provides better errors when remote relation data is accessed in this circumstance.

Better error for relation data access in relation-broken events

---

HACKING.md
ops/testing.py
test/test_testing.py

Note that in its current form, this does change the behavior of harness.add_storage in a way that could break users' tests.  I am curious to see how widespread or not any breakage will be before deciding on details for the best way to not break users.
* Changes Harness.storage_add to not mark storage as attached by default unless explicitly told to via kwarg attach=True
* Updates add_storage and begin_with_initial_hooks to use attach_storage method rather than manually emitting storage_attached events.
* Minor doc comment tweaks and housekeeping.
Fixes #750
- storage_add and begin_with_initial_hooks only emit storage-attached events if storage is actually market attached internally (was …

Address storage testing quirks

---

ops/testing.py
test/test_testing.py

We changed harcoded value for `self.model_uuid` in `class _TestingModelBackend` with `str(uuid.uuid4())`.
Using a dynamically generated UUID v4 instead of a harcoded UUID v1 value mimics Juju behaviour better.
This PR fixes #779. Read this issue for further details.
Just run unit tests
```sh
$ tox -e unit
```
* None
https://github.com/canonical/operator/issues/779
- Remove harcoded value for self.model_uuid in ops/testing.py

Remove harcoded value for self.model_uuid

---

ops/testing.py

When juju runs, storage is attached/mounted into containers before the
charm class instance is constructed - meaning that in production, charms
can access storage data inside their `__init__` functions.  In order to
allow the harness to simulate this circumstance, it must be possible to
attach storage *before* calling Harness.begin().  With that need in
mind, this error check in add_storage doesn't make sense and so is
removed here.  More details of the issue are explained in #780.
Fixes #780
No changes necessary.
This is just a small reversion of some changes we made in a prev PR this cycle.  So nothing from this should go in the release changelog.

Remove overzealous Harness.add_storage error check.

---

ops/__init__.py
ops/charm.py
ops/framework.py
pyproject.toml

Added typing for ops/framework.py
Notes for reviewers:
- I had to touch __init__.py because the newly added 'from ops.model import...' (Even if guarded by an if TYPE_CHECKING...) made the import tree circular. There is no other solution (short of refactoring the whole project): https://github.com/microsoft/pylance-release/issues/531
- I had to touch charm.py to prevent CharmBase.on to be incorrectly predicted to be of type ObjectEvents (instead of CharmEvents). This is because of the `@property`-based approach I chose for typing Object.on (data descriptors are messy when it comes to typing...). If someone can think of a better solution, I'm all ears.
I think this workaround will become unnecessary with python 3.6+, where we can declare variable types without assigning them.
- [x ] Have …

Typing framework.py

---

ops/model.py
ops/pebble.py
pyproject.toml
test/test_pebble.py

Added types to pebble.py
- several minor API changes (List[str] --> Iterable[str], adding conversions and adapting error messages where necessary)
- small changes to model.py to remove the `# type: ignore` hanging around the pebble calls
- [NA] If this code exposes model data, does it do so thoughtfully, in a way that aids understanding?
- [NA] Do error messages, if any, present charm authors or operators with enough information to solve the problem?
`tox -e static`
- typed ops/pebble.py
- integrated the new types with ops/model.py (previously types were ignored when pebble calls were involved)

Typed ops.pebble.py

---

ops/testing.py
test/test_testing.py

When we added the departing_unit attribute to relation departed events,
I neglected to add that attribute to the corresponding events we emit
from the harness.  This fixes that and includes a test.
*Please replace with how we can verify that the change works.*
```sh
QA steps here
```
* Fixed the test harness to include departing unit information in relation-departed events consistent with the production environment.

Include departing unit info for harness-initiated events

---

ops/testing.py

Small change to a docstring I noticed while doing unit tests. Seems like `remove_relation_unit()` was copied from `add_relation_unit()` and the args weren't updated.

Fix docstring

---

ops/testing.py
test/test_model.py
test/test_testing.py

As I was working on #786 I realized also config is not as strict as juju config is. This PR brings the harness' behaviour in line.
From now on, the harness will complain if you try and set a non-existing config key, if you try and set a config key to a value that doesn't match its desired type.
- [ x ] Have any types changed? If so, have the type annotations been updated?
- [ x ] If this code exposes model data, does it do so thoughtfully, in a way that aids understanding?
- [ x ] Do error messages, if any, present charm authors or operators with enough information to solve the problem?
Added itests for all changed behaviours.
- The harness is now more strict in the way it manages config.
- Unittests will catch charm code attempting to mutate config (in naive ways).

added config backend to simulate more closely juju's own

---

ops/model.py
test/test_model.py

In some cases, the value of any given relation data key may be too long to set within the boundaries of the maximum argument length of `subprocess` and/or shell invocation. Charm authors interact with this by setting `MutableMapping` data, and it is not obvious to authors that this maps back to a bare k:v set on the commandline, until the data exceeds some limit and an `OSError` appears in the logs on a `RelationEvent`.
Deferring to file-based input is already done for `state-set`. Match that pattern.
Closes #801 
*Please replace with how we can verify that the change works.*
This modifies all `relation-set` operations, so integration tests cover it, though it can certainly be tested manually …

Use --file for relation-set; avoid shell argument length limits

---

test/test_charm.py

Someone had some issues applying a decorator to an event handler, solution was: use functools.wrap.
Felt like a good idea to add a test for it to help catch regressions.

Test observe(decorated-method)

---

.gitignore
test/charms/test_smoke/README.md
test/charms/test_smoke/charmcraft.yaml
test/charms/test_smoke/config.yaml
test/charms/test_smoke/metadata.yaml
test/charms/test_smoke/src/charm.py
test/smoke/test_smoke.py
tox.ini

This PR adds a smoke test will build a new "smoke" charm in test/charms/test_smoke.
The test will attempt to deploy xenial, bionic and focal versions of the charm.
- [N] Have any types changed? If so, have the type annotations been updated?
- [N/A] If this code exposes model data, does it do so thoughtfully, in a way that aids understanding?
- [Y] Do error messages, if any, present charm authors or operators with enough information to solve the problem?
Make sure that you are on a box with charmcraft and juju installed, and that you are connected to a "machine" controller, such as a local lxd cloud. Then run:
```sh
tox -e smoke
```
* This adds a step to the release process. Right now, it's a …

Added a very basic smoke test. Run it with `tox -e smoke`

---

ops/framework.py
ops/testing.py
test/test_testing.py

storage_list in the testing backend was erroneously using "all" instead
of "include_detached" - in its list comprehension to accumulate
active/attached storage entries.  We didn't get an error before since
"all" is a python builtin :-/  Correcting this also unveiled another
error where we weren't invalidating the stale storages list/cache in the
model when attaching a new storage - which showed up as failed snapshot
loading for storage events.  The cache invalidation code was moved from
Harness.add_storage to Harness.attach_storage where it belongs.
Fixes #819
See #819 for error details.
*Please include a bulleted list of items here, suitable for inclusion in a release changelog.*
- Fixed bug where currently-detached storage entries could show up erroneously in test harness operations.

Fix incorrect kwarg handling in testing backend storage_list

---

.github/workflows/framework-tests.yaml
.github/workflows/hello-charm-tests.yaml
.github/workflows/observability-charm-tests.yaml
.github/workflows/publish.yml

This should help prevent mistakes like I just did (tagging the wrong commit for a release).

require tests to pass on a commit before we publish it to pypi

---

ops/framework.py
ops/testing.py

This harness error check was added in #795.  It raises on a usually
benign sloppy naming of units by charm developers when writing tests.
In order to avoid breaking CI/tests for other charms, this should be
downgraded to a warning only. Notably, this change does/did cause
breakage in some data platform and observability charms - so it isn't
just a theoretical problem.  We are working to add some more charm tests to our CI - which is what originally caught this in #776.
Nothing for the changelog - we are basically rolling back an intra-release change.

downgrade breaking-change exception to just a warning

---

ops/model.py
test/test_model.py

Fixes #818
There are no tests for network object properties; ~~we probably should add some~~ --> I added some.
We should document somewhere that if juju fails to resolve a hostname, some network-get fields will not be IPs but the 'raw' hostname itself.
- OF won't break if hook tools return hostnames where IPs were previously expected.

Allow network-get to return hostnames where previously IPaddr were expected

---

ops/framework.py

What is being changed: framework.py
Description: Adding more documentation to the function `define_event` as per issue #830 
Documentation update only.
Documentation updated.
#830 -> #824
- Documentation has been added to `define_event`,  to further elaborate its functionality and purpose.

Added further documentation to define_event function in framework.py #830

---

ops/_private/yaml.py
ops/framework.py
ops/model.py
ops/pebble.py
ops/storage.py
ops/testing.py
pyproject.toml

Typed `ops/testing.py`
And with that, ops is now officially pyright-airtight.
`tox -vve static`
##Changelog
- typed `ops.testing`

Typed `ops/testing.py`

---

ops/charm.py
ops/model.py
test/test_charm.py

Stderr output emitted during an action hook execution gets injected in an action's results by juju.
- documented this in the ActionEvent docstring
- added a check that users don't manually set_results to anything containing "Stdout", because it will either be overridden or override juju's or break something, not sure which one but either way, it ain't good.
Added test for the new error condition.
We should make this clear in the ActionEvent-related documentation.
Already updated: https://discourse.charmhub.io/t/action-name-action-event/6466
*Please include a bulleted list of items here, suitable for inclusion in a release changelog.*
- Added check that `ActionEvent.set_results` will fail if the results contain the 'special' juju key "Stdout"

Documented and checked ActionEvent.set_results with "Stdout" key

---

ops/testing.py
test/test_testing.py

Reworked the `Harness.charm` method to raise an exception if the harness is not initialized (with `begin()`) yet.
That way, type checkers will not complain on: 
`charm: CharmBase = harness.charm`
- Refactored `Harness.charm` to raise an exception before `begin()` is called.

made harness.charm raise before begin

---

.github/workflows/framework-tests.yaml
.github/workflows/hello-charm-tests.yaml
.github/workflows/publish.yml

There is little value added in testing 3.{7,9} because older and newer versions are tested. Furthermore, those are not part of any supported Ubuntu release.

github actions: replace Python 3.{7,9} by 3.10

---

ops/charm.py

Fixed a confusing typo in the ConfigChangedEvent documentation

Fix typo in ConfigChangedEvent documentation

---

ops/main.py
ops/model.py

The Storage.id attributes was deprecated in PR #734, but this usage of it wasn't updated, so we were getting WARNING logs about it.
I've tested this code path locally by changing the `echo '["disks/0"]'` in `test_main.py:TestMainWithNoDispatch` to `echo '["disks/0", "disks/1]'`.
Fixes #853

Use Storage.index instead of deprecated Storage.id

---

ops/_private/yaml.py
ops/testing.py

This was originally coded as a ValueError exception in https://github.com/canonical/operator/pull/795/files#diff-37e8d80748bba21bb08c982f17b7879059bacc8d413b59da998a896fca18be33R713
Then downgraded to a warning in
https://github.com/canonical/operator/pull/822/files#diff-37e8d80748bba21bb08c982f17b7879059bacc8d413b59da998a896fca18be33R714
But accidentally reverted to a ValueError when types were being added: https://github.com/canonical/operator/pull/828/files#diff-37e8d80748bba21bb08c982f17b7879059bacc8d413b59da998a896fca18be33
So revert it to a warning as per #822.

Reinstate reversion of add_relation_unit ValueError to warning

---

ops/model.py
ops/pebble.py
ops/testing.py
test/test_model.py
test/test_pebble.py

As noted in #759, the debug logging in the FileNotFoundError case raises an exception while logging due to a missing "%s". In addition, we don't need str(e) or e.message(): %s with just "e" handles the formatting. Also, can_connect wasn't very well tested, so add test cases for the various exception cases.
Also remove the other use of pebble.Error.message() and remove the pebble.Error.name() and .message() methods as per discussion in #777.
Fixes #759
Fixes #777

Fix logging in can_connect, add tests; remove pebble.Error methods

---

docs/requirements.txt
ops/model.py

This doc tweaks is to clarify for https://github.com/canonical/operator/issues/863
Note that the Sphinx change is because 3.x no longer installs on recent Python versions. I updated this to fix doc build on Python 3.10.x. Due to changes in the typing module in Python 3.10.x and how Sphinx was doing a version test using version > (3, 10), doc building was broken with an ImportError when import Sphinx on Python 3.10.x (I'm using Python 3.10.6, for example). See: sphinx-doc/sphinx@8b2031c ... So just use the latest version of Sphinx for now.
Fixes #863

Doc tweak: clarify what Container.get_plan actually returns

---

.readthedocs.yaml

Our docs are broken due to the codebase now using 3.6 or 3.8 syntax features, and that breaks the docs generation on ReadTheDocs due to the version being fixed to 3.5 -- there's no content at all under any of the sections.

Update ReadTheDocs build to use Python 3.8 instead of 3.5

---

.github/workflows/framework-tests.yaml
README.md
ops/__init__.py
ops/main.py
ops/model.py
ops/pebble.py
setup.py
test/test_main.py
test/test_model.py
test/test_pebble.py

Juju 3.0 no longer supports Windows, so we don't need to either.

Remove Windows support

---

HACKING.md
README.md
ops/framework.py
ops/model.py
ops/pebble.py
ops/storage.py
ops/version.py
setup.py
test/test_framework.py
test/test_infra.py
test/test_main.py
test/test_model.py
test/test_pebble.py
test/test_storage.py

* Update references to the minimum Python version from 3.5 to 3.8
* Update setup.py `python_requires` version to 3.8
* Get rid of `framework._Metaclass` hack and use `__set_name__` instead
* Use `subprocess.run()`'s encoding argument now that we can
* Remove `pebble._json_loads()` now that `json.loads()` handles bytes
* `Pathlib.path.unlink()`'s "missing_ok" keyword argument
* Remove need for `unittest.skipIf` for Python < 3.7
* Couple of test tweaks now that dicts are ordered (as of Python 3.6)
Also added `test_run_error` from #868 (which is superceded by this PR).
**NOTE: This is a first pass, "minimum viable product" only.** In a subsequent release (2.1) I plan to do a full pass, updating everything to f-strings, variable type annotations, and so on.

Update minimum Python version from 3.5 to 3.8

---

ops/testing.py
test/test_testing.py

(Reopen of #866)
This PR changes the behavior of pebble in ops.testing module, to match the behavior of a real pebble server.
The previous code does not allow idempotent operations (start on started service, stop on stopped service) where a real pebble server is idempotent (https://juju.is/docs/sdk/interact-with-pebble#heading--start-and-stop).
Code for checking for previous service status in pebble has been removed in both `start_services` and `stop_services`, which does not match the idempotent behavior of a real pebble server. 
Pebble server does the following as validation which seems unnecessary to be implemented in testing module as of now.
1. Validate names of services
2. Validates dependencies (service before, after) and checks for loops
3. Applies changes with timeout
It should …

add pebble idempotency behavior

---

ops/charm.py
ops/main.py
ops/testing.py
test/test_main.py
test/test_testing.py

Per discussion with Gustavo, John, and Jon, we want to deprecate `use_juju_for_storage=True` (it's intended for pod-spec charms).
This PR also:
* Clarifies the warning message when local storage is chosen: "not a Kubernetes *podspec* charm" instead of "not a kubernetes charm" (the latter is incorrect). See also https://github.com/canonical/operator/issues/880.
* Removes the long-deprecated `key` argument to charm's `__init__`.
* Removes the deprecated (and private!) `Harness._oci_resources` attribute.

Deprecate controller storage and clarify log when local storage is chosen

---

ops/testing.py
test/test_model.py
test/test_testing.py

When we introduced `can_connect` it would have been a breaking change to enable it by default, so we added the `SIMULATE_CAN_CONNECT` global to enable it. The default was False to avoid breaking changes. We've been planning on turning this on by default for the 2.0 release (basically the only breaking change for 2.0). Note that it's been a recommendation and a warning to date.
This PR removes the global flag and enables simulation by default. The default value of `container.can_connect()` is still False when using `begin()` ("manual mode"), but this PR updates `begin_with_initial_hooks()` to set `can_connect` to True and fire pebble-ready for all containers in the charm's metadata.

Remove SIMULATE_CAN_CONNECT, make begin_with_initial_hooks trigger pebble-ready

---

.github/workflows/observability-charm-tests.yaml

It's breaking under 2.0.0 because of the begin_with_initial_hooks() change to start triggering pebble-ready. I'll submit a PR to fix that charm's tests tomorrow, but in the meantime I'd like to release a 2.0.0 release candidate to PyPI. The publish GitHub Action requires the observability-charm-tests to pass, so comment this out temporarily.

Temporarily disable alertmanager-operator test

---

.github/workflows/framework-tests.yaml
.github/workflows/observability-charm-tests.yaml
ops/_private/timeconv.py
ops/charm.py
ops/framework.py
ops/jujuversion.py
ops/lib/__init__.py
ops/main.py
ops/model.py
ops/pebble.py
ops/storage.py
ops/testing.py
ops/version.py
setup.py
test/charms/test_main/src/charm.py
test/fake_pebble.py
test/pebble_cli.py
test/smoke/test_smoke.py
test/test_charm.py
test/test_framework.py
test/test_helpers.py
test/test_lib.py
test/test_log.py
test/test_main.py
test/test_model.py
test/test_pebble.py
test/test_testing.py

Now that we require Python 3.8+, we can use f-strings (introduced in Python 3.6). This conversion was done automatically using the [Flynt](https://github.com/ikamensh/flynt) tool in two steps (separate commits):
* Base step to upgrade `.format()` to f-strings: `flynt -ll 100 --exclude ops/_vendor/ -- .`
* Also use f-strings for string concatenations (helps in most cases): `flynt -ll 100 -tc --exclude ops/_vendor/ -- .`
All tests pass. I haven't done a thorough check over the diff yet, but will before merging.
The intention is to do further upgrades (variable type annotations, and so on) in future PRs.

Use f-strings (almost) everywhere

---

.github/workflows/observability-charm-tests.yaml

Also update these repos to their new (redirected) URLs.
Reverts when this was commented out in https://github.com/canonical/operator/pull/885

Reenable alertmanager-operator tests now that charm is fixed on ops 2.0

---

ops/model.py
ops/pebble.py
ops/testing.py
test/test_testing.py

Currently the testing harness's version of pull() raises FileNotFoundError and IsADirectoryError instead of pebble.PathError, which is what the real pull() raises in these situations. Catch those and raise the same error as in real life.
Also document this better in the relevant docstrings.
There are probably other places the testing file system's errors leak out, but keep this PR limited in scope to just pull().
Also remove an unnecessary Pyright FIXME -- this was addressed when the message() method was removed recently.
Fixes #896

Make testing pull() raise pebble.PathError and improve docs

---

ops/framework.py
ops/model.py
ops/testing.py
test/test_model.py

Fix itself is a two-character change: "if" -> "elif". :-)
Also a couple of drive-by fixes for docstrings.
Fixes #899. However, due to https://bugs.launchpad.net/juju/+bug/2004672, when this is fixed you get a "secret not found" error when `secret-info-get` is used in the same hook as the `secret-add`, because `secret-info-get` is not looking at pending creates.

Don't call secret-info-get with both ID and label (it's a Juju error)

---

ops/lib/__init__.py
test/test_lib.py

Per Mattermost discussion, `ops.lib` is deprecated, and is superseded by
charm libraries (https://juju.is/docs/sdk/library) and regular Python imports.
We now prefer to do version selection at build (charmcraft pack) time.

Add ops.lib deprecation notice

---

ops/model.py
test/test_model.py

This won't actually fix any `ops` issues in the field, but it makes the backend calls more consistent and less confusing.
Also add test for label-only Model.get_secret() variant.
Fixes #902

Make secret-get consistently use "secret:<id>" fmt to avoid confusion

---

ops/charm.py
ops/framework.py
ops/main.py
ops/model.py
ops/pebble.py
ops/storage.py
ops/testing.py
pyproject.toml
test/charms/test_main/src/charm.py
test/fake_pebble.py

Now that we're using Python 3.8+ the more modern syntax is available to us, so use it. Also re-enable Pyright's reportTypeCommentUsage setting.
The second commit in this PR also removes a bunch of unneeded "noqa" and "pyright" comments.
I used a little script to find these and do a regex replace, then fixed up the few remaining ones (that were split on multiple lines) manually. Then I ran the following script to dump the AST (removing "annotated assignments") and did a diff against the original AST to ensure I hadn't messed up anything else.
```python
import ast
import os
class Transformer(ast.NodeTransformer):
def visit_AnnAssign(self, node):
if node.value is None:
return None
return ast.Assign([node.target], node.value)
PATHS = """
ops/charm.py
ops/framework.py
ops/main.py
ops/model.py …
```

Replace "# type: T" comments with proper variable type annotations

---

ops/model.py
ops/testing.py
test/test_model.py
test/test_testing.py

Adds support for open-port, close-port and opened-ports as per the [OP029 spec](https://docs.google.com/document/d/1xHLzBgcXtLsBpMsjuqUW2pI1tP4D8lgSUD_sg3HClng/edit#).
Also adds testing backend support for the same for use in charm tests.
Fixes https://github.com/canonical/operator/issues/179

Support for open-port, close-port, and opened-ports

---

setup.py
test/test_infra.py

This breaks "pip install" because requirements.txt is not included in the sdist or wheel. We could explicitly add a MANIFEST.in, but seems better to keep it simple and in line with the defaults, so just duplicate it and add a test to ensure they stay in sync.
Fixes #913.

Revert to static list for setup.py install_requires

---

.github/workflows/charmcraft-pack.yaml
.github/workflows/db-charm-tests.yaml
.github/workflows/framework-tests.yaml
.github/workflows/hello-charm-tests.yaml
.github/workflows/observability-charm-tests.yaml
.github/workflows/publish.yml

This is to find any issues early and avoid breakage like that caused by 2.1.0 missing the requirements.txt file: https://github.com/canonical/operator/issues/913 (the specific issue was fixed in #914).

Add CI tests for 'pip install' and 'charmcraft pack'

---

.github/workflows/charmcraft-pack.yaml

The change in https://github.com/canonical/operator/pull/915 was all good on the PR branch but of course didn't work once merged, because `${{ github.event.pull_request.head.sha }}` doesn't exist when running CI on the main branch. Update to only use that variable if present, otherwise revert to the normal `$GITHUB_SHA` method.

Only use PR SHA if it's actually a PR (it broke once merged)

---

ops/__init__.py
ops/main.py
test/test_charm.py
test/test_framework.py
test/test_helpers.py
test/test_jujuversion.py
test/test_main.py
test/test_model.py
test/test_pebble.py
test/test_storage.py
test/test_testing.py

This is to address #731: it's hard to remember or discover which `ops` sub-module (like `ops.charm` or `ops.framework`) a name comes from. That, and imports become a bit of a mess (`from ops.charm import X; from ops.framework import Y; from ops.main import main`).
In my view we had previously split them up somewhat arbitrarily (eg: `FooEvent` types are in `ops.charm`, but they could just as well be in `ops.framework`). I considered a different, more logical sub-module arrangement, but I think it'd still be hard to remember and know where things were.
This solution is simple: import all the public names into the top-level `ops` module in the `__init__.py` file. They're quite unique, so there's no conflicts. The only exception is `ops.pebble`, whose names aren't imported there (most charms …

Import (almost) all public names in ops __init__.py

---

ops/model.py

*Update `relation.units` docstring to mention the special case of subordinates units.*
N/A
No change.
N/A.
- *Update `relation.units` docstring for subordinates*

Update `relation.units` docstring for subordinates

---

ops/pebble.py
test/test_pebble.py

This PR adds support for directly comparing `Layer` objects for equality. While writing tests using `ops-scenario`, I was surprised by an assertion failing with identical `Layers`. 
The PR includes a new test for this feature.
This does not impact documentation, but will more correctly match users expectation that 2 identical `Layers` are equal.
N/A
- *Adds support for Layer equality checks*

Support Layer equality checks

---

ops/testing.py
test/test_testing.py

This pull request addresses the issue of incorrect function signature in the `send_signal` method of the mocking class `_TestingPebbleClient` in the operator framework. Currently, the signature of `send_signal` method in `_TestingPebbleClient` does not match the `send_signal` method of `Client` in the `ops.pebble` module. As a result, unit tests that involve the `send_signal` method are failing.
Here's the function signature of `send_signal` in `ops.testing._TestingPebbleClient` right now :
https://github.com/canonical/operator/blob/a8717eadfbf97f001f9b1e06214fa19aa5df6204/ops/testing.py#L2540
And here's the `send_signal` method of `ops.pebble.Client`:
https://github.com/canonical/operator/blob/a8717eadfbf97f001f9b1e06214fa19aa5df6204/ops/pebble.py#L2306

Fixing the function signature of send_signal in _TestingPebbleClient

---

.github/workflows/framework-tests.yaml

Current GitHub CI jobs (for `1.5-maintenance` branch) are using `ubuntu-latest` image to run tests. However the "latest" image was upgraded to `Ubuntu 22.04` which does not have required python versions (<=3.6). To keep testing with older python versions, it's necessary to specify `ubuntu-20.04` as a platform for running tests. ([list of python versions and their availability on different ci images](https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json))
~~I believe that Github CI ignores proposed changes to `.github/workflows/` files and always uses what's currently in the target branch. Thus I don't think there's a way to test this change without merging it.~~
No code changes made. See results of the checks in this PR to verify success.
No documentation …

Use ubuntu-20.04 to run CI tests that require python<=3.6

---

ops/model.py
test/test_model.py

This PR addresses an issue that happens during a scale-down event, where `planned_units` includes units with the status marked as `dying`.
This becomes visible when say the `_storage_detaching` hook errors based on certain preconditions preventing a unit from immediately disappearing. 
This PR essentially filters out those dying units to have an accurate count of live units.

Remove "dying" units from planned units

---

ops/model.py

Concrete paths (pathlib.Path) are not needed since the filesystem is not being accessed from the path object; only pathlib.PurePath is needed
Added `StrOrPurePath` type annotation to ops.Container methods that only accepted `str` type for path
(`pathlib.Path` is a subclass of `pathlib.PurePath`)
More info:
https://docs.python.org/3/library/pathlib.html#pure-paths
https://docs.python.org/3/library/pathlib.html#concrete-paths
Call ops.Container methods (e.g. `pull()`) with a `pathlib.PurePath` & check type annotation
Type annotation for some methods changes from `str | Path` to `str | PurePath`
N/A
- Accept `pathlib.PurePath` type in `ops.Container` methods: `pull`, `push`, `list_files`, `exists`, …

Use PurePath type annotation when path casted to string

---

.github/workflows/observability-charm-tests.yaml
ops/charm.py
ops/framework.py
ops/jujuversion.py
ops/log.py
ops/main.py
ops/model.py
ops/pebble.py
ops/storage.py
ops/testing.py
pyproject.toml
requirements-dev.txt

This PR updates Pyright to the latest version, 1.1.313, and fixes the errors that resulted.
Boy this was more painful than I expected. It seems to have gotten significantly stricter. I engaged in lots of fighting with the compiler -- if I knew any swear words I'd be using them here. In one case (`_ModelBackend._run`) I stopped fighting and added a `type: ignore`. I think we need to be pragmatic here: the *code* is no worse than it was before, and we can always improve specific things in future PRs.
I also ended up disabling a few more Pyright issues, specifically the following seemed more trouble than they're worth:
* reportPrivateUsage: we do this often in the codebase, for example charm.py and testing.py poke at `_ModelBackend`, which is private
* reportUnnecessaryIsInstance: we do lots …

Update Pyright version to latest (1.1.313)

---

.github/workflows/db-charm-tests.yaml
.github/workflows/framework-tests.yaml
HACKING.md
README.md
docs/conf.py
docs/index.rst
ops/__init__.py
ops/charm.py
ops/framework.py
ops/log.py
ops/main.py
ops/model.py
ops/storage.py
ops/testing.py
ops/version.py
setup.py
test/charms/test_smoke/src/charm.py
test/test_main.py

**[View rendered version updated README.md here.](https://github.com/benhoyt/operator/blob/readme-update/README.md)**
Remove a lot of the "operator" and K8s jargon from the top of our README. I feel fairly strongly this isn't the place to sell how great Juju, K8s operators, and model-driven development are -- we should do that on our landing page and/or docs, not in the ops README. Charmers shouldn't normally be landing here, and if they do, I think we should give them succinct, developer-oriented documentation.
Also simplify and update some of the terminology to be consistent with our updated Juju Terminology doc.
The first part of the README is copied to `ops/__init__.py` for consistency. That will appear at the top of our API reference at https://ops.readthedocs.io/
Move the note about …

Remove jargon from and simplify README

---

ops/model.py
test/test_helpers.py
test/test_model.py

This PR fixes the error caused by duplicate paths in `container.push_path()`.
Please see #948 .
*Please replace with how we can verify that the change works.*
```sh
QA steps here
Running `tox`
```
No changes required. 
Fixes #948
- Fixes bug in container.push_path, which caused FileNotFoundError when pushing paths to the container.

Fix issue with relative paths in Container.push_path

---

ops/testing.py

`FileInfo.__repr__` was raising a TypeError due to the expectation that permissions was never None, and the ":o" format string:
```
TypeError: unsupported format string passed to NoneType.__format__
```
At first I was surprised that Pyright didn't catch this, because clearly dict.get can return None, but we were defining a `_FileKwargs` TypedDict with a non-optional "permissions" field, so fix that too.
NOTE: this code will be removed and unnecessary if OP036 is done (using the real file system for the Harness's container filesystem), but might as well fix while the iron's hot.
Fixes #955

Avoid error in FileInfo repr due to permissions being None

---

ops/charm.py
ops/framework.py
ops/model.py
ops/storage.py
ops/testing.py

This is so that if MyPy is used in a charm, it type checks them. MyPy by default doesn't type check methods that have no type annotations on them. For example:
```
$ tox -e mypy
mypy: commands[0]> mypy
src/charm.py:49: error: Call to untyped function "remove_all_revisions" in typed context  [no-untyped-call]
Found 1 error in 1 file (checked 1 source file)
```
I forgot to do this in #953.

Add "-> None" to methods without other types

---

ops/charm.py

One more thing forgotten from #953. This is annoying because it means that charms that use `ops.PebbleReadyEvent` annotations when handling `pebble-ready` can't access any attributes of the `workload`, as it doesn't have a type.

Type annotate PebbleReadyEvent.workload

---

ops/jujuversion.py
test/test_jujuversion.py

open-port is not supported before Juju 3.0.3 on Kubernetes
Context: https://chat.charmhub.io/charmhub/pl/91t6ip37ybncuqe11eudfx38xw

Add `has_open_port_k8s` to `JujuVersion`

---

ops/pebble.py
test/test_pebble.py

Pebble [merged/released](https://github.com/canonical/pebble/pull/190/files) `kill-delay` support, but ops did not yet picked that up.
This PR adds it.
Closes #974

Add kill-delay to pebble ServiceDict type

---

ops/pebble.py

Hi! While working on https://github.com/python/mypy/pull/15732 our tools detected a misuse of `AnyStr` TypeVar (which is quite common). The proper way is to use `Union` here :)

Replace `typing.AnyStr` with `Union[str, bytes]`

---

ops/testing.py
test/test_testing.py

Try read unified charmcraft.yaml first, that may included metadata, actions, and config. Ignore metadata.yaml, actions.yaml, config.yaml if they are exists in charmcraft.yaml
Fixes https://github.com/canonical/operator/issues/969

Support reading charmcraft.yaml in testing harness

---

ops/model.py

This also fixes the type of a subclass's .name attribute, such as BlockedStatus.name, so that a "# type: ignore" comment is not required in such things as "status_str == BlockedStatus.name".
See https://github.com/canonical/github-runner-operator/pull/79#discussion_r1274376165
Please describe the *why* and the *how* of your change here.

Fix type of StatusBase.name

---

ops/framework.py

Fixes #981
This PR tells type checkers to make no assumptions about the names that will be found in ObjectEvents.
- pros: type checkers will no longer complain on `self.on.dynamically_defined_name_action`
- cons: type checkers will no longer give type hints for events names that we do know to exist in subclasses, e.g. `start, stop, install`...

effectively disable type checking on ObjectEvent namespace

---

.github/workflows/db-charm-tests.yaml
ops/model.py
test/test_model.py

In some cases when a charm has an array or set of secrets that don't have distinguishing characters, charms need a way to distinguish by ID (most of the time you'd use labels: most secrets have a specific use like "database-password" that you can use as a label). Despite the name, you can't `Secret.id` as a unique identifier, because sometimes it includes the model UUID, and sometimes not -- it's really intended as a locator URI, not a unique ID. So provide `Secret.unique_identifier` to handle this use case.
It would be nice if Secret.id was a unique identifier, but it's really a locator URI. Too late to change that, though.
We considered deprecating Secret.id entirely, and adding two new properties, "uri" and "unique_identifier". However, given that this locator is called ID throughout …

Add Secret.unique_identifier (XID part); improve id/label docs

---

ops/testing.py
test/test_testing.py

The [push() docs](https://ops.readthedocs.io/en/latest/#ops.Container.push) explicitly say that the "encoding" param is ignored if the source is bytes or a binary stream. This is useful because the default is encoding='utf-8'; but we should already know the source stream is binary, so let that override the default.
Also add a test that "encoding" is ignored in these cases.
Fixes #990

Ignore push() encoding if source is a binary file or stream

---

.github/pull_request_template.md

It just gets in the way. You have to manually select and delete it from the PR description -- and that's easy to miss when you have a single commit and GitHub puts this text at the bottom of the nice commit message.
More trouble than it's worth -- just delete it. You can be sure I'll ask the PR creator if it needs a better description. :-)

Remove the PR template

---

ops/pebble.py
ops/testing.py
test/test_testing.py

The Pebble process execution plays an important role in a lot of charms. However, the ops framework testing module currently lacks built-in functionality to simulate this process, leading many charms to roll their own patching and mocking mechanisms for unit tests.
To address this problem, this pull request introduces `ops.testing.Harness.handle_exec`, a new feature that enables the simulation of Pebble process execution within the Ops framework testing module.
See [spec OP039](https://docs.google.com/document/d/1V7nzFzSOIMVlPF-HCvTZZyWOGlHnCS__RyL5352P2e4/edit) for discussion.

Add process execution simulation to test harness

---

.github/workflows/observability-charm-tests.yaml
ops/pebble.py
test/test_pebble.py

The recommendation is to use the email.message.Message type. See example: https://docs.python.org/3.11/library/cgi.html#cgi.parse_header
Fixes #995

fix(pebble): remove use of deprecated cgi module in Pebble code

---

README.md
ops/testing.py
test/test_testing.py

When using testing.Harness, it's very common to see these two or three calls in a row: add relation, (often) add relation unit, and (often) update relation data. This addition simplifies those patterns down to just a single call, and without the need for the relation_id return value in most cases.
See additional justification and discussion at #992.
Fixes #992

Simplify Harness.add_relation by adding app_data and unit_data args

---

ops/pebble.py
test/test_pebble.py

When the `stdout` argument is provided to `ops.Container.exec` for capturing the stdout stream, the `ExecProcess` will have a `stdout` attribute of `None`. To prevent potential null safety issues, an error is now raised in such cases within `wait_output`.

Raise error in wait_output if stdout is already being consumed

---

ops/model.py
test/test_model.py

This avoids the caller modifying the Secret instance's dict.
Fixes #999

fix(model): ensure Secret.get_content returns a copy of the dict

---

ops/model.py
test/test_model.py

This is so that if get_content() is called after, it fetches and returns the expected new content. We could also set self._content to the new content, but re-fetching it from Juju seems better.

fix(model): make Secret.set_content invalidate local cache

---

.github/workflows/observability-charm-tests.yaml

I believe this was the fix on their side: https://github.com/canonical/prometheus-k8s-operator/pull/513

ci: reinstate prometheus-k8s-operator tests as it's been fixed

---

.github/workflows/framework-tests.yaml

Pebble uses Go as of canonical/pebble#/171, so we need to adjust the ops CI to also do so for the real Pebble tests.

ci: use Go 1.20 for real Pebble tests

---

ops/model.py

Simplify the `open_port()` and `close_port()` documentation:
* Link to the Juju documentation ([soon to also be updated](https://chat.charmhub.io/charmhub/pl/heqdxrtrkjyotdn8iikcpegbxh)) to minimise the amount of syncing required
* Note that the behaviour differs between K8s sidecar and machine charms
* Remove the note that `juju expose`/`juju unexpose` is required (true for machine, not true for k8s sidecar)
Fixes #918

docs: reduce the amount of detail in the open/close port methods

---

pyproject.toml
test/test_infra.py

Minor type hinting to make pyright happy:
```
$ env PYTHONPATH=.tox/static/lib/python3.10/site-packages/ .tox/static/bin/pyright test/test_infra.py 
WARNING: there is a new pyright version available (v1.1.317 -> v1.1.327).
Please install the new version or set PYRIGHT_PYTHON_FORCE_VERSION to `latest`
0 errors, 0 warnings, 0 informations 
```
Also renames an unused variable to `_` to get rid of an IDE warning.
Partial fix for #1007.

test: add type hints to the test_infra tests

---

pyproject.toml
test/test_log.py

Minor type hinting to make pyright happy:
```
$ env PYTHONPATH=.tox/static/lib/python3.10/site-packages/ .tox/static/bin/pyright test/test_log.py 
WARNING: there is a new pyright version available (v1.1.317 -> v1.1.327).
Please install the new version or set PYRIGHT_PYTHON_FORCE_VERSION to `latest`
0 errors, 0 warnings, 0 informations 
```
Most significant change is that the fake model backend now inherits from the real one.
Partial fix for #1007.

test: add type hints to test_log tests

---

ops/jujuversion.py
pyproject.toml
test/test_jujuversion.py

JujuVersion's comparisons can be done against strings as well as other JujuVersions, so the type hints should reflect that.
For mocking the os.environ response, the type is dict(str, str) but I think to declare that we would need to define the dict, e.g:
```
_mockenv : typing.Dict[str, str] = {}
@unittest.mock.patch("os.environ", new=_mockenv)
```
And that looks considerably messier to my eyes and doesn't seem to really add value (so I've ignored the warning).
Partially fixes #1007

test: fix type hinting on test_jujuversion tests

---

pyproject.toml
test/test_private.py

It looks like there's an accidental double-call in these two tests. They still pass, since the ValueError isn't caught in the second call, but that means that the second call isn't doing anything at all. It would also be weird if the code changed and allowed the values being tested because instead of the test failing in the expected way (the assertRaises failing) it would fail because a TypeError would be raised instead of ValueError.
This also makes pyright happy because we're not (theoretically) passing a datetime.datetime when a string is expected.
test_private is otherwise fine:
```
$ env PYTHONPATH=.tox/static/lib/python3.10/site-packages/ .tox/static/bin/pyright test/test_private.py 
WARNING: there is a new pyright version available (v1.1.317 -> v1.1.327).
Please install the new …
```

test: fix type hint warnings in test_private tests

---

ops/testing.py
pyproject.toml
test/test_testing.py

One minor (type) change to ops.testing: the harness `pull()` signature is changed to allow `encoding==None`, which matches the actual `pebble.Client` method.
Otherwise, changes are in test_testing:
* Explicitly ignore types where we are testing invalid type behaviour
* Use `assert`s to show type checkers that `obj|None` is always `obj` in a few places - this seems better tn tests than `cast(obj_type, obj)` and pyright doesn't understand that this is the case with `assertIsNotNone(obj)`
* Remove two `print()` calls, one of which seems to be a debugging print that slipped in, and one that's not required although the expression being printed is
* Replace a few `dict(a=b, c=d)` with `{'a': b, 'c': d}` as pyright seems to understand the latter much more easily (plus it's insignificantly faster …

test: add type hinting to test_testing

---

pyproject.toml
test/test_storage.py

* Ignore the `None`s passed when creating the framework - passing real values would be a lot of extra noise without actually gaining any value in the test
* Add dummy methods to make the `Serializable` protocol match
* Ignore types when replacing a (when type checking) property
* Inherit from StoredStateData rather than Object to match the type of the `Framework.save_snapshot` method - the additional methods seem harmless in this case, and the meaning of the test seems unchanged
* Sprinkle enough type hints so that pyright can tell what's happening
Partially addresses #1007

test: add type hints for test_storage

---

CHANGES.md
ops/framework.py
pyproject.toml
test/test_framework.py

* Change the type of `Handle`'s `key` (in `__init__` and `nest()` and the property) to explicitly allow `None
* Add a CHANGES.md file to document changes (backfilled only to 2.7)
* Tidy up the type hinting of `BoundStoredState.__getattr__` - multiple overloads need to be provided, and once that's done the ignores can be removed (and a bunch of type issues in the tests get resolved)
* Ignore type where creating an object that's only partially complete, but the test only requires that much and fully creating it would be a lot of extra code for no real gain
* Where's it's simple to do, pass the required attributes rather than `None`
* Ignore types where we're checking handling of invalid types
* Add casts around the very dynamic snapshot/restore functionality
* For a couple of the "list of …

test: add type hints to test_framework

---

ops/model.py
test/test_model.py
test/test_testing.py

Instead of just recursively iterating through the remote/local files, also iterate through the directories as well, ensuring that they are created even if they don't contain any files.
Also create/update relevant test cases.
Fixes #968

fix: push_path and pull_path include empty directories

---

ops/charm.py
test/test_charm.py

This field is already supported in `metadata.yaml` but just not exposed in `RelationMeta`. Expose it. Further discussion in #799.
Fixes #799

feat(charm): add RelationMeta.optional

---

.github/workflows/db-charm-tests.yaml

In canonical/mysql-k8s-operator#313, the unit tests were changed to expect a LIBJUJU_VERSION_SPECIFIER envvar to be present when the tests are run. This is used in those tests to run the tests simulating Juju 2.9 and 3.1.
Adjust our running of the mysql-k8s-operator tests to also provide this value, fixed at 3.1. (This is also present for the other 3 DB operators, but that should do no harm).

ci: Pass LIBJUJU_VERSION_SPECIFIER to the mysql-k8s-operator unit tests

---

.github/workflows/db-charm-tests.yaml

With [canonical/mysql-k8s-operator#320](https://github.com/canonical/mysql-k8s-operator/pull/320) merged, we should no longer require the temporary workaround from #1036.

ci: remove the temporary mysql-k8s-operator unit tests workaround

---

ops/pebble.py
test/test_pebble.py
test/test_real_pebble.py

Filter the 'pebble socket does not exist' case from the existing try/except block and raise a more helpful exception in that case.
Although the content of the exception message is not really part of the API contract, since we're deliberately changing it, extend the unit test to check that the message has been changed.
Fixes #844

feat: provide a clearer exception when the Pebble socket is missing

---

ops/charm.py
ops/testing.py
test/test_testing.py

Currently you can't really call `Harness.evaluate_status()` twice in one test because it keeps the previous collected statuses around. Reset them before evaluating.
I believe this addresses https://github.com/canonical/operator/issues/736#issuecomment-1762094066

fix(testing): reset collected statuses in Harness.evaluate_status

---

HACKING.md
ops/charm.py
ops/framework.py
ops/model.py
ops/pebble.py
ops/storage.py
ops/testing.py

If we raise an exception when checking an argument's type, and the type hinting covers this, I have not included it in the `Raises` list. I feel that the docs (and a type checker) cover this already, and the `Raises` section should be more focused on exceptions that the Charmer should consider handling.
#908 goes back-and-forth on documenting very common exceptions (like `APIError` and `CommunicationError` in nearly all pebble `Client` methods), and I have as well. ~I'm currently +0 on documenting them, and it seems like it's simpler to add them all in the PR and them remove them than decide to add them after the initial PR, so they are included at the moment. I could easily be convinced that they should be removed and a central doc note added (but I'm not sure where that would be best).~ …

docs: document more of the exceptions that may be raised

---

CHANGES.md
ops/model.py
ops/testing.py
test/test_model.py
test/test_testing.py

Adds a new `reboot` method to `Unit`, that's a wrapper around the `juju-reboot` command.
`juju-reboot` is only available for machine charms. When it's run for a K8s charm, Juju logs an error message but doesn't return an response with the error (or have a non-zero exit), which means that we have to fail silently.
Adds a corresponding `reboot()` method to the harness backend.
From the point of view of the harness, we assume that everything is essentially the same after rebooting without `--now`, so this is a no-op. The most likely change that would impact the harness would be a leadership change, but it seems better to let the Charmer model that explicitly in their tests.
When rebooting with `--now`, what should happen is that everything after that point in the event handler is skipped, …

feat: add Unit.reboot for machine charms

---

README.md
ops/__init__.py

This is part of a larger initiative to update and streamline the READMEs of all the main projects associated in the Juju universe.

[JUJU-4553] Update README.md to simplify and better align with docs

---

.github/workflows/framework-tests.yaml
ops/testing.py
requirements-dev.txt

Adjust the dev requirements to be pinned to the latest compatible version of the currently used major.minor version.
This should make breakage like the current issue with flake8 & Python 3 less common, and generally encourage developing using the latest versions of the dev tools (picking up bug fixes and security fixes in particular).
Pyright doesn't use semvar and newer versions have issues with some of the hinting we use (it's unclear whether this is limitations in Python, or a pyright bug, or something we should fix ourselves) so leave it tightly pinned to the same version.
Changes one line of (ops.testing) code to avoid an issue raised by newer flake8 (using `!=` to compare types, rather than `is not` for an exact match or `not isinstance` for looser checks).
Temporarily use Python …

chore: pin the dev requirements to major.minor compatible

---

ops/testing.py

docs: fix Harness.get_filesystem_root example

---

README.md

Add badges for the Github workflows (except publish) to the README.
These will show when viewing the README in a markdown reader that loads external images (e.g. on Github itself) but more importantly also show the CI status on [the Juju releases page](https://releases.juju.is).

docs: add workflow badges to the README

---

ops/framework.py

docs: clarify how custom events are emitted in emit docstring

---

ops/testing.py
test/test_testing.py

A charm that owns a unit secret always has manage permissions, regardless of which unit is executing the charm. However, an app secret has manage permissions if the charm is executing on the leader, and view permissions otherwise ([the matrix in this WIP documentation](https://discourse.charmhub.io/t/secret-access-permissions/12627) has been verified by @wallyworld).
This PR adjusts the Harness permission check (used by get-info, set, grant, revoke, remove, etc) so that if the secret is an app secret, then the leader flag must be set for access to be allowed.
Fixes #1071

fix: non-leaders can only view app secrets

---

test/test_framework.py

The behaviour of descriptors changed in 3.12, so that when `__set_name__` raises an exception, that exception reaches the code that did the name setting, with a note attached, unlike earlier Python where the exception was chained.
<details>
<summary>Minimal code</summary>
```python
import sys
print(sys.version)
class Foo:
def __init__(self):
self.name = None
def __set_name__(self, owner, name):
if self.name is not None:
raise RuntimeError("hello world!")
self.name = name
f = Foo()
class A:
x = f
try:
class B:
x = f
except Exception as e:
if hasattr(e, "__notes__"):
print(f"notes: {e.__notes__!r}")
print(f"cause: {e.__cause__!r}")
print(f"context: {e.__context__!r}")
print(f"str: {e}")
```
</details>
<details>
<summary>Python 3.11</summary>
```
3.11.5 (main, Oct  2 2023, 11:58:32) [GCC …
```

chore: update framework tests to pass under Python 3.12

---

.github/workflows/framework-tests.yaml
CHANGES.md
HACKING.md
ops/pebble.py
test/test_pebble.py
test/test_real_pebble.py

Exposes the `log-targets` section of the Pebble layer spec, to allow charms to configure log forwarding in Pebble without having to provide layers as plain YAML.
New types:
* `LogTargetDict`: a typed dictionary similar to `ServiceDict` and `CheckDict`.
* `LogTarget`: similar to `Service` and `Check`.
Changed types:
* `LayerDict` and `PlanDict` have (not required) `log-targets` keys.
* `Layer` and `Plan` have `log_targets` attributes (`Plan` is read-only, as with `checks` and `services`).
Fixes #1073

feat: expose the ability to set Pebble log targets

---

ops/model.py
test/test_model.py
test/test_testing.py

[Ned Batchelder noticed that the unit tests failed on his machine](https://hachyderm.io/@coveragepy/111477098431251147), which was because the temporary folder returned by `TemporaryDirectory()` belonged to a group with no name.
In theory, this could happen outside of the tests as well - someone could do a `push_path()` on a path that has files that have owners/groups that do not have names (e.g. because they have been removed). This is presumably quite uncommon (which makes sense: it seems unlikely that the charm container would often have a user or group removed) but it's also simple to fix, so it seems like we might as well do that.

fix: handle users/groups with no names in push_path

---

README.md

`charmcraft init` no longer produces a `metadata.yaml`, `actions.yaml`, `config.yaml` -- instead, it's just `charmcraft.yaml`. 
This PR updates the README to replace references to `metadata.yaml` with `charmcraft.yaml`.

docs: update README.md in light of changes to `charmcraft init` output

---

.github/workflows/db-charm-tests.yaml
requirements-dev.txt

This addresses the dependency issues with protobuf detailed here: https://github.com/go-macaroon-bakery/py-macaroon-bakery/issues/94
Also comment out mysql charm tests as they're broken at the moment.

fix: pin macaroonbakery version

---

ops/model.py

Adds documentation to `Container.push` to explain that it will fail if the remote file is locked or is a bind-mount.
Fixes #752

docs: document limitations with pushing locked or bind-mount files

---

HACKING.md

Figuring out how to test changes to `ops` locally (without just monkeypatching everything) wasn't straightforward when I started - this should make it easier for new people going forward.
I've included two variants:
* If the code is in a Git branch then I find it's simplest to just have the `charmcraft.yaml` file make `git` available and use standard Python dependency specification.
* If the code isn't easily installable by `pip`, then editing the `.charm` zip file is probably simplest - I've included @benhoyt's `inject-ops.sh` script to make it easy for people.
I've also added a small note about running in custom Juju versions, since that was something I had to learn today and seems like it might also come up for other people working on `ops`.

docs: add instructions on how to use a custom version of ops in a Charm

---

ops/model.py
ops/pebble.py
ops/testing.py
test/test_model.py
test/test_pebble.py
test/test_real_pebble.py
test/test_testing.py

This PR adds Harness support for Pebble Notices, specifically a new `Harness.pebble_notify` method which you call as follows -- this will add a custom notice with key "example.com/key" and some data:
```python
harness.pebble_notify('mycontainer', 'example.com/key', data={'optional': 'data'})
```
This will record a notice (which will be visible in the `Container.get_notice` and `Container.get_notices` return values) and, if the notice is new or repeated, trigger a `pebble-custom-notice` event like Juju would.
Note that I've based the fake Harness implementation on the Pebble Go code (for example, [`State.AddNotice`](https://github.com/canonical/pebble/blob/ecac3d4a3a6111e0ae1face2f9062f5210405826/internals/overlord/state/notices.go#L223) and …

feat: Harness support for Pebble notices

---

requirements-dev.txt

https://github.com/go-macaroon-bakery/py-macaroon-bakery/issues/94 is fixed now and version 1.3.4 of that project has been released, so this should not be needed any more.

fix: revert macaroonbakery exception now that underlying issue is fixed

---

ops/charm.py
ops/model.py
ops/pebble.py
ops/storage.py
ops/testing.py
pyproject.toml
requirements-dev.txt
test/test_charm.py
test/test_framework.py
test/test_model.py
test/test_pebble.py
test/test_real_pebble.py

So annoying how quickly this tooling changes. Couple of notes:
- ops/charm.py: it seems like the new version disallows overriding the type in a subclass, so just use a "pyright: ignore" comment to work around this. Maybe there's a better way.
- The new Pyright no longer allows a type variable to be defined inside a function. Not sure what the rationale for this was, but they have to be moved to the top level (away from where they're used!) now.
- Some of the bytes/str/bytearray stuff is annoying. Maybe there are better solutions for these types. Oh for Go's io.Reader.
Suggestions to improve any of these welcome.

fix(typing): update to latest version of Pyright and fix errors

---

HACKING.md
ops/model.py
ops/testing.py
test/test_testing.py

This small enhancement:
1. documents that `ErrorStatus` and `UnknownStatus` is for read-only.
2. raises an ops.ModelError, which is the same behavior on real juju backend.

feat: model error on testing module if invalid status set by charm

---

ops/testing.py
test/test_pebble.py
test/test_testing.py

Issue: adding a layer with checks or log-targets isn't reflected in the plan you obtain when testing through get_plan()
solution: make it reflect

fix: add pebble log targets and checks to testing plan

---

.github/workflows/db-charm-tests.yaml

Also update links to mysql issues.

ci: reinstate postgresql-operator tests now that issue is fixed

---

docs/conf.py
ops/__init__.py
ops/_private/__init__.py
ops/charm.py
ops/framework.py
ops/model.py
ops/pebble.py
ops/testing.py
pyproject.toml
test/__init__.py
test/charms/test_main/lib/__init__.py
test/test_infra.py
tox.ini

This PR replaces flake8, flake8-docstrings, flake8-builtins, isort, autopep8, pep8-naming, pyproject-flake8, and two test_infra unit tests with ruff for linting. Formatting remains unchanged (to be addressed in #1103).
Notes:
1. Ruff does not yet implement all of the pycodestyle rules, which we checked/fixed with autopep8, see: https://github.com/astral-sh/ruff/issues/2402
2. Ruff implements all Flake8 rules (the "F" rules).
3. flake8-docstrings is not listed in the Ruff re-implementation list by pydocstyle is there, which flake8-docstrings is based on
4. Ruff reimplements flake8-builtins (but picks up much more than we were previously, which is odd).
5. Ruff's isort is "profile='black'".
6. With flake8 we had "R" rules enabled, but I can't figure out what those were, or what provided …

chore: move to ruff for linting

---

HACKING.md
ops/version.py

Also change the publishing instructions to post about the release on Matrix rather than Mattermost.

chore: bump version string for working on the next release

---

CHANGES.md
ops/charm.py
ops/framework.py
ops/main.py
ops/testing.py
test/test_charm.py
test/test_framework.py
test/test_main.py
test/test_testing.py

This PR exposes the `JUJU_ACTION_UUID` environment variable's value as `ActionEvent.id`.
Fixes #1121

feat: add the action's ID to the ActionEvent object

---

CHANGES.md
ops/charm.py
ops/framework.py
test/test_charm.py

There are two goals for this PR:
* Prevent charms from calling `defer()` on events where that makes no sense
* Alert charmers as early as possible when they are using `defer()` where it doesn't make sense
The original version of the PR adjusted the various event classes so that the events that shouldn't have `defer()` called didn't have the method at all. This achieves both goals (most IDEs and checkers will detect that a method is being called that isn't defined). However, that was too significant a change, as we could not maintain the pattern for creating custom events and also checks like `isinstance(action_event, ops.EventBase)`.
Instead, we continue with the same practice as we already use for `ActionEvent`, `SecretExpiredEvent`, and `SecretRotateEvent`:
* Set the return type to …

feat: only have a `defer()` method on events that can be deferred

---

ops/model.py

`can_connect()` is a point-in-time check, and, if used as a guard for interacting with Pebble, introduces a race condition where Pebble was responding at the `can_connect()` time, but is not when the rest of the work is done.
We already encourage people to handle errors communicating with Pebble when doing the later work (catching `ConnectionError`), which means that most of the time the `can_connect` call is not providing any value (and incurs a small cost). However, the documentation, particularly the example, encourages this pattern, and this has been copied to many other places (charm sources, docs).
This PR adjusts the documentation to be less encouraging of `can_connect()` use as a guard, and changes the example to one where a point-in-time check is wanted (for collecting unit …

docs: tweak the wording around can_connect() usage

---

CHANGES.md
docs/conf.py
ops/pebble.py
test/test_pebble.py
tox.ini

This PR adds two minor features to `pebble.Plan` objects to simplify testing (particularly with Scenario):
* The ability to compare two `pebble.Plan` objects, or a `Plan` with a `dict`, with `==` - comparison to any other type of object  will still return False.
* The ability to instantiate a `pebble.Plan` object from a `pebble.PlanDict` (or equivalent dict).
This aligns the `Plan` functionality with `Layer` objects.

feat: add the ability to compare two Plan objects with == and create a Plan from a dict

---

ops/charm.py
tox.ini

Currently, running `tox -e fmt` leaves the code in a state that `tox -e lint` complains about, for two reasons:
* Wrapping a line in ops/charm - I'm not sure why this difference exists since autopep8 and ruff have the same max line length (or why it wasn't picked up before we used ruff), but ruff is ok with the wrapped version, so it seems like the simple fix here is to just have it wrapped.
* "from x import a,b,c" style imports and wrapping.
For the import issue, if we adjust isort to use the "vertical hanging indent" mode (weirdly called "3") that gets most of the way there, but even though the docs show a trailing comma, one isn't included. However, if we use the `--split-on-trailing-comma` mode as well that does lead to a compatible format. We're not using the "force wrapping via …

chore: adjust isort to be more compatible with ruff

---

test/charms/test_main/src/charm.py

`tox -e fmt`, `tox -e lint` run in a loop should result in no changes and both passing.

chore: adjust the imports so that both ruff and isort pass

---

ops/charm.py
ops/model.py
ops/testing.py

The current Juju terminology is that apps "integrate" to form a "relation". This PR tweaks the API documentation to align with that wording.
Fixes: #1133

docs: use 'integrate with' rather than 'relate to'

---

ops/framework.py
test/test_charm.py

So this is a tricky one.
At times charmers are tempted to write:
```
class MyObj(ops.Object):
def __init__(self, charm, *args: typing.Any):
super().__init__(charm, "obj")
framework.observe(charm.on.start, self._on_start)
def _on_start(self, _):
raise RuntimeError()  # never reached!!! 
class MyCharm(ops.CharmBase):
def __init__(self, *args: typing.Any):
super().__init__(*args)
MyObj(self)  # not assigned!
framework.observe(self.on.start, self._on_start)
def _on_start(self, event: ops.EventBase):
pass  # is reached
```
and expect that both _on_start methods will be triggered, while due to some subtle implementation details, MyObj._on_start never fires because the notice is silently dropped if the weakref stored in Framework._observer has been gc'd between charm instantiation time and …

fix(framework): add warning on lost observer weakref

---

CHANGES.md
ops/model.py
ops/pebble.py
ops/testing.py
test/test_model.py
test/test_pebble.py

Pebble added support for notices, aggregated events that are recorded with a type and key. The `/v1/notices` API had a parameter "select=all" to show notices for all users, and the parameter name is changed to "users=all" in recent [release v1.9.0](https://github.com/canonical/pebble/releases/tag/v1.9.0).
This PR is the corresponding changes to the ops framework.
Related doc: [OP042 - User ID features for Pebble Notices
](https://docs.google.com/document/d/1tQwUxz-rV-NjH-UodDbSDhGcMJGfD3OSoTnBLI9aoGU/edit#heading=h.kavgppauvkj5)
See here: https://github.com/canonical/operator/issues/1132
- `pebble.Client.get_notices`
- `model.Container.get_notices`
- unit tests
```bash
TOTAL                       6389    472   2278    207    91%
unit: OK (79.29=setup[0.05]+cmd[77.96,1.28] seconds) …
```

fix(pebble)!: change select=all to users=all for pebble get_notices

---

ops/framework.py
test/test_charm.py
test/test_framework.py

When validating the `observe` arguments, inspect the signature of the method that we'll call, rather than digging down into any wrapped version, so that wrappers can adjust the signature as required, as long as the framework can still call them with the expected arguments.
This also fixes a bug where the check would fail to properly identify `*` and `**` as not required, so a signature like `def _on_x(self, event, *args, **kwargs)` would fail, even though the framework can use it to emit events.
Also remove the code that checks for `framework.observe(self.on.x, self)` style calls, which were possible in some old version of ops, and raises a specific error just for that (the general error is clear enough, and we don't believe anyone is still doing this).
When checking the type of the event …

fix: inspect the correct signature when validating observe arguments

---

ops/charm.py
ops/testing.py
test/test_charm.py
test/test_testing.py

One minor fix to the `storage` metadata: [charmcraft.yaml](https://juju.is/docs/sdk/charmcraft-yaml#heading--storage) and [metadata.yaml](https://juju.is/docs/sdk/metadata-yaml#heading--storage) support a `multiple.range` value in the form `<n>+` - this would previously error out when we attempted to read the metadata. We now support this (as an alias for `<n>-`, which is an open-ended range rather than "n or less", and have a test for it.
Adds a minor clarification in the API docs when `Harness.add_storage` will emit a storage-attached event.
In `begin_with_initial_hooks`, if the storage has already been attached, then don't try to attach it a second time, but *do* emit the storage-attached event, since that will not have been done previously.
Make the `_storage_attach` method safe to …

fix(harness): don't error out when attempting attaching storage before begin

---

CHANGES.md
ops/testing.py

Since we are encouraging charm tests to be written with pytest, we should use that in test code examples in ops.testing.
Only code samples from `ops/testing.py` are updated, other files/test cases are not updated.
Closes https://github.com/canonical/operator/issues/1154.

docs(testing): update code samples in ops.testing from unittest to pytest style

---

CHANGES.md
ops/model.py
ops/pebble.py
test/test_pebble.py

Tried to run some `container.exec` in a test charm with sleep, with some other long-running commands like apt-update, with or without timeout, but could not reproduce the issue.
Changed according to John's opinion: catch `socket.timeout` exception and continue polling till the end of the deadline.
Also updated docstring for `model.Container.exec()` and `pebble.Client.exec()`.
Closes https://github.com/canonical/operator/issues/826.

fix(pebble): catch socket.timeout exception in pebble.Client.exec()

---

CHANGES.md
ops/testing.py

Add a short paragraph about Harness `begin_with_initial_hooks` behaviour on peer relations in the docstring of method `add_relation`.
Closes https://github.com/canonical/operator/issues/1161.
Hold until RTD PRs are merged so that the lint/doc build can pass.

docs(Harness): add a paragraph on peer relations in add_relation

---

ops/version.py

[2.12.0 is live in PyPI now](https://pypi.org/project/ops/), bumping the version to 2.13.0.dev0.

chore: update version to 2.13.0.dev0

---

HACKING.md

Update `HACKING.md` "Publishing a Release` part.

docs: update publishing a release in hacking

---

HACKING.md
tox.ini

Separate pip-compile into a separate env `tox -e docs-deps`. Now `tox -e docs` only does `pip-sync` then `sphinx-build`.

docs: tox -e docs-deps to compile requirements.txt

---

.github/workflows/framework-tests.yaml
.github/workflows/hello-charm-tests.yaml
.github/workflows/publish.yml
.github/workflows/test-publish.yml
ops/pebble.py
test/test_pebble.py

This is new with health checks being implemented as changes and tasks (https://github.com/canonical/pebble/pull/409).
Ops/charms will likely not use this new field. Even once we have the new `change-updated` event, that has a `.get_change()` method to get the change directly. But we're adding it to the Pebble client/types for completeness.
We shouldn't merge this before that Pebble PR is merged, just in case anything changes.

feat: add pebble.CheckInfo.change_id field

---

ops/testing.py
test/test_testing.py

Add a `__str__` to `ops.testing.ActionFailed` so that an uncaught `event.fail()` in tests produces a more informative traceback.
Currently, `event.fail()` and `event.fail(message)` will look somewhat like:
```python
Traceback (most recent call last):
File "/tmp/1204.py", line 18, in <module>
harness.run_action("act")
File "/home/tameyer/code/operator/ops/testing.py", line 2001, in run_action
raise ActionFailed(
ops.testing.ActionFailed
```
After this PR, `event.fail()` will look like:
```python
Traceback (most recent call last):
File "/tmp/1204.py", line 19, in <module>
harness.run_action("act")
File "/home/tameyer/code/operator/ops/testing.py", line 2006, in run_action
raise ActionFailed(
ops.testing.ActionFailed: Event handler called `fail()` with no additional details.
```
and …

feat: add a `__str__` to ActionFailed, for better unexpected failure output

---

.github/workflows/framework-tests.yaml
test/test_helpers.py
test/test_main.py
test/test_storage.py

Refactor test_storage and test_main to pytest style.
`test_main.py`:
```bash
$ python -m tox -e unit -- test/test_main.py
unit: commands[0]> coverage run --source=ops/ -m pytest --ignore=test/smoke -v --tb native test/test_main.py
===================================================================== test session starts ======================================================================
platform darwin -- Python 3.11.8, pytest-7.4.4, pluggy-1.4.0 -- /Users/tiexin/work/operator3/.tox/unit/bin/python
cachedir: .tox/unit/.pytest_cache
rootdir: /Users/tiexin/work/operator3
collected 108 items
======================================================================= warnings summary ======================================================================= …
```

test: refactor test_main and test_storage

---

.github/workflows/framework-tests.yaml
test/test_model.py

Refactor `test_model.py` to pytest style.
Major changes:
- strip `unittest.TestCase`
- refactor setup functions to fixtures
- use parametrize where possible
```bash
$ python -m tox -e unit  -- test/test_model.py
unit: commands[0]> coverage run --source=ops/ -m pytest --ignore=test/smoke -v --tb native test/test_model.py
===================================================================== test session starts ======================================================================
platform darwin -- Python 3.11.8, pytest-7.4.4, pluggy-1.5.0 -- /Users/tiexin/work/operator4/.tox/unit/bin/python
cachedir: .tox/unit/.pytest_cache
rootdir: /Users/tiexin/work/operator4
collected 209 items
===================================================================== 209 passed in 55.48s …
```

test: refactor test_model to pytest style

---

README.md

Currently, [ops on PyPI](https://pypi.org/project/ops/) looks like this:
This PR replaces the `:point-right:` GitHub-specific markup with the actual emoji character so that it shows as expected in both places.

docs: use the actual emoji character rather than GitHub markup, to show properly on PyPI

---

ops/model.py
ops/pebble.py
ops/storage.py

Removes use of f-strings in `logging.debug` and `logging.warning` calls.
Calls to `logging.*` should provide a format string and arguments (generally we use `%` style, but `{` or `$'` would be ok, if inconsistent). There are two main reasons:
* Some log handlers (most well known is Sentry, but I believe there are others) will aggregate messages using the format string, and this breaks if the string is pre-interpolated.
* Interpolation/formatting is done lazily - for example, a debug level message may never get formatted - so there is a (very small) efficiency gain by avoiding it when possible.
Theoretically, there are also safety concerns in having user-provided content, but that's not relevant for any of these cases here, and I think you'd have to _also_ provide an argument to exploit …

fix: don't use f-strings in logging calls

---

ops/model.py
test/test_model.py

Fixes the signature for `RelationDataContent.update` to match `MutableMapping`, where `other` is optional (a regression introduced in #1883).
The type for `other` has been simplified to `Any`. It should really be `Mapping|_SupportsKeysAndGetItem[str,str]` plus a minimal type that supports `.values`, but it was already messy pulling in `_SupportsKeysAndGetItem` in #1183, and we're just passing this through to `MutableMapping` so it doesn't seem like the tight typing is providing enough benefit to justify the complexity of the signature. [typeshed has three overloads](https://github.com/python/typeshed/blob/f7c03486ee01c8ea74823db75e017341bf3c2ad0/stdlib/typing.pyi#L726), so we could match that (as we did in #1883, just incompletely), if that is desirable.
Fixes: #1225

fix: the `other` argument to `RelatationDataContent.update(...)` should be optional

---

.git-blame-ignore-revs

Ignore bulk changes done by the Ruff formatter.
PR: https://github.com/canonical/operator/pull/1224
Commit: https://github.com/canonical/operator/commit/d8148ab41869f6119683cf42b7e6e574f1a99bf1
To configure git to use this file, run:
``` bash
git config --global blame.ignoreRevsFile .git-blame-ignore-revs
```

chore: add git blame ignore revs file

---

.github/actions/update-charm-pins/action.yaml
.github/actions/update-charm-pins/main.py
.github/actions/update-charm-pins/readme.md
.github/actions/update-charm-pins/requirements.txt
.github/workflows/charmcraft-pack.yaml
.github/workflows/db-charm-tests.yaml
.github/workflows/hello-charm-tests.yaml
.github/workflows/observability-charm-tests.yaml
.github/workflows/update-charm-tests.yaml
.gitignore
HACKING.md

Switch to using pinned versions of the charm (latest main) for our charm tests in the GitHub Actions.
Also I've re-enabled mysql-k8s charm test, as that apparently got fixed upstream.
Here's the configuration for the personal access token I'm using to develop the external charm "dependabot":
- read/write access to the repo
- `workflow` scope to push branches with changes to workflows

ci: automate pinning charms in regression tests

---

HACKING.md

Fix the links to [version.py](ops/version.py) so that they render correctly.

docs: fix links in HACKING.md

---

test/pebble_cli.py

Without this fix, running this raises the following:
```
TypeError: catching classes that do not inherit from BaseException is not allowed
```
Not sure how to silence pyright without the type: ignores.
I guess we haven't used this script in a while. :-)

fix: fix TypeError when running test.pebble_cli

---

.github/workflows/charmcraft-pack.yaml
.github/workflows/db-charm-tests.yaml
.github/workflows/framework-tests.yaml
.github/workflows/hello-charm-tests.yaml
.github/workflows/observability-charm-tests.yaml

I've noticed that when a new commit is pushed to a PR, the same tests are run twice: once triggered by `on: push` and another by `on: pull_request: synchronize`
---
Note that the two runs are not exactly same, if the target (main) branch has received updates in the meantime, because:
This workflow runs the tests on the new commit in the feature branch as it stands alone.
It doesn't consider any changes that might have been merged into the main branch since the feature branch was last updated.
This workflow runs the tests on the combined state of the feature branch and the main branch.
It effectively simulates a merge between the feature branch and the main branch to see if the combined state would pass the tests.
---
to do

ci: only run tests once on push to pr

---

CHANGES.md

* No intro text as found on the GitHub page and various announcements.
* No attribution.
* No links to issues.
* Remove conventional commit type in favour of headings.

doc: adjust the 2.14 changelog to match our style

---

ops/pebble.py

This is the fix for the issue described at https://github.com/canonical/operator/issues/1246. Essentially, if the Pebble timeout has already elapsed, Pebble will happily wait indefinitely for the connect to go through, and the Python side will hang. Add a timeout during the connect phase to cut this short.
Fixes #1246.

fix: add connect timeout for exec websockets to avoid hanging

---

pyproject.toml

We had originally included the wrong email address (.com instead of .net). This fixes that. All the thousands of fan mails that have been inevitably sent to us have been lost forever. ;-)

fix: correct email address in PyPI project metadata

---

test/test_log.py

Calling `setup_root_logging` changes `sys.excepthook`. The tests should undo this in the same way that they clear out the logging handlers that `setup_root_logging` adds.

fix: properly clean up after running setup_root_logging in test_log

---

README.md

The link to `HACKING.md` needs to be a fully-qualified link so that it shows up correctly on PyPI

docs: fix HACKING.md link

---

HACKING.md

Explain that we use conventional commits, and list the types and scopes that we're starting with.

docs: add a section to HACKING.md on PR titles (commit messages to main)

---

.github/dependabot.yaml
.github/workflows/update-charm-tests.yaml

Unfortunately dependabot.yaml doesn't support saying "25th of each month", just "monthly" which is hard-coded to the 1st. But that's probably okay for that one.

chore: make dependabot and update-charm-tests only happen monthly

---

.github/workflows/semantic-pr-check.yaml
.github/workflows/validate-pr-title.yaml

As documented in #1252
- types taken from the doc PR
- scopes were scraped from project PR history

ci: validate PR title against conventional commit rules

---

ops/charm.py
ops/framework.py
ops/model.py
ops/testing.py
test/test_model.py
test/test_testing.py

Adjust Harness so that the errors match what Juju does in practice (I tested each case - the results are in a table in a comment in #1229).
* When Juju responds with a message including "not found", we raise `SecretNotFoundError`
* When Juju responds with any other message (such as "permission denied"), we raise `ModelError`
* When Juju succeeds and only fails at the completion of the hook, we raise `RuntimeError` - in production, the charm cannot catch this, but we do want to surface this error, so `RuntimeError` seems most approprate
In addition:
* Update the documentation to clarify when secret content is cached (this was a request from the discussion with the data platform team in Madrid)
* Correct the documentation regarding when `ModelError` and when `SecretNotFoundError` will be …

fix: adjust Harness secret behaviour to align with Juju

---

.github/workflows/db-charm-tests.yaml

When running `poetry lock` in the CI workloads, only update the ops dependency, not all dependencies. We want to know whether the proposed changes to ops would break the charm's tests, not whether updating all dependencies, including the proposed ops changes, would do so.
This is one of the suggestions in #1272. Using `poetry add --lock` seems slightly cleaner than the `sed` system we currently use, but I wasn't able to easily figure out how to do that with a `ops = { path = "ci/path/for/ops/branch" }` type specifier. It seems like this approach is at least an improvement on the existing one, even if not perfect. (It also will unblock other PRs, given that the tests fail because we're re-locking in entirety).
Fixes #1272.

ci: only update ops, not all dependencies

---

.github/workflows/publish.yml
.github/workflows/test-publish.yml

This PR adds [artefact attestation](https://github.blog/2024-05-02-introducing-artifact-attestations-now-in-public-beta/) to the ops builds. Essentially: users are able to verify that the wheel and source dist tarball produced by the build script were actually generated by the workflow in this repo (and not, for example, uploaded by someone else that got access to the PyPI account).
The `test-publish` workflow is also updated to use the `build` backend, which was missed when the main script was migrated.  Annoyingly, [we are still waiting for access to the operator package on test.pypi.org](https://github.com/pypi/support/issues/3349).

ci: add artefact attestation (using GitHub / SigStore)

---

.github/dependabot.yaml
.github/workflows/charmcraft-pack.yaml
.github/workflows/db-charm-tests.yaml
.github/workflows/framework-tests.yaml
.github/workflows/hello-charm-tests.yaml
.github/workflows/observability-charm-tests.yaml
.github/workflows/publish.yml
.github/workflows/test-publish.yml
.github/workflows/update-charm-tests.yaml
.github/workflows/validate-pr-title.yaml
CHANGES.md
HACKING.md
README.md
SECURITY.md
docs/requirements.txt
ops/charm.py
ops/framework.py
ops/model.py
ops/pebble.py
ops/testing.py
pyproject.toml
test/pebble_cli.py
test/test_charm.py
test/test_log.py
test/test_model.py
test/test_testing.py

Adds a simple security policy, so that users can easily find out how to privately report security issues.
The policy states that 2.x will get security updates, which seems reasonable to me, but we could make that more recent versions if that was better.
The policy offers reporting via GitHub (which would need to be turned on) and to the security@ubuntu.com address - I think it's important to still offer an email (particularly encrypted email) mechanism, not just the GitHub one.
This is based on the [LXD policy](https://github.com/canonical/lxd/blob/main/SECURITY.md), and the [work to develop a Canonical security policy template](https://warthogs.atlassian.net/browse/SEC-4238) (internal link only, sorry).
See also [this Mattermost …

docs: add a basic security policy

---

docs/index.rst

The docstring of `main` is missing from RTD, this adds it back.
According to Dora, it would be nice to link to `main` in [here](https://juju.is/docs/sdk/ops#opsmain-1).
I don't have a very good solution to add it, did some testing, this is the best I can do, preview [here](https://ops--1273.org.readthedocs.build/en/1273/#module-ops.main).
Tried to put it in front of the first entry of the ops module but then the indentation for following items are wrong, since they are handled automatically by autodoc.
Also tried to add only the function `ops.main.main` instead of the module, in this way we can put it in front of [`ops.ActionEvent`](https://ops--1273.org.readthedocs.build/en/1273/#ops.ActionEvent), but it is still before [the big …

docs: add main to ops api reference

---

.github/workflows/framework-tests.yaml

[Pebble now requires Go 1.22](https://github.com/canonical/pebble/releases/tag/v1.15.0), so bump the CI real Pebble tests to match.

ci: bump the Go version to match Pebble

---

ops/model.py

Per discussion with @jameinel, `Maintenance` means "I'm not ready because of work that I need to do", versus `Waiting`, which is "I'm not ready because of work that other things need to do".
Also clarify when you should use a message for Active, and make wording a bit more consistent between docstrings.

docs: clarify distinction between maintenance and waiting status

---

ops/model.py
test/test_helpers.py
test/test_model.py

Change the mechanism used to pass secret values from ops to hook tools from command line to files in temporary directory.
Removes the 2MB total secret size limit imposed by command line length
Hook tool calls juju agent which in turn reads these files, I've confirmed with the Juju team that juju agent and charm code are run as the same user.

fix: use temp dir for secret data

---

HACKING.md

GH markdown converts angle-bracketed words into HTML tags, which, being unknown, are ignored by the browser.

docs: escape <major> etc in hacking.md

---

SECURITY.md

We strongly encourage charms to use the latest release of ops, and put in a lot of effort to make sure that there are no compatibility issues that would prevent that. As such, rather than promising to do security releases for a year of versions (with our monthly release cadence, this would generally mean 10-12 security releases), only promise to do one for each active major release (so that would be only for 2.x now, and might be 2.x and 3.x at some point in the future).
This is all that we promise, but we could, of course, choose to do more if there was some reason to do so on a case-by-case basis.
This seems to balance the amount of work required to do many small releases and the work that we put into compatibility better than the previous policy.

docs: security policy change to only support each active major release

---

ops/model.py
test/test_model.py

`secret-info-get` gives the expiry back in a field called "expiry":
```
$ juju exec --unit thirteensixteen/0 -- secret-info-get cqv88thtvhl393c8hs20
cqv88thtvhl393c8hs20:
revision: 1
label: food
owner: application
rotation: daily
expiry: 2024-09-04T23:12:09Z
rotates: 2024-08-16T23:12:10Z
```
We were incorrectly looking for it in a field called "expires", which is the attribute name we use.
Fixes #1316

fix: Juju passes the expiry in a field 'expiry', not 'expires'

---

.github/workflows/framework-tests.yaml

Python 3.13 has reached rc1, this PR adds it to the test matrix.
Note: not using free-threaded builds at this point due to  https://github.com/actions/setup-python/issues/771 (not like we'd expect any difference, frankly)

ci: run tests on Py 3.12 and install test on Py 3.13

---

docs/custom_conf.py
ops/charm.py
ops/main.py
ops/model.py
pyproject.toml

Adds the version features were added in Juju to the API reference docs (other than ops.testing).
No version tags are added for anything older than 3.0 - meaning that if there's no version tag, then it was available in the oldest supported Juju version.
Unfortunately, the built-in Sphinx `versionadded` directive does not support customising the text, so while otherwise suitable, it results in "Added in version 3.0" (seems like it's referring to ops 3.0) or "Added in version Juju 3.0". Instead, a new pair of custom directives are added, `jujuversion` and `jujuremoved`. These are very heavily based on `versionadded` and `versionremoved` but have custom text (and we could customise them further, e.g. linking to revision notes) if we wanted to in future). In order to avoid having to also add …

docs: add example Juju version markers

---

tox.ini

Distributing tests across multiple CPUs to speed up test execution.
On my 10-core mac m1, time is reduced by a little more than a third (~4m39s to ~3m3s). According to GitHub Actions it also speeds up proportionally to that (see [this run](https://github.com/canonical/operator/actions/runs/10417030729/job/28850433850?pr=1313) without pytest xdist and [this run](https://github.com/canonical/operator/actions/runs/10417133297/job/28850745589?pr=1319) with it).

test: run pytest in parallel with pytest xdist

---

HACKING.md
docs/custom_conf.py
ops/_private/__init__.py
ops/charm.py
ops/framework.py
ops/main.py
ops/model.py
ops/storage.py
test/__init__.py
test/charms/test_main/actions.yaml
test/charms/test_main/config.yaml
test/charms/test_main/lib/__init__.py
test/charms/test_main/metadata.yaml
test/charms/test_smoke/metadata.yaml
test/test_charm.py
test/test_framework.py
test/test_helpers.py
test/test_infra.py
test/test_main.py
test/test_storage.py
test/test_testing.py
tox.ini

Copyright notice line only needs file creation year (not range).
Full boilerplate from LICENSE.txt should be used (rather than a one line note to see LICENSE).
Copyright notice process documented in HACKING.md.
Resolves #1325

chore: standardise copyright headers

---

docs/conf.py
docs/custom_conf.py
pyproject.toml

This PR reverts the only edit to docs/conf.py, which was made in [this commit](https://github.com/canonical/operator/compare/9b2b3341ddfae77da27933297d80579b14aabdf1...8bae12d15013cf2d2b4119568a36ab55c6f01b1a), and enables linting of docs/custom_conf.py
The resulting linting errors have been resolved primarily via `tool.ruff.lint.per-file-ignores`, with one inline noqa (`copyright` variable shadows builtin), and the removal of a type annotation not in scope (`Node`). It didn't seem worth spending significant time to add docstrings and resolve the other errors at this point. In fact, I'm not entirely sure whether it's worth merging in these changes, as it sounds like we've yet to settle on how the docs code will be handled with respect to upstream going forward, but I figured I might as …

refactor: enable linting of docs/custom_conf.py

---

ops/model.py
ops/testing.py
test/test_model.py

The `SecretInfo` class exposed all the fields from `secret-info-get` exception `description`. This PR adds that field as well.
Fixes #1289.

feat: add the description field to SecretInfo

---

ops/framework.py
ops/main.py

fix: correct the signature of .events()

---

ops/pebble.py
pyproject.toml
test/pebble_cli.py
test/test_framework.py
test/test_main.py
test/test_pebble.py
test/test_real_pebble.py
test/test_testing.py
tox.ini

In preparation to enabling `reportUnnecessaryTypeIgnoreComment`, bumping pyright to today's latest.
super-tox run: OK (tested on host, macos)
- 58 charms pass against canoincal/operator@main
- 58 charms pass against dimaqq/operator@bump-pyright

test: bump pyright to 1.1.377

---

ops/__init__.py
ops/_private/yaml.py
ops/charm.py
ops/framework.py
ops/main.py
ops/model.py
ops/pebble.py
ops/storage.py
ops/testing.py
pyproject.toml
test/test_framework.py
test/test_helpers.py
test/test_jujuversion.py
test/test_model.py
test/test_pebble.py

Parent: https://warthogs.atlassian.net/browse/CHARMTECH-232
Covered in the parent epic:
- charmcraft analyse will validate that charm Python entrypoint calls ops.main
- it is static type checker’s job to ensure correct arguments to ops.main
- today, many charms do and have to do ops.main(ThisCharm)  # type: ignore 
- thus, type hints need to be improved so that typpe: ignore can be dropped
Plan in this story:
- upgrade pyright (not sure if strictly necessary, #1332)
- enabled pyright setting reportUnnecessaryTypeIgnoreComment
- include code that calls ops.main(SomeCharm) in every which legal way in ops tests somewhere
- pyright validates the positive case, that ops.main can be called with a charm class
- include code that calls ops.main() without a charm class
- pyright now validates that …

ci: make Pyright report unnecessary type ignore comments

---

tox.ini

docs: Live reload with sphinx-autobuild

---

ops/charm.py

typo: the CharmBase inheritance example should be an object, not a function

docs: typo on CharmBase inheritance example

---

ops/_main.py

So that it's easier to remove one day.

chore: note juju version on legacy workaround

---

ops/testing.py

Harness needs to provide a `JUJU_VERSION` value to set up the `_JujuContext`, but it doesn't have to be in `os.environ`, it can just be in the dictionary passed to create the `_JujuContext` object.
In production, `os.environ` would actually have this, so it's more realistic for it to be present, but it would also have lots of the other `JUJU_` environment variables as well, and we don't want to have Harness simulate all those in the environment - we want people working with the ops tools to access those, not the environment directly.
This change [broke the tests of at least one charm](https://github.com/canonical/charm-simple-streams/pull/22) because it patches the environment to have specific values, and then creating the `Harness` object changes that. It seems better for us to not do …

fix: avoid changing os.environ in Harness

---

ops/charm.py

Note that `juju trust` changes will trigger a config-changed event.
I couldn't find any other cases that aren't already mentioned in the `ConfigChangedEvent` doc that would trigger config-changed, so I hope this is all.
Fixes #1211.

docs: config-changed is triggered by Juju trust

---

CHANGES.md
ops/version.py

Normal preparation for a release, but for a maintenance branch - to get the os.environ change out.

chore: changelog and version bump for 2.16.1

---

ops/pebble.py

Change the links to the Pebble README to the Pebble docs site where the content now lives.

docs: update the links to the Pebble docs

---

.github/workflows/tiobe.yaml
.gitignore
tox.ini

We recently changed `tox -e unit` to not produce a coverage report. This PR adjust the TIOBE workflow to account for that - running `tox -e coverage` instead.
Since this will now be one of the main uses for that command, I've also moved the `coverage xml` command into the tox steps rather than being in the workflow, and adjusted the `.gitignore` accordingly.

ci: update the TIOBE reporting for the changes in coverage calculation

---

test/test_real_pebble.py

https://github.com/canonical/pebble/issues/80 is fixed (almost three years ago!) so we should enable this test again, as far as I can understand.

chore: re-enable test now that Pebble directory permissions are fixed

---

docs/custom_conf.py
docs/requirements.txt
ops/charm.py
ops/model.py
tox.ini

https://warthogs.atlassian.net/browse/CHARMTECH-171

docs: note about repeatedly setting secret value in Juju 3.6

---

test/test_model.py

No functional changes (including to the tests) - this just adjusts the imports so that the names from `unittest.mock` are imported into a `mock` namespace, rather than all into the module namespace.
Primarily, this ensures that `typing.Any` and `unittest.mock.ANY` are clearly distinguished by more than case, but it's also generally tidier ("Namespaces are one honking great idea").
See discussion in #1373.

refactor: keep the unittest.mock names in the 'mock' namespace

---

ops/charm.py

A `DeprecationWarning` is emitted whenever an instance of `CollectMetricsEvent`, `PreSeriesUpgradeEvent`, or `PostSeriesUpgradeEvent` is created (which should only be whenever there is an observed event of that type).
Documentation warnings were already added in an earlier PR.
Fixes #1280

chore: generate warnings for events that will be removed in Juju 4.0

---

ops/jujuversion.py
test/test_jujuversion.py

Adds a new property to `JujuVersion` indicating if the version of Pebble bundled with Juju supports log forwarding to Loki, with labels.
See discussion in #1230 around which version of log forwarding should be the cutoff for support, which landed on when labels were added.
Fixes #1230

feat: add a JujuVersion property for Pebble log forwarding to Loki

---

CHANGES.md
docs/index.rst
ops/__init__.py
ops/framework.py
ops/model.py
ops/pebble.py
ops/testing.py

Docs: Ops: Add top-level intro, clean up ops.module intro in light of that, flesh out ops.pebble and ops.testing intros a bit more
https://warthogs.atlassian.net/browse/CHARMTECH-183

docs: add top-level intro and module-level intros

---

ops/model.py
test/test_model.py
test/test_testing.py

This is a simple alternative to #1382, following @dimaqq's suggestion to just not use `StatusBase.register` as a decorator. In this PR we instead do so via `__init_subclass__`.

fix: fix type of StatusBase subclasses by calling StatusBase.register in __init_subclass__

---

test/test_model.py

These two tests change `os.environ` without restoring it afterwards, which means that the changes leak into other tests. Change that by using `monkeypatch.setenv`.

test: properly mock the environment

---

ops/model.py
test/test_model.py

As `StatusBase.__init_subclass__` is now used to automatically register status classes by name, and the old `StatusBase.register` decorator (1) shouldn't have been public, (2) shouldn't have been used externally anyway, (3) doesn't appear to be used in charms currently, and (4) isn't needed internally, let's deprecate it.
See also discussion on #1380.

refactor: deprecate StatusBase.register decorator

---

ops/charm.py
ops/model.py
test/test_charm.py
test/test_model.py

Each call to `secret-set` replaces the values in any previous `secret-set` call in the same hook. Since both `Secret.set_content` and `Secret.set_info` use `secret-set`, this means that doing both in the same hook would only retain the change from whichever was done last.
This PR changes the model backend to cache the secret metadata (from `set_info`) and add it into any subsequent `secret-set` calls. Although the metadata is only available to the secret owner, it does not seem so private that it is unsafe to keep it in memory for the duration of the hook execution.
There is an additional behaviour change here: previously calling `set_info` twice in the same hook would 'undo' setting metadata. For example:
```python
secret.set_info(label="foo")
secret.set_info(description="bar")
```
I …

fix: Secret.set_info and Secret.set_content can be called in the same hook

---

.github/workflows/smoke.yaml
test/smoke/test_smoke.py
tox.ini

We have some basic smoke tests, which are currently the only tests we regularly run against an actual Juju model. The tests deploy a basic charm and verify that it goes to `active` status (which happens in an `install` handler). However, these are currently only run if someone manually runs `tox -e smoke`. This PR adds running the tests on a schedule (currently monthly, in the days before we will likely do a release).
This tests:
* Juju 3.5 (latest stable 3.x - I suggest we *change* this to 3.6 when that's released, rather than *adding* 3.6). The smoke tests do not currently work with Juju 2.9 (I'm not sure if it's worth adding that at this point), but if that changes, it should only require a matrix change in the workload. The smoke tests use python-libjuju, which doesn't yet support …

ci: run the smoke tests on a schedule

---

docs/index.rst
docs/pebble.rst
ops/__init__.py

Pros:
* Significantly reduces the length of the right-hand sidebar for the main API reference
* Clearly delineates ops.pebble, which could legitimately used independently of ops as a Python Pebble API
* Separates duplication between ops.Container and ops.pebble into separate pages
Cons:
* Browser search-on-page is less useful (although we already started this process by splitting ops.testing out)
* Existing deep links into the docs will break (we should be able to find and fix the ones on juju.is/docs at least)

docs: move Pebble to a separate page

---

CHANGES.md
ops/version.py

Also add 2.16.1 to CHANGES.md and fix links in 2.16.0 changelog

chore: update changelog and bump version number for 2.17.0 release

---

ops/model.py

`WaitingStatus` should be used when waiting on an integrated charm. `MaintenanceStatus` should be used when waiting for something local to the charm. We missed an example in `can_connect()` when clarifying the statuses earlier in the year.

docs: use MaintenanceStatus for local issues

---

ops/charm.py

We decided in #1265 that, for backwards compatibility, the behaviour of collect-status won't be changing. That is, it will continue to run at the end of every hook, even if the charm does not provide any observers for that hook. This PR makes this clear in the docs. Closes #1265.

docs: explicitly document that collect-status is is run on *every* hook

---

.github/dependabot.yaml

For GitHub actions dependabot PRs: only use the `dependencies` label, rather than both that and `github_actions`.
For pip (Python) dependabot PRs: we only have security dependabot PRs enabled, so add the same label restriction (avoiding a `python` label) but this requires adding a section to configure dependabot, and then essentially disabling most of it by setting the maximum PRs to 0 (security PRs will still be opened).

ci: configure the labels for dependabot PRs

---

docs/custom_conf.py

Currently we use the [Open Graph configuration](https://github.com/canonical/operator/blob/df9afbe28a1dff24ffc0e4f58a6fcb1cf5560ac6/docs/custom_conf.py#L88C1-L98C82) from the canonical-starter-pack without any modifications, but we should use the hosting url for our docs instead of theirs.
The Open Graph configuration is used by Sphinx to generate the Open Graph Protocol (ogp) properties in our docs pages. This information is used when generating link previews, for example when linking to our docs in Mattermost messages:
The `ogp:url` properties are incorrect, e.g. 
```html
<meta property="og:url" content="https://canonical-starter-pack.readthedocs-hosted.com/state-transition-testing.html" />
```
In practice these urls seem to be ignored in link previews, but let's fix them anyway since …

docs: use our docs url for the ogp:url properties Sphinx generates

---

docs/custom_conf.py

As of October 7th, the `html_context` dictionary is meant to contain a `READTHEDOCS` key set to True if that's in the environment variables, so this change does that.
We may see small changes in the visual look of the docs but everything should keep working with this small adjustment.
[Instructions from Read the Docs](https://about.readthedocs.com/blog/2024/07/addons-by-default/)
Fixes #1393

docs: set the READTHEDOCS context variable

---

HACKING.md
STYLE.md

This adds the very start of a team Python style guide, with a few items we've discussed recently. The idea is to add as things come up (more than once) in PRs and we feel it's worth adding them to the style guide to avoid having to make a specific decision each time.
The specifics in this PR are up for debate. I feel fairly strongly about "avoid nested comprehensions" and "spell out abbreviations", but quite weakly about "Compare enum values by equality".
Another thing that's up for debate is where this should live. It's kind of a team style guide, but we don't really have a place for team stuff like this (yet), and I'd much prefer it in a .md file in a repo than a Google doc.

docs: the very start of a team Python style guide

---

docs/custom_conf.py

Fixing the issue where the ad doesn't show up on the left navigation bar even if there is empty space for it.
See the issue here: https://github.com/canonical/operator/issues/1393, and the related PR: https://github.com/canonical/operator/pull/1410.
Preview: https://ops--1414.org.readthedocs.build/en/1414/.

docs: fix rtd ad placement

---

README.md
ops/__init__.py
ops/framework.py

Adjustments to the `StoredState` documentation:
* For `StoredDict`, `StoredList`, and `StoredSet`, note that charms would not normally create these directly and would use `StoredState` instead.
* Explain where the data is stored (there is one case that it doesn't mention, where there is already a unit-state DB locally, but I think that complicates things too much to specify here).
* Explain what happens when the charm is upgraded and recommend using a peer relation over stored state for K8s charms that want data preserved across upgrades.
As a related drive-by: remove the `jujuremoved` tag for `use_juju_for_storage`, since this won't actually be going away with Juju 4.0.
Fixes #1270

docs: clarify where StoredState is stored, and the upgrade behaviour

---

.github/workflows/build_scenario_wheels.yaml

This hasn't been fully updated to handle the location in the merged repo, but has been enough to wrongly release an `ops.version.version` release (and tag) on merge to main.
Disable this for now so that we don't accidentally have another `ops.version.version` release. I'll do a follow-up PR that properly implements ops-scenario releasing alongside ops releases.

ci: disable the automatic ops-scenario releasing

---

testing/src/context.py
testing/src/mocking.py
testing/src/ops_main_mock.py

As part of the merge of the `ops-scenario` repo into this one, `ops-scenario` now requires ops 2.17+. This has the added benefit that we can get rid of the compatibility code that supported ops 2.15 and ops 2.15.
With the pyright "detect ignores that aren't needed" check enabled again, some additional ignores can also be removed.
Closes https://github.com/canonical/ops-scenario/issues/192 (rather than copying it into this repo).

chore: remove compatibility code with older ops

---

testing/src/mocking.py
testing/tests/test_e2e/test_status.py

This copies across the fix from Harness to also be present in Scenario: if `status_set` is passed anything other than the valid statuses, then `ModelError` is raised (to better mimic what the Juju hook would actually do).
Closes https://github.com/canonical/ops-scenario/issues/202 (rather than copying it over to this repo).

fix: raise ModelError on unknown/error status set in Scenario

---

test/test_pebble.py
tox.ini

Upgrade pyright version to the latest (1.1.385).

chore: upgrade pyright to 1.1.385

---

.github/workflows/framework-tests.yaml

Fix Python version warnings and go cache warnings in github actions.
Closes https://github.com/canonical/operator/issues/1346.
On the go cache warning: By default [the cache is enabled](https://github.com/actions/setup-go/blob/main/action.yml#L15), but in our case, since we only need go to install Pebble and there is no `go.sum` file, there is no need for the cache, see the logic [in the code here](https://github.com/actions/setup-go/blob/main/src/main.ts#L67-L79). So I am disabling the cache explicitly, which should not make the actions run slower but should suppress the warnings.
See a successful run [here](https://github.com/canonical/operator/actions/runs/11402361559) and there is no more warnings.

chore: fix ci warnings

---

ops/framework.py
ops/pebble.py
pyproject.toml
test/test_main.py
test/test_model.py
test/test_pebble.py
test/test_storage.py
tox.ini

Currently, we are using ruff 0.4.5 but recently 0.7.0 was released, this PR upgrades ruff to 0.7.0 for both formatting and linting.
Closes https://github.com/canonical/operator/issues/1335.

chore: upgrade ruff to v0.7.0

---

.github/workflows/published-charms-tests.yaml

When handling charms that used poetry, the workflow would do a clone of the ops repo, tweak the poetry.lock file to include it and then re-lock. This leaves a copy of the ops repo around, and sometimes the ops tests get picked up by pytest, which is not what we want here.
The PR changes this to use the proper `poetry add` functionality to add the appropriate version of ops, in the same way that the requirements.txt files are updated.
Additional related fixes:
* The test runs for the charmcraft profiles also had the operator clone but never used it, so remove that.
* The charmcraft profile can safely run the static checks (since the charms are so minimal), and that would have caught an issue previously, so add that.

ci: use the actual poetry command, rather than manually tweaking the file

---

.github/workflows/framework-tests.yaml

Python 3.13 has been released yesterday.
Let's enable it in our CI.

chore: Python 3.13 has been released, remove allow-prerelease

---

.github/workflows/validate-pr-title.yaml

https://matrix.to/#/!eNCNzcteYUDDYpStsu:ubuntu.com/$PjGy1bizJkNGgu-A629wckDFKPzEQ5BKXIkmlE8sUyg?via=ubuntu.com&via=matrix.org
> Huh, looks like we have a small bug in the CI:
>
> > Canceling since a higher priority waiting request for 'Validate PR Title-refs/heads/main' exists
> 
> which happened for this PR: https://github.com/canonical/operator/pull/1447
> 
> surely the concurrency group should not be set to "main" for a new PR, should it?

ci: fix PR title ci job concurrency

---

ops/pebble.py

This was just a copy-n-paste error, presumably from copying from the `start_services` docstring.

docs: fix copy 'n' paste error in stop_services docstring

---

ops/model.py
test/test_model.py

There was a bug in `push_path` where it called `open` with the default (text) mode on the local files, causing it to not work on binary files (more specifically, if they weren't valid UTF-8). This is the fix for that -- `push_path` should treat the files as raw bytes, so read in binary mode.
Also change the test to ensure binary / non-UTF-8 files work as expected.
Fixes #1455.

fix: make push_path open in binary mode so it works on non-text files

---

testing/src/scenario/mocking.py
testing/src/scenario/ops_main_mock.py
testing/src/scenario/runtime.py
testing/tests/test_runtime.py

Properly use the `ops.jujucontext._JujuContext` class in Scenario.
When `_JujuContext` was introduced in ops, we added some quick compatibility code to Scenario that made use of it, but it was basically just recreating the context object from the environment everywhere.
This PR tidies things up in two main ways:
* Create a single `_JujuContext` object and pass it around where it's required. This also sets the stage for using the ops `_Manager` class in a later PR.
* Rather than updating and then later (imprecisely) reverting `os.environ`, just pass the mock environment directly when creating the `_JujuContext` object.
Note that to maintain backwards compatibility of public methods the argument is optional in some places and will fall back to the environment - this won't be exactly the …

refactor: use _JujuContext in Scenario

---

.github/workflows/observability-charm-tests.yaml

Proposing a fix to https://github.com/canonical/operator/pull/1461 deleting commented out repos

ci: a better way than commenting out external repos

---

.github/workflows/publish-ops-scenario.yaml
.github/workflows/publish-ops.yaml
.github/workflows/test-publish-ops-scenario.yaml
.github/workflows/test-publish-ops.yaml

Include the name of the package being published in the workflow title, so that there aren't two called "Publish" etc.

ci: use more descriptive names for the publish workflows

---

tox.ini

Miguel, our TIOBE contact, has asked that we move the XML coverage file that gets loaded, to `.report/coverage.xml`. This also means we can avoid using a custom data file name, which is nice.

ci: move the XML coverage report to .report

---

testing/src/scenario/context.py
testing/src/scenario/ops_main_mock.py

Closes #1444.
This change enables passing the Charm type all the way from the Context to the charm attribute in the manager for better autocompletion and type checks.
You can give this a try with the following code snippet:
```python
from ops import CharmBase
from testing.src.scenario import Context, State
class MyCharm(CharmBase):
some_attribute: str
def test_function():
ctx = Context(MyCharm)
state = State()
with ctx(ctx.on.config_changed(), state) as manager:
charm = manager.charm
charm.some_attribute  # behold, autocompletion!
```
A word of caution, though, the testing module is not using the bundled scenario code base. It is still using `ops_scenario`. For users to benefit from this new feature, we would need to change the import machinery.

feat: Make Context and Manager variadic types

---

testing/src/scenario/_consistency_checker.py

This was incorrectly changed during the import of the ops-scenario code to this repo. As discussed in #1429, having an object in the state that has the same identifier as the object in the event is insufficient and could end up being confusing: it should be the same actual object.
As well as reverting the previous change, adjust the error messages so that they're clearer if this case is triggered.
Fixes #1429

fix: require the same object to be in the testing state as in the event

---

CHANGES.md
ops/version.py
testing/CHANGES.md

This is for the 2.17.1 release of ops. Changes that only affect ops[testing] are waiting at the top of testing/CHANGES.md for the next release of ops[testing].

chore: update changelogs and bump version number for 2.17.1 release

---

.github/workflows/observability-charm-tests.yaml

Took 5 attempts, but I got the syntax right after all.

chore: fix skipping disabled observability charms

---

.github/workflows/publish-ops-scenario.yaml
.github/workflows/test-publish-ops-scenario.yaml

The build step is already done in `./testing/`, but the publish and attestation steps are not, which mean they fail because they cannot find the `dists` folder.

ci: all the ops-scenario publish actions need to be done in testing/

---

.github/workflows/published-charms-tests.yaml

When `uv` is used (as with self-signed-certificates-operator), the published-charms-tests workflow doesn't know how to inject the latest version of ops (there's no requirements.txt file).
This PR updates the workflow to look for `uv.lock` and if it exists then it uses `uv` to change the `ops` source in `pyproject.toml`.
self-signed-certificates-operator doesn't use `uv` to do the install in `tox` so we have to modify the raw sources list rather than have it be uv-specific. However, this should work even for projects that do, since the raw list is the originator of the dependencies - we might need to re-lock if other projects handle this differently, but we don't for now, so I've avoided that.
I've tested this manually, and have it manually against the branch (where it did install ops from …

ci: add support for injecting the latest ops when uv is used

---

.readthedocs.yaml
docs/custom_conf.py
docs/requirements.txt
pyproject.toml
testing/src/scenario/state.py
tox.ini

This PR fixes the version of ops-scenario used when building the docs.
Previously, the published version of ops-scenario was used for generating the documentation, and the generated requirements file was used for local builds but not for read-the-docs.
That breaks if there are local incompatible changes (such as renaming a module), and is generally wrong anyway.
With this PR, the local version is loaded, and read-the-docs uses the same requirements file as building locally. A few minor type annotations were adjusted to remove remaining warnings (I don't know why Sphinx couldn't figure out where `Path` was coming from, but keeping it in the `pathlib` namespace is generally nicer anyway).
Split out from #1467.

docs: use the right ops-scenario for building the docs

---

HACKING.md

Changes:
- Drop "ops" from the release title - we don't seem to include "ops" in practice
- Use ops[testing] in the release title in case of a release that includes ops[testing]
- Choose the previous tag after setting the new tag - the GitHub UI forces this order
- Exclude chores from CHANGES.md - we clarified that decision yesterday
- For an ops-only release, recommend to store any scenario-only changes at the top of testing/CHANGES.md
- Recommend to add backticks for code formatting in CHANGES.md

chore: update and clarify release process

---

testing/src/scenario/_ops_main_mock.py

This PR changes Scenario to always use `:memory:` as the location for the unit state database, to speed up running tests.
In most cases, the charm root location is a `TemporaryDirectory`, so the unit state database only exists during the event emission anyway. The database could be accessed if a specific root directory was provided (or inside the context manager context) but the correct way to interact with the database is through the State API (deferred events, saved state objects) so we don't want to leave that open for users.
Timing (best of 3):
|Suite|main|branch|
|-|-|-|
|operator unit tests (no concurrency)|4m11.923s|3m41.354s|
|traefik scenario tests|3m49.479s|1m56.795s|
|kafka-k8s-operator scenario tests|0m13.463s|0m13.236s|
Note that this [is already the case for …

feat: use :memory: as the unit state storage location for ops.testing

---

testing/src/scenario/state.py

The Scenario code that limits the number of positional arguments (needed in Python 3.8 since the dataclasses there do not have `KW_ONLY`) is quite expensive. For the case of `JujuLogLine`, it's not actually providing any value, because both of the arguments can be positional. `JujuLogLine` objects are created frequently (one per logging call), so the cost of creation matters a lot for the test performance.
This PR changes `JujuLogLine` to be a regular frozen dataclass. There are other performance improvements possible in the max-positional-args code (most significant of which would be only using it for Python 3.8 and 3.9) but this one-line change provides most of the benefits, so seems worth doing before any more significant work.
Timing (best of 3):
|Suite|main|branch|
|-|-|-|
|operator …

refactor: don't use the max-positional-args parent class for JujuLogLine

---

.github/workflows/framework-tests.yaml

A test can pass on one python/os version and fail on others, and it’s nice to see that in the outcome, rather than dig into cancelled tests which may or may not have hit the failing case.
Since unit tests are cheap and fast, we’re not really saving much by cancelling them – by the time one unit test run fails and asks the others to cancel, they’ll already have been spun up and run many of the tests, so cancelling them doesn't save much.
The pip-install and test-real-pebble jobs are faster than the test job, so this commit adds fail-fast: false to them too.

ci: don't cancel other unit tests when one fails

---

test/test_main.py
test/test_model.py
testing/src/scenario/mocking.py
testing/tests/test_context_on.py
tox.ini

Our tests currently end with a very large list of warnings. This PR fixes that:
* All of the Harness tests emit a `PendingDeprecationWarning` telling us that Harness is going away and we should use Scenario. This seems like something to simply ignore in our own tests, so I've added a `-W` argument to Python to silence them in bulk.
* One `test_main` test raises a warning about controller storage going away - there's another test that tests that warning happens, and the two tests are otherwise identical. I've merged the two - we don't need them both.
* Two of the secret tests check that `SecretInfo` objects can still be created without providing the model UUID. I've added a `pytest.warns` to (a) ensure that there's the warning, and (b) stop it appearing in the tox output.
* Scenario should …

test: handle warnings generated by our own tests

---

ops/_private/harness.py
testing/src/scenario/_runtime.py
testing/src/scenario/state.py

The Scenario code that limits the number of positional arguments (needed in Python 3.8 since the dataclasses there do not have `KW_ONLY`) is quite expensive. We have a method of providing this functionality in 3.8, but it is unfortunately expensive, and therefore a regression from older versions of Scenario.
I considered 4 options here:
* Manually write out the dozen or so `__init__` signatures (as we had at one point in the [original PR](https://github.com/canonical/ops-scenario/pull/137)). I'd rather not for the same reasons we made the decision at that time.
* Figure out a way to have a syntax that allows using regular `dataclasses.KW_ONLY` with modern Python and only use our custom code on older Python. I spent some time looking into this, and couldn't figure out a way to do it where …

refactor: cache signature structure in ops.testing state classes

---

.github/workflows/tiobe.yaml

Per [instruction](https://discourse.canonical.com/t/end-of-the-year-update-for-tiobe-tics-required-action-to-disable-tics-cicd-pipelines/4890) (internal link only, sorry), we need to temporarily disable reporting to TIOBE.

chore: temporarily disable TIOBE reporting

---

docs/howto/index.md
docs/howto/manage-actions.md
docs/howto/manage-configurations.md
docs/howto/manage-leadership-changes.md
docs/howto/manage-libraries.md
docs/howto/manage-logs.md
docs/howto/manage-relations.md
docs/howto/manage-resources.md
docs/howto/manage-secrets.md
docs/howto/manage-storage.md
docs/howto/manage-the-charm-version.md
docs/howto/manage-the-workload-version.md
docs/howto/run-workloads-with-a-charm-kubernetes.md

Adjustments to the how-to guides:
* Links to the API reference are updated to the new location. I assume that these can be references that will automatically resolve somehow, but I'm not sure how to do that, so I opened #1506 and just fixed them as full links for now (at least they'll work again).
* A few minor whitespace cleanups.
* Removed all the Harness sections, moving the Scenario sections up to be "unit tests"
* Updated the Scenario sections to use ops.testing and Scenario 7
* Updated the secrets how-to to be more explicit about needing to remove revisions if you create new ones.
[Live preview](https://ops--1507.org.readthedocs.build/en/1507/)

docs: update how-to guides to use the new unit testing framework

---

docs/explanation/testing.md
docs/howto/get-started-with-charm-testing.md
docs/howto/write-scenario-tests-for-a-charm.md
docs/howto/write-unit-tests-for-a-charm.md

Small adjustments to the how-to guides on testing to make it clear that Harness is deprecated:
* Tweak the general guide so that it's still basically saying the same thing, but refers to Scenario rather than Harness.
* Adjust example tests to use ops.testing Scenario classes rather than Harness.
* Make sure it's clear that `ops[testing]` should be installed to write unit tests.
* Use Scenario from `ops.testing` rather than from `scenario`.
Note that this does not substantially change the testing documentation: there's a roadmap item to do that later in 25.04.
[Live preview](https://ops--1508.org.readthedocs.build/en/1508/)

docs: clearly deprecate Harness in the testing how-tos

---

docs/.sphinx/_templates/footer.html
docs/index.md

Updates to some of the boilerplate links in the docs:
- "Join our online chat" now goes to Charm Development instead of Ops Library Development
- "Report bugs" now goes to GitHub issues instead of the repo home
- Adjusted "doc" to "docs" in the title of the issue that's started if you click "Open a GitHub issue for this page"
**[Preview build](https://ops--1515.org.readthedocs.build/en/1515/)**

docs: update boilerplate links

---

testing/README.md

The previous syntax made Markdown treat the entire paragraph as the title. I don't think this was intended. Maybe there was originally a list or something else at this point, but this changes the formatting back to a normal title for a single sentence, and then the following paragraph is formatted normally.
Copied from @jameinel 's PR in the old repo: https://github.com/canonical/ops-scenario/pull/205
(I accidentally made this change in 0c55e6473c604c7f041fbc92201d59429fec070d).

docs: fix Markdown syntax in ops.testing readme

---

.github/workflows/publish-ops-scenario.yaml
.github/workflows/test-publish-ops-scenario.yaml

`working-directory` is specifically for `run` steps. For the `gh-action-pypi-publish` action, `with: packages-dir` should be used.

ci: correctly point PyPI publishing to the ops-scenario packages

---

docs/explanation/holistic-vs-delta-charms.md
docs/explanation/testing.md
docs/howto/get-started-with-charm-testing.md
docs/howto/manage-actions.md
docs/howto/manage-configurations.md
docs/howto/manage-leadership-changes.md
docs/howto/manage-relations.md
docs/howto/manage-resources.md
docs/howto/manage-secrets.md
docs/howto/manage-storage.md
docs/howto/manage-the-workload-version.md
docs/howto/run-workloads-with-a-charm-kubernetes.md
docs/howto/write-scenario-tests-for-a-charm.md
docs/howto/write-unit-tests-for-a-charm.md
docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/open-a-kubernetes-port-in-your-charm.md
docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/preserve-your-charms-data.md
docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/write-unit-tests-for-your-charm.md

This PR addresses #1506
- Fixed links that broke after the library docs were moved under [Reference](https://ops.readthedocs.io/en/latest/reference/index.html). See 8d62861 (for Harness-related links) and 1d8374e (for other links). For some of the Harness-related links, I set the links to use the full doc title "ops.testing.Harness (legacy unit testing)" to help emphasise that Harness is legacy.
- In [How to run workloads with a charm - Kubernetes](https://ops.readthedocs.io/en/latest/howto/run-workloads-with-a-charm-kubernetes.html), fixed a link to `ops.Container.isdir`. See b5d5528
- In [Manage relations](https://ops.readthedocs.io/en/latest/howto/manage-relations.html), fixed a link to `ops.RelationChangedEvent`. See a2e84e9
- Replaced absolute links to `ops.testing` by a cross …

docs: fix broken links and use cross references instead of absolute links

---

ops/__init__.py
ops/_private/harness.py
ops/charm.py

A while back we decided to recommend using an explicit `framework` parameter instead `*args` to a charm's `__init__`. We've updated `charmcraft init` templates, but we forgot a few places in our docs. Update them to match here.
[Preview](https://ops--1523.org.readthedocs.build/en/1523/reference/ops.html#ops.CharmBase)

docs: use explicit framework param instead of *args

---

HACKING.md

This PR adds a few style tips to the Documentation section of HACKING.md (the same ones we added to Pebble in https://github.com/canonical/pebble/pull/556).

docs: add doc style tips to HACKING.md

---

docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/set-up-your-development-environment.md

This PR fixes the link to Juju on this page: https://ops.readthedocs.io/en/latest/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/set-up-your-development-environment.html
Fixed issues:
- The link points to "Tear down automatically" in the Juju instructions. It should point to the full instructions for setting up automatically.
- The link doesn't render properly because of a missing `)` at the end.

docs: fix link to Juju docs in Kubernetes charm tutorial

---

README.md

This is currently broken (because the workflow was renamed), but rather than fix it, we've decided that it doesn't really add any value to have this badge, so we'll remove it instead.

docs: remove the publish badge from the README

---

test/test_real_pebble.py

When running the real Pebble, it's possible that the tests fail more than twice when the test code is running. For the purposes of the test, we only care that it's at least twice (more than the threshold).
Fixes #1524

test: allow check to fail an additional time when running the test

---

docs/explanation/storedstate-uses-limitations.md
docs/howto/index.md
docs/howto/manage-stored-state.md

This continues the previous work in moving chapters of the tutorial to how-to guides.
The how-to guide covers:
* Storing state with `StoredState` objects
* Storing state in a peer relation
Minor tweaks are also made to the "stored state uses and limitations" explanation doc, to which the how-to links.

docs: add how-to for storing state

---

ops/log.py
ops/main.py
test/charms/test_main/actions.yaml
test/charms/test_main/src/charm.py
test/test_main.py
test/test_main_invocation.py
testing/src/scenario/_ops_main_mock.py

Background:
* A `warnings.warn` call outputs to stderr by default.
* Juju captures stderr and when executing an action provides it to the user.
* We emit a DeprecationWarning when charms call `main()` other than `import ops ... ops.main()`
* DeprecationWarnings are ignored by default, *except* for issues in the `__main__` module.
* A warning like this is meant to be discovered during tests - but unit tests typically do not call `main()` or execute the `charm.py` file, so they will not trigger this warning. That means that we're relying on integration tests.
The above means that, currently, the deprecation warning is included in the action output - this warning is intended for the developer of the charm, not the user of the charm, so we want to change this.
Firstly, the `ops.main.main` …

fix: remove ops.main.main deprecation warning, and avoid warnings in action output

---

HACKING.md
docs/index.md

This PR addresses a couple of issues:
- The "Contribute docs" link on the [docs homepage](https://ops.readthedocs.io/en/latest/index.html) points to https://github.com/canonical/operator/tree/main/docs, with no advice about how to get started.
- The Documentation section in [HACKING.md](https://github.com/canonical/operator/blob/main/HACKING.md#documentation) has irrelevant/outdated info and no clear advice about how to get started.
Main changes:
- In HACKING.md, split the Documentation section in two:
- Contributing documentation - Added a high-level process for how to contribute, removed irrelevant info about Discourse docs and the release process, put the build instructions in a subsection (and updated them), kept the subsection about style, put the info about doc versions in a …

docs: improve info about contributing to docs

---

docs/requirements.txt

There's a security release for Jinja (not one that impacts our use from what I can tell, but nice to just move to the updated version anyway). While bumping that, bump all the other dependencies as well.
This is just the result of removing the requirements file and regenerating it with `tox -e docs-deps`.

chore: update documentation dependencies

---

HACKING.md

This quick PR fixes a few formatting issues in HACKING.md, some introduced by me previously :roll_eyes:
See the commits for details.

docs: fix formatting errors in HACKING.md

---

ops/testing.py

The next version of ops-scenario renames the `runtime` module to `_runtime`. The `main` branch of `ops` currently expects that rename to have happened, but doesn't require it in the `[testing]` dependency. This means that `main@HEAD` `ops` doesn't work unless you also use `main@HEAD` of `ops-scenario`, which isn't the case in our compatibility checks - or in any charm that ends up with that combination.
We could fix this by adjusting the `ops` dependencies to require the newer `ops-scenario`, but that would really require releasing a new version of `ops-scenario`, and we're unlikely to be doing that before we also release `ops`.
The relevant code is only required until we release the next version of `ops-scenario` so for now just handle 7.0.5 as well as the newer code.
This will fix …

chore: fix compatibility with ops-scenario 7.0.5

---

.github/workflows/smoke.yaml

The smoke tests are currently failing because of `sg` behaviour changes in the `ubuntu:latest` runners. Rather than figure out what the solution for that is, this PR simplifies the entire environment setup to just use Concierge instead.
This also switches from testing against Juju 3.5 to 3/latest (which is 3.6), since 3.6 is available now and the intention was always to test against the latest 3.
A [run can be seen in my fork](https://github.com/tonyandrewmeyer/operator/actions/runs/13003299600).

ci: use Concierge to set up the smoke test environments

---

.github/workflows/tiobe.yaml

[Internal post saying it can be enabled again](https://discourse.canonical.com/t/end-of-the-year-update-for-tiobe-tics-disable-tics-cicd-pipelines-if-needed-service-will-be-shutdown/4890/6?u=tony-meyer).

chore: enable the scheduled TIOBE reporting again

---

.github/workflows/observability-charm-tests.yaml

The [upstream PR](https://github.com/canonical/prometheus-k8s-operator/pull/639) has been merged, so it should be fine for us to resume tracking the latest revision in our compatibility tests.

ci: enable the prometheus-k8s revision updates again

---

.github/workflows/smoke.yaml
tox.ini

Now that we're using Concierge running against Juju 2.9 works trivially, so we might as well include it for now, to avoid any breakage.
This also fixes the python-libjuju installation that broke in the last change (but still worked because the default is 3.x, which is what Juju 3.x needs).

ci: include Juju 2.9 in the smoke tests

---

HACKING.md

`tox -e docs-deps` produces subtly different result depending on which Python is used, as pip-compile uses that Python to resolve transient deps, so 3.10, 3.11, 3.12, 3.13 are all different.

chore: update docs-deps step in HACKING.md for the release

---

testing/CHANGES.md
testing/pyproject.toml

and prep for release
the idea is that we'd:
- release this as `ops-scenario=7.1.1`
- yank `ops-scenario=7.1.0`
the users can then either stay on old ops and old ops-scenario, or upgrade both
the automatic version resolution should work, I think :)

fix: require today's ops for today's ops-scenario

---

ops/storage.py

Fixing the db transaction when the db is being created in this dispatch call.
We commit the whole unit state on_commit()
If the DDL is committed early, then the rest of the operations are performed in the autocommit mode, potentially breaking the transactional guarantees the rest of the code assumes.
Meanwhile it is safe (and normal) to modify DDL within a transaction in sqlite.
Additionally, I feel that the transaction code was added to make doubly sure that two hooks cannot be run concurrently... Doesn't Juju guarantee that for us anyway?

fix: maintain transaction integrity on first run

---

docs/custom_conf.py
docs/howto/manage-actions.md
docs/howto/manage-configurations.md
docs/howto/manage-leadership-changes.md
docs/howto/manage-libraries.md
docs/howto/manage-logs.md
docs/howto/manage-relations.md
docs/howto/manage-resources.md
docs/howto/manage-secrets.md
docs/howto/manage-storage.md
docs/howto/manage-stored-state.md
docs/howto/turn-a-hooks-based-charm-into-an-ops-charm.md
docs/howto/write-integration-tests-for-a-charm.md
docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/preserve-your-charms-data.md
docs/tutorial/write-your-first-machine-charm.md

This PR sets up intersphinx for Juju and Charmcraft links and adds intersphinx-style links to Juju and Charmcraft in all the places we had bookmarked through UPDATE LINKS comments before (see https://github.com/canonical/operator/issues/1516 ).

docs: set up intersphinx and add links

---

ops/framework.py
test/test_framework.py

If an event has multiple observers, then if *any* of the (event+observer) pairs do not defer, then we need to save the snapshot so that it's available to process that (event+observer).
#1372 introduced a bug where if *any* of the (event+observer) pairs was skipped because an exact match was already in the deferral queue, we would skip saving the snapshot. This is ok if there's only a single observer, or if an (event+observer) that did not defer was processed before any that did defer, but not otherwise.
Fixes #1561

fix: ensure that the event snapshot is available when one observer defers and the other does not

---

docs/custom_conf.py
docs/explanation/storedstate-uses-limitations.md
docs/howto/get-started-with-charm-testing.md
docs/howto/manage-stored-state.md
docs/howto/write-integration-tests-for-a-charm.md

All the remaining "UPDATE LINKS" notes in the docs are replaced with actual links to the external Juju/Charmcraft docs.
Also changes the "product page" to be `juju.is` rather than `juju.is/docs/sdk` as the latter is going away (`juju.is` was recommended by @tmihoc).
(These changes were previously in [a commit in another PR](https://github.com/tmihoc/operator/commit/54dca52) but got lost when changes were forced - it seemed cleanest to break them out into a separate PR).

docs: fill out remaining external link placeholders

---

docs/explanation/charm-relation-interfaces.md
docs/explanation/interface-tests.md
docs/explanation/storedstate-uses-limitations.md
docs/explanation/testing.md
docs/howto/get-started-with-charm-testing.md
docs/howto/manage-libraries.md
docs/howto/manage-relations.md
docs/howto/write-integration-tests-for-a-charm.md
docs/howto/write-unit-tests-for-a-charm.md
docs/index.md
docs/reference/ops-testing.rst
docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/create-a-minimal-kubernetes-charm.md
docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/integrate-your-charm-with-postgresql.md
docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/observe-your-charm-with-cos-lite.md
docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/write-integration-tests-for-your-charm.md
ops/_private/harness.py
ops/charm.py
ops/model.py
testing/README.md
testing/src/scenario/__init__.py
testing/src/scenario/_consistency_checker.py
testing/src/scenario/state.py

Update documentation, mostly the content that used to be on Discourse, to use the noun form relation and the verb integrate.

docs: use noun relation and verb integrate

---

testing/src/scenario/_runtime.py
testing/tests/test_runtime.py

Rather than only put `JUJU_VERSION` into `os.environ`, copy the entire contents of the mock Juju environment variables (and after the run, put the environment dictionary back to the same state it was originally).
In general, we feel that charms should be using ops to access this information, rather than going directly to the raw environment variable, but this was too large a change to make in a refactoring bugfix release, and should wait for an 8.x release (and also ensuring that there are reasonable ways to get everything from ops - for example, the event name is perhaps too tricky to get globally right now).
Fixes #1572

fix: expose the mocked Juju environment variables via os.environ again

---

ops/jujuversion.py
ops/model.py
test/test_jujuversion.py
test/test_model.py

Charm code currently needs to do `JujuVersion.from_environ()` to get the Juju version. This isn't very 'ops-y' - we expose all the other Juju state through the `Model` object, and it also means that charms instantiate `JujuVersion` objects multiple times - even though the framework has actually done this already when parsing the Juju environment variables.
This PR exposes the Juju version via `Model.juju_version`, and deprecates the `JujuVersion.from_environ()` method (actual removal will presumably be in 3.0, a long time off).
This also centralises all the Juju environment variable processing in the `JujuContext` object.

feat: expose the Juju version via Model objects

---

docs/howto/index.md
docs/howto/manage-opened-ports.md

Add a basic how-to guide that covers using `Unit.set_ports` to set which ports are open, and unit and integration tests for such.
The intention is that this replaces the tutorial chapter (see #1511).

docs: add a how-to for setting open ports

---

ops/_private/harness.py
ops/model.py
ops/pebble.py
test/test_charm.py
test/test_model.py
test/test_pebble.py
test/test_testing.py
testing/src/scenario/mocking.py
testing/src/scenario/state.py
testing/tests/test_e2e/test_pebble.py
testing/tests/test_e2e/test_state.py

Add support for:
* The `startup` field in Pebble checks.
* The `start_checks` and `stop_checks` Pebble API calls.
Harness (and Scenario, mostly via re-using the Harness implementation) is adjusted to more closely simulate the Changes implementation of Pebble Checks, so that the 'if the change ID is the empty string, the check is inactive' behaviour can be simulated.
A subtle bug with notices and check-infos is also fixed: previously the mocked Pebble would gather all notices and check-infos from all containers in the state, instead of only those that are in the correct container.
[Pebble PR](https://github.com/canonical/pebble/pull/560)

feat: support starting and stopping Pebble checks, and the checks enabled field

---

docs/explanation/holistic-vs-delta-charms.md
docs/explanation/how-and-when-to-defer-events.md
docs/howto/get-started-with-charm-testing.md
docs/howto/manage-leadership-changes.md
docs/howto/manage-logs.md
docs/howto/manage-relations.md
docs/howto/manage-storage.md
docs/howto/manage-the-workload-version.md
docs/howto/run-workloads-with-a-charm-kubernetes.md
docs/howto/run-workloads-with-a-charm-machines.md
docs/howto/turn-a-hooks-based-charm-into-an-ops-charm.md
docs/howto/write-unit-tests-for-a-charm.md
docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/integrate-your-charm-with-postgresql.md
docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/set-up-your-development-environment.md
docs/tutorial/write-your-first-machine-charm.md

This PR replaces links to https://juju.is/docs/ by internal cross-references to other Ops pages or intersphinx cross-references to Juju pages (as appropriate).
**Not included in this PR**
- The link in https://ops.readthedocs.io/en/latest/howto/get-started-with-charm-testing.html#charmcraft-profiles that should point to the Charmcraft docs. I'll follow up with a separate PR after https://github.com/canonical/charmcraft/pull/2085 gets merged into Charmcraft.
- Links in the code samples of the Kubernetes tutorial (for example, in [Create a minimal Kubernetes charm](https://ops.readthedocs.io/en/latest/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/create-a-minimal-kubernetes-charm.html)). I think it would be better to tackle these separately when improving the tutorial - …

docs: fix links that pointed to earlier Juju docs

---

docs/howto/get-started-with-charm-testing.md
docs/tutorial/write-your-first-machine-charm.md

This PR updates [Get started with charm testing](https://ops.readthedocs.io/en/latest/howto/get-started-with-charm-testing.html):
- Added a link to [Write your first Kubernetes charm for a Django app](https://canonical-charmcraft.readthedocs-hosted.com/en/latest/tutorial/write-your-first-kubernetes-charm-for-a-django-app/) in Charmcraft
- Converted the existing link to [Write your first Kubernetes charm for a Flask app](https://canonical-charmcraft.readthedocs-hosted.com/en/latest/tutorial/write-your-first-kubernetes-charm-for-a-flask-app/) into an intersphinx link
**[Preview link](https://ops--1582.org.readthedocs.build/en/1582/howto/get-started-with-charm-testing.html)**
This PR also fixes unwanted brackets in [Write your first machine …

docs: update links to Charmcraft docs

---

.github/update-published-charms-tests-workflow.py
.github/workflows/observability-charm-tests.yaml
.github/workflows/published-charms-tests.yaml

* Bumps the uv version to 0.6
* Installs tox-uv for the published charms tests (fix via @james-garner-canonical)
* Use `uv add` rather than patching requirements.txt for the observability charms (grafana-k8s has moved to this approach)
* Re-run the update script to get the latest list of published charms

ci: update list of charms and handle increasing uv usage

---

docs/tutorial/write-your-first-machine-charm.md

This PR is for capturing small updates to [Write your first machine charm](https://ops.readthedocs.io/en/latest/tutorial/write-your-first-machine-charm.html) while I'm working on creating my own sample machine charm.
Summary of changes:
- Adjusted the "What you'll need section" to tidy up the language & formatting, and to clarify that familiarity with Juju is not an absolute requirement.
- When using `curl` to test the service after the initial deployment, we don't need to `juju exec` into the unit first. Instead, we can do `curl http://10.122.219.101:8080`, where 10.122.219.101 is the IP of the unit. I've updated the command and the preceding text to match.
- Added missing context to the note that comes after using `curl` to test the service. This note was supposed to say that the reader …

docs: small updates to machine charm tutorial

---

ops/model.py
ops/pebble.py

The version of Pebble that includes the start/stop check functionality has been [merged into Juju](https://github.com/juju/juju/pull/19037), so should be in the next Juju release. 3.6.3 is in candidate and 3.6.4 is edge, so I think that means it'll be in 3.6.4, so set that as the marker.
[Preview](https://ops--1592.org.readthedocs.build/en/1592/reference/ops.html#ops.Container.start_checks)

docs: add Juju version markers for start/stop checks

---

ops/_private/harness.py
test/test_testing.py

This PR addresses the TODO and notes in the start/stop/restart service methods of Harness (and via inheritance, Scenario).
* Raise an APIError rather than RuntimeError, with the same message as Pebble, when a service doesn't exist.
* Return a ChangeID, now that we're keeping track of these.
Also: check for an empty list of services and raise the same APIError as Pebble in that case.
Fixes #1310

fix: in tests, raise the same error as Pebble when an invalid service is provided

---

testing/tests/test_consistency_checker.py

This PR updates the `scenario` tests to sort any `set` parameters so that the ordering is guaranteed to be the same every time. This is necessary because `pytest-xdist` will error if workers have different (or differently ordered) tests, because it [refers to tests by index](https://github.com/pytest-dev/pytest-xdist/issues/432#issuecomment-506535968).
> each worker performs a standard collection, and sends the collected test ids (in order) back to the master node. The master node ensures every worker collected the same number of tests and in the same order, because the scheduler will from that point on send just the test indexes (not the entire node id) to each worker to tell them which test to execute. That's why the collection must be the same across all workers.
This resolves failures …

test: sort pytest params to guarantee identical ordering across workers

---

docs/custom_conf.py
docs/howto/run-workloads-with-a-charm-kubernetes.md
docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/create-a-minimal-kubernetes-charm.md
docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/make-your-charm-configurable.md
ops/pebble.py
testing/src/scenario/state.py

Just update the hard-coded docs links from https://canonical-pebble.readthedocs-hosted.com/ to https://documentation.ubuntu.com/pebble/

docs: update Pebble docs links to documentation.ubuntu.com/pebble

---

testing/tests/test_e2e/test_deferred.py

Pulled out from the OTEL branch.
Since life cycle events can't be deferred anyway, let's not observe them in these tests.
I hope this makes the tests more focused, and perhaps easier to maintain.
Inspired by #1589

refactor: when testing deferral, don't observe life cycle events

---

.github/workflows/published-charms-tests.yaml

This PR adds a steps to the `charm-tests` job defined in the `published-charm-tests` workflow to run the charm's `static` `tox` environment. The first step checks if the `static` environment exists, and the second step runs it if it does exist. Additionally, output and step ids are added to allow these steps to runeven if the unit test step fails, but not if there was a failure in an earlier step (installing dependencies, etc.) and not if the job was cancelled. Therefore a given job may be marked as a failure overall if both or either of the `static` and `unit` tests fail (if both fail, two failures will be listed for the job on the summary page for the workflow).

ci: run tox static environment for charms that have it

---

STYLE.md
ops/_main.py
ops/_private/harness.py
ops/charm.py
ops/framework.py
ops/jujucontext.py
ops/log.py
ops/main.py
ops/model.py
ops/pebble.py
ops/testing.py

Per discussion at daily. I thought this would be a trivial job, but the Ops imports are a bit of a mess, so it was a bit more work than usual.
As Dima pointed out, we have to be careful in public modules (like `ops.charm`) not to remove existing names or introduce new names. I think I've done that right, but please review that carefully. The one exception is when in `model.py` or similar I've not worried about removing `ops`, because if you're writing `ops.charm.ops.foo` you deserve an `AttributeError`, at least. :-)

chore: use relative imports

---

docs/explanation/interface-tests.md
docs/howto/manage-interfaces.md

Reading through some of the operator interface documentation, I came across a number of bugs which I was able to fix.
Addresses:
- grammatical tweaks
- broken link to `ops.testing`
- malformed internal references (mostly when try to embed `monospace` in the link text)
- removed dead link to external repository
Thanks!

docs: tidy interface test documentation

---

docs/howto/index.md
docs/howto/run-workloads-with-a-charm-kubernetes.md
docs/howto/run-workloads-with-a-charm-machines.md
docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/observe-your-charm-with-cos-lite.md
docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/write-scenario-tests-for-your-charm.md

This PR fixes some broken links (see my comments for details) and also the page titles of:
- https://ops.readthedocs.io/en/latest/howto/run-workloads-with-a-charm-machines.html
- https://ops.readthedocs.io/en/latest/howto/run-workloads-with-a-charm-kubernetes.html
I've changed the titles per our discussion in https://github.com/canonical/operator/issues/1581#issuecomment-2658234737.
I've also moved these two pages to the top of the How-to guides nav tree (per comments below).
**[Preview build](https://ops--1614.org.readthedocs.build/en/1614/)**

docs: fix some links and page titles

---

.github/workflows/observability-charm-tests.yaml
CHANGES.md
HACKING.md
docs/requirements.txt
ops/version.py
pyproject.toml
testing/CHANGES.md
testing/pyproject.toml

* Bump ops version to 2.19.1
* Bump ops-scenario version all the way to 7.19.1
* `ops[testing]` will only install `ops-scenario` version 7.19.1
* `ops-scenario` requires exactly `ops` 2.19.1
* Add CHANGES for 2.19.1 and 7.19.1
* Add missing CHANGES for 7.2.0
* Clean up the CHANGES from 2.19.0 (extraneous "in")
* Tweak the observability compatibility CI to use the latest merged versions rather than the ones from the PR branch (only for release)
* Tweak the docs build to use the latest published `ops-scenario` (only for release)
* Adjust the release instructions in HACKING.md to cover this process, all manual steps for now (we'll automate later on)

chore: prepare 2.19.1 and 7.19.1 releases

---

.github/workflows/publish-ops-scenario.yaml
.github/workflows/publish-ops.yaml

The observability tests need to install ops and ops-scenario, and they can't do that with the requirements in the branch, because they aren't available yet.
As a workaround for now, disable the requirement for these tests to pass in the maintenance branch. This should allow publishing both versions.
For the next release, we'll need to either do this again or implement the wheel solution or something similar.

ci: disable the observability tests requirement in publishing for the 19.1 branch

---

CHANGES.md
ops/version.py
testing/CHANGES.md
testing/pyproject.toml

The CI failed releasing 2.19.1 and 7.19.1, so this just bumps the version numbers to have another go, now that the observability tests are disabled in this maintenance branch.

ci: bump versions to 2.19.2 and 7.19.2

---

CHANGES.md
ops/version.py
pyproject.toml
testing/CHANGES.md
testing/pyproject.toml

Just like the previous bump but onto the 3rd attempt. Somehow the last release pushed 2.20.dev0 - I assume I must have selected the branch incorrectly in the releases page :disappointed:

ci: bump versions to 2.19.3 and 7.19.3

---

docs/requirements.txt

There's a security alert for Jinja 3.1.5. As far as I can tell, it's not relevant to our use (which is only in doc generation anyway), but it's nice to move to the fixed version even if just to silence the warning systems.
While we're doing this, bump the other doc dependencies (this is just generating a fresh `requirements.txt` via `uvx --python=3.11 tox -e docs-deps`).
I haven't read through all of the changes in each of the bumps, but for the ones that aren't micro bumps, certifi seems safe (and that's calendar versioning, not semver), sphinx-notfound-page seems safe, the starlette changes don't seem relevant, and the websockets changes don't seem relevant to docs (it's less clear for ops itself).

chore: bump doc dependencies

---

.github/workflows/observability-charm-tests.yaml
.github/workflows/published-charms-tests.yaml

We currently patch in the latest version of `ops`, but should really be also patching in the latest version of `ops-scenario` to make sure that we aren't breaking compatibility specifically in tests (at least as long as the latest versions are used).
[Observability run in my fork](https://github.com/tonyandrewmeyer/operator/actions/runs/13648333151)
[Broad compatibility run in my fork](https://github.com/tonyandrewmeyer/operator/actions/runs/13648336581)

ci: use the latest version of ops-scenario in the compatibility tests

---

testing/src/scenario/state.py
testing/tests/test_e2e/test_state.py

This PR has two changes to make the `testing.State` less mutable (or more immuntable as my Kiwi fingers keep typing).
* All of the components that have a dictionary or list attribute now deepcopy that attribute in `__postinit__`. The type annotations are also changed to `Mapping` and `Sequence` so static type checking should detect when charm tests try to alter these (the actual underlying types are still the ones passed, and default to dict and list).
* In `State.__deepcopy__` we deepcopy all of the items inside the collections (the relations, the containers, and so forth) - this means that all of these items are separate in the input and output states. This also includes the config.
This also fixes a small bug that was found by the new tests: `State.get_storage` was wrongly comparing …

feat: ops.testing.State components are less mutable

---

pyproject.toml
testing/pyproject.toml

We've had issues with the reliability of the `charm-tech` launchpad email address, and we don't ever actually get any contact via it.
This PR therefore drops the `charm-tech@lists.launchpad.net` email address from `pyproject.toml` (and therefore PyPI) for both `ops` and `ops-scenario`. Both projects have links to the GitHub repositories where issues and PRs and security reports can be created, and it's also pretty clear from both repositories who is actively working on the projects and so if someone needs to be privately contacted, they can always go via the GitHub profile.
Note that our CoC has an address `charmcrafters@lists.launchpad.net` -- I'm assuming that still works and is the correct one to have (a private contact method in the CoC does make sense).

docs: remove the charm-tech@lists.launchpad.net email address

---

ops/_private/harness.py
ops/pebble.py
test/test_pebble.py
test/test_testing.py
testing/src/scenario/state.py
testing/tests/test_e2e/test_pebble.py

* When merging `pebble.Check`s, an unset `startup` should not override a set `startup`. (Once set you can't go back to unset - you need to explicitly use enabled).
* When rendering services, checks, and log targets from a series of layers, Harness and Scenario were combining after sorting the items by name. Although Pebble uses filename sorting when reading initial layers from a directory, future layers are combined in the order they are added via the API. For Harness and Scenario, we need to use the order in which they were added - if the caller wants to simulate loading from the filesystem, they need to do that by calling `add_layer` in that order. The plan itself still sorts the services, checks, and log targets.
* When rendering services, checks, and log targets, if there are multiple …

fix: assorted fixes for Pebble layer merging in Harness and Scenario

---

testing/src/scenario/_consistency_checker.py
testing/tests/test_consistency_checker.py
testing/tests/test_context_on.py
testing/tests/test_e2e/test_pebble.py

Add some consistency checks for the `CheckInfo`s in `testing.Container`:
* If there is a `CheckInfo`, then the plan must have a check by that name, or Pebble would never have generated that info.
* The threshold, startup, and level values of the `CheckInfo` come from the check definition itself, so must match the plan.

feat: check that the check-infos in testing.Container match the plan

---

ops/_private/harness.py

Links to the documentation in the Harness pending deprecation warning, so that charmers know how to proceed, if they have no idea what "state transition testing" is (and don't go searching for "Scenario").
Fixes #1503

feat: add a docs link to the Harness deprecation warning

---

docs/custom_conf.py

This PR sets [maximum_signature_line_length](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-maximum_signature_line_length) to limit the length of signature lines. I've gone with 80 chars. If we want to squeeze out a few more chars, I think we'd be alright with 85 too. But even single-line long lines can be hard to read, so stacking at 80 seems good to me.
**[Preview build](https://ops--1641.org.readthedocs.build/en/1641/reference/ops.html)**

docs: stack args vertically for long signature lines

---

testing/src/scenario/state.py

This PR fixes items 3 and 4 in https://github.com/canonical/operator/issues/1623. Changes:
- In the description of `ops.testing.Mount`, changed "file" to "path". I verified that files and directories can both be mounted.
- In the description of `mounts` in `ops.testing.Container`:
- Simplified the example to show one file and one directory.
- Added the missing `location` and `source` keywords.
- Removed the part of the comment that duplicated the example in the docstring.
**[Preview build](https://ops--1637.org.readthedocs.build/en/1637/reference/ops-testing.html#ops.testing.Container.mounts)**
A couple of things I'm not 100% sure about:
- Is it worth wrapping the `source` args in `pathlib.Path`? `Mount()` accepts a string or a Path.
- Is it worth keeping the remaining part of the comment …

docs: clarify how to use mounts in ops.testing.Container

---

docs/explanation/testing.md

This PR adds a channel for microk8s for the test explanation doc in the CI section.
More information: when using the [charmed-kubernetes/actions-operator action](https://github.com/charmed-kubernetes/actions-operator) to setup an environment for integration test, with Juju 3.3+, microk8s needs a strict channel version. Without this setting, there will be an error like `juju "3.x.x" can only work with strictly confined microk8s`. See an [existing issue here](https://github.com/charmed-kubernetes/actions-operator/issues/70) and [an unmerged PR here](https://github.com/charmed-kubernetes/actions-operator/pull/57).
Related: https://github.com/canonical/juju-sdk-tutorial-k8s/pull/72.

chore: fix integration ci

---

docs/howto/run-workloads-with-a-charm-kubernetes.md

Referencing the issue, I don't think this needs a whole how-to, just a section with a couple of paragraphs seems sufficient.
Fixes #1402

docs: add section about services with long startup time

---

docs/explanation/holistic-vs-delta-charms.md

Fix indentation. It used a tab before, now everything is updated to spaces.
Before: https://ops.readthedocs.io/en/latest/explanation/holistic-vs-delta-charms.html
After: https://ops--1649.org.readthedocs.build/en/1649/explanation/holistic-vs-delta-charms.html

docs: fix code snippet indentation

---

.github/update-published-charms-tests-workflow.py
.github/workflows/published-charms-tests.yaml

The vault-k8s-operator repository is now a monorepo with both machine and k8s charms. The published charms broad compatibility test workflow doesn't know how to handle repositories where there are multiple charms yet, so disable checking that charm until it does.

ci: exclude vault-k8s-operator until the system can handle monorepos

---

.github/workflows/publish-ops-scenario.yaml
.github/workflows/publish-ops.yaml
CHANGES.md
ops/version.py
pyproject.toml
testing/pyproject.toml

Docs requirements are unchanged.
Observability and docs builds are both expected to fail in this PR due to the versions of each other that are required by each package not being released yet. They are temporarily disabled as release requirements in this PR, and will be restored when bumping the package versions post-release.

chore: add changelog and bump versions for release

---

.github/workflows/observability-charm-tests.yaml
.github/workflows/publish-ops-scenario.yaml
.github/workflows/publish-ops.yaml
HACKING.md
docs/requirements.txt
ops/version.py
pyproject.toml
testing/pyproject.toml
tox.ini

This PR bumps the post-release versions of `ops` and `ops-scenario`, and updates `HACKING.md` to reflect the process followed in this release. It also adds a fix for the failing `observability-charm-tests` (needed for the new versions in this PR), which should fix them for releases too, and updates the `docs-deps` tox environment that the docs build with the development version requirements.
Post-release, I've changed the dependency versions from `==$latest_release` to `==$dev_version`. To allow the docs to build with this change, I've modified the `docs-deps` tox environment to add the line `.` to the requirements before `./testing/`, which means that ops is installed from the local files first, then `ops-scenario`'s requirements requests the dev version when it's installed, and finds it …

ci: post-release versioning, release process update + workflow fix

---

HACKING.md

A tiny PR that adds a missing `--` in a `tox` command in HACKING.md.

docs: fix tox command in HACKING.md

---

ops/charm.py
ops/framework.py
ops/model.py
test/charms/test_main/src/charm.py
test/test_framework.py
test/test_main.py
test/test_model.py
test/test_pebble.py
test/test_testing.py
tox.ini

This PR bumps the ruff and codespell versions to their latest releases, and makes the changes recommended by ruff.

chore: bump ruff version to 0.11.2 and codespell version to 2.4.1

---

.git-blame-ignore-revs

This PR adds the mostly automatic changes from #1652 to the blame ignore file.

chore: add ruff version bump + formatting to blame ignore

---

HACKING.md
tox.ini

This is consistent with what we're recommending in OP061.

ci: rename "tox -e fmt" to "tox -e format"

---

test/test_pebble.py

Fix a flaky Pebble exec test.
Resolves https://github.com/canonical/operator/issues/1360.
After looking into it, I found that the flaky test happens because garbage collection (GC) can clean up other temporary objects when this test (`test_no_wait_call`) runs. If other temporary objects are cleaned up right before the `ExecProcess` object's cleanup method `__del__` is called, it makes the test sometimes catch the wrong ResourceWarning.
Since it's hard to reproduce this problem (not to mention consistently), I've been thinking about how to fix it. Here are a few ideas:
1. Force garbage collection: Call `gc.collect()` right after `del process`. Or even move the `client.exec` part outside the `with` block to shorten the time in the `with` block before GC happens.
- This would lower the …

fix: try to fix flaky pebble exec test

---

testing/src/scenario/_consistency_checker.py
testing/src/scenario/context.py

Gets rid of these warnings:
```
(operator) 🦐/c/operator (main)> uvx tox -e lint
lint: commands[0]> ruff check --preview
warning: Invalid rule code provided to `# noqa` at testing/src/scenario/_consistency_checker.py:204: U100
warning: Invalid rule code provided to `# noqa` at testing/src/scenario/_consistency_checker.py:208: U100
warning: Invalid rule code provided to `# noqa` at testing/src/scenario/_consistency_checker.py:230: U100
warning: Invalid rule code provided to `# noqa` at testing/src/scenario/_consistency_checker.py:268: U100
warning: Invalid rule code provided to `# noqa` at testing/src/scenario/_consistency_checker.py:300: U100
warning: Invalid rule code provided to `# noqa` at testing/src/scenario/_consistency_checker.py:383: U101
warning: Invalid rule code provided to `# …
```

chore: remove invalid ruff suppression

---

docs/howto/write-and-structure-charm-code.md

This PR clarifies the guidance in [Design your Python modules](https://ops.readthedocs.io/en/latest/howto/write-and-structure-charm-code.html#design-your-python-modules).
Main things that I'm clarifying:
- When to use private vs public methods
- What would go in `<workload>.py`
**[Preview docs build](https://ops--1670.org.readthedocs.build/en/1670/howto/write-and-structure-charm-code.html#design-your-python-modules)**

docs: clarify guidance about designing Python modules

---

README.md
docs/custom_conf.py
docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/make-your-charm-configurable.md

Links to https://documentation.ubuntu.com/juju/latest/ now require a Read the Docs login. This PR updates links to point to https://documentation.ubuntu.com/juju/3.6/ instead.
Since I'm changing code in the Kubernetes tutorial, I'll also open a corresponding PR to the [juju-sdk-tutorial-k8s](https://github.com/canonical/juju-sdk-tutorial-k8s) repo.
**Note:** This PR doesn't update any links to `juju.is/docs/*`. Those links already redirect to the 3.6 branch of the docs. They ought to be updated, but not so urgently. I'll do that separately (#1626).

docs: fix links to Juju docs

---

.git-blame-ignore-revs
pyproject.toml
testing/pyproject.toml

This PR adds the config changes that drove the formatting changes made in #1691. This includes adding a number of `per-file-ignores`, as the removal of the `tool.ruff.format` table in `testing/pyproject.toml` means that a number of `ops` linting rules are now being applied to `ops-scenario` for the first time. These will be fixed in subsequent PRs (issue: #1693).
This PR also adds the merge commit (https://github.com/canonical/operator/commit/54f03272439e1e7c450afc5e6b65222f640351fa) for #1691 to the git blame ignore list (which is why the formatting changes and config changes are being made in separate PRs).

chore: pyproject.toml changes and blame ignore for ops-scenario ruff formatting

---

ops/model.py

This PR adds `from __future__ import annotations` to `ops/model.py` and updates the annotations accordingly.
[Here is a diff](https://github.com/james-garner-canonical/operator/compare/2025-04/chore/test-pyupgrade..james-garner-canonical:operator:2025-04/chore/future-annotations-ops-model?expand=1) showing the manual changes layered on top of those that running `ruff` with `pyupgrade` enabled gives us -- the automated changes haven't changed types outside of annotations (casts, type aliases, generic inheritance), while this PR does.
Type aliases have been annotated with `TypeAlias` (imported from `typing_extensions` in `if typing.TYPE_CHECKING`) and had their annotations stringified  if needed.
I intend to update annotations in other `ops` modules, but I figured it was worth breaking it …

chore: use annotations from the future for ops/model.py

---

testing/tests/test_e2e/test_juju_log.py

This PR fixes a test that fails intermittently on main. It failed because it asserted that the last two log lines were specific ones, while the addition of tracing means that sometimes (but not always), tracing log lines are emitted afterwards instead. This PR modifies the test to only assert that both lines are present in the logs instead.

test: fix overly specific test that fails sometimes with tracing

---

.git-blame-ignore-revs
pyproject.toml

This PR removes `tool.ruff.lint.pyupgrade.keep-runtime-typing`, and adds `flake8-future-annotations` and `flake8-type-checking`.
The rules `TC001`, `TC002`, and `TC003` are ignored, because these rules would move typing only imports into `if TYPE_CHECKING` blocks (when running `ruff check --preview --fix` with `--unsafe-fixes`), which is not a backwards compatible change for users who aren't also using `from __future__ import annotations`, stringified `typing.cast` argument, etc.
This PR also adds 425eae45307338f353279d7ae788581195393290 to the git blame ignore list, as that PR touched many lines in a mostly automated way when updating the annotation style to use `from __future__ import annotations`.

chore: update pyproject.toml and add future annotations commit to ignore list

---

.github/workflows/smoke.yaml
test/smoke/test_smoke.py

@tonyandrewmeyer reports
> The [smoke tests are failing](https://github.com/canonical/operator/actions/runs/14658930717/job/41138918710), unable to import opentelemetry.
It's my fault, I didn't try running smoke before/after I've merged `ops[tracing]`.
That added a fixture into the top-level `conftest.py` which monkey-patches `ops`, which pytest takes as an instruction to import `ops` which in turn imports `opentelemetry`.
That's fine for unit tests. Integration and smoke tests don't import `ops` in the first place, and thus `tox.ini` never declared their dependencies. This PR stubs out the offending fixture.
In the long term, let's move all the unit tests under `test/unit` or something.
> What do we say to the god of refactor?
> Not today.

ci: fix smoke test

---

docs/reference/ops-tracing.rst
tracing/ops_tracing/_export.py

Relax our, client-side TLS version requirement to allow TLS 1.2 or 1.3.
This roughly corresponds to allowing "Intermediate" config in addition to "Modern" in the Mozilla SSL Configuration Generator
Ref: https://ssl-config.mozilla.org/
Although https://github.com/canonical/tempo-coordinator-k8s-operator/pull/147 has been merged, I don't have clarity on all the trace data sinks and their deployment options.
Additionally some versions of the telemetry stack are in production and we'd have to analyse those very carefully if we enforce TLS 1.3 from the get-go, lest we force COS deployment upgrades merely because the first "random" application charm is switched to `ops[tracing]`.

fix: allow TLS 1.2 in ops-tracing

---

.github/workflows/publish-ops-scenario.yaml
.github/workflows/publish-ops-tracing.yaml
.github/workflows/publish-ops.yaml
.github/workflows/test-publish-ops-scenario.yaml
.github/workflows/test-publish-ops-tracing.yaml
.github/workflows/test-publish-ops.yaml
HACKING.md

Assuming that I understood Ben correctly about his earlier conversation with Tony, we have CI running in the PR context and on the main branch after each PR is merged.
Thus, we need not run the tests at the start of the publish job.
I'm not sure if this was about all tests or only integration tests.
I've added a step into the release process to wait after the release PR is merged to make sure tests are indeed passing.

ci: don't run tests within the publish job

---

.github/workflows/publish-ops-scenario.yaml
.github/workflows/publish-ops-tracing.yaml
.github/workflows/publish-ops.yaml
.github/workflows/test-publish-ops-tracing.yaml

The `ops` and `ops-scenario` release jobs don't specify the github (secret) environments, so let's remove these from the `ops-tracing` release jobs.

ci: don't pin release jobs to github environments

---

ops/version.py
pyproject.toml
testing/pyproject.toml
tracing/pyproject.toml

- ops '2.22.0.dev0'
- ops-tracing '2.22.0.dev0'
- ops-scenario '7.22.0.dev0'
- remove the otlp-json dependency since the package is vendored

chore: dev versions for all package after release

---

CHANGES.md
ops/version.py
pyproject.toml
testing/pyproject.toml
tracing/pyproject.toml

Includes:
- #1711 (revert separate charm instances for deferred events)
- #1709 (removes the `otlp-json` dependency as we're using the vendored version)

chore: release 2.21.1 / 7.21.1

---

.github/workflows/validate-pr-title.yaml
HACKING.md

I'm proposing to add the 'tracing' scope to our conventional commit (pr title) checker.
This would allow issuing PRs like #1705 with a title like `fix(tracing): blah blah`.
P.S. I don't feel strongly about this. For example, we seem to have decided against `testing` the last time we discussed scopes.

ci: allow 'tracing' scope in PR titles

---

README.md

A charming survey response suggested linking to our docs from the top of our readme. I think this is a good idea. Currently I believe the only link is at the end of the (now quite long) readme.

docs: link to our docs from the top of our readme

---

.github/actions/update-charm-pins/action.yaml
.github/workflows/charmcraft-pack.yaml
.github/workflows/db-charm-tests.yaml
.github/workflows/framework-tests.yaml
.github/workflows/hello-charm-tests.yaml
.github/workflows/integration.yaml
.github/workflows/observability-charm-tests.yaml
.github/workflows/publish-ops-scenario.yaml
.github/workflows/publish-ops-tracing.yaml
.github/workflows/publish-ops.yaml
.github/workflows/published-charms-tests.yaml
.github/workflows/smoke.yaml
.github/workflows/test-publish-ops-scenario.yaml
.github/workflows/test-publish-ops-tracing.yaml
.github/workflows/test-publish-ops.yaml
.github/workflows/tiobe.yaml
.github/workflows/update-charm-tests.yaml
.github/workflows/validate-pr-title.yaml
.github/workflows/zizmor.yaml
.github/zizmor.yml

This PR updates our uses of actions in our actions and workflows to specify them by their hash, rather than by tag. This is a good idea because tags are movable, and so could result in the execution of malicious code in our workflows if a bad commit is added to any of those actions.
I believe that dependabot can be configured to open PRs to bump the commit hash (and version comment) when there are new releases, though I'm not sure what will happen with our current configuration.

ci: pin workflows by hash

---

ops/_private/harness.py
ops/framework.py

This PR addresses a couple of issues:
- In the welcome message that's shown when a breakpoint is triggered, there's a link to https://juju.is/docs/sdk/debugging. This link is broken. I think a suitable replacement would be [`juju debug-code`](https://documentation.ubuntu.com/juju/3.6/reference/juju-cli/list-of-juju-cli-commands/debug-code/).
- Harness raises an error if the charm tries to update an unknown config option. The error message includes a link to https://juju.is/docs/sdk/config, which redirects to [https://ops.readthedocs.io/en/latest/howto/manage-configurations.html](https://ops.readthedocs.io/en/latest/howto/manage-configurations.html). I was going to replace the link, but since this is Harness, I then figured that removing the link would be the more maintainable option.

fix: fix link in breakpoint output, remove link from Harness error message

---

README.md
docs/reference/ops-testing-harness.rst
docs/reference/ops-testing.rst
ops/_private/harness.py
ops/charm.py
ops/jujucontext.py
ops/lib/__init__.py
ops/model.py
ops/testing.py
pyproject.toml
test/charms/test_smoke/metadata.yaml
test/integration/conftest.py
test/integration/test_tracing.py
test/smoke/test_smoke.py

This PR updates old `juju.is/docs` links in docstrings, comments, and the README.
This addresses most of #1626. The other parts of that issue will be done separately:
- Links in the Kubernetes tutorial will be covered by https://github.com/canonical/operator/issues/1718
- The link in `testing/CONTRIBUTING.md` will be covered by https://github.com/canonical/operator/pull/1724
- The remaining links are technically behavior changes, because they're in output/errors from Ops. Covered by https://github.com/canonical/operator/pull/1726

docs: update links to juju.is/docs

---

ops/_private/harness.py

While investigating Harness code, we found this apparently unused (private) class. It (rightly) does not appear to be used in any charms.

fix: remove apparently unused class in harness

---

.github/workflows/example-charm-tests.yaml

This PR is a follow up to #1719 - specifically [this comment](https://github.com/canonical/operator/pull/1719/files#r2090751498).

chore: change Python 3.11 to 3.10 and 3.12, when testing example charms

---

docs/requirements.txt

Regenerate the documentation dependencies (`rm docs/requirements.txt; uvx --python=3.11 tox -e docs-deps`).
This is primarily to deal with `h11`, which has a security issue that's fixed in the new release (I don't believe we are impacted, but updating is safest and silences the alert).
Rather than only bumping `h11`, bump the rest as well. The ones that are not bug-fix releases only are:
* [anyio](https://anyio.readthedocs.io/en/stable/versionhistory.html) (seems unlikely to impact doc generation)
* certifi (the usual cert updates)
* [click](https://click.palletsprojects.com/en/stable/changes/) (drops Python 3.8 support but for docs that should be fine already, nothing else seems to impact us, awful release notes)
* [importlib-metadata](https://github.com/python/importlib_metadata/blob/mai …

chore: bump documentation dependencies

---

tracing/README.md

During the sprint we renamed the channel from "Ops Library Development" to the more general "Charm Tech". Update the reference in the tracing README.

docs: update Matrix channel name to Charm Tech

---

docs/explanation/testing.md
docs/howto/index.md
docs/howto/manage-charms.md
docs/howto/manage-configuration.md
docs/howto/manage-interfaces.md
docs/howto/manage-metrics.md
docs/howto/write-integration-tests-for-a-charm.md
docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/create-a-minimal-kubernetes-charm.md
docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/integrate-your-charm-with-postgresql.md
docs/tutorial/write-your-first-machine-charm.md
examples/k8s-1-minimal/tests/integration/test_charm.py

This PR changes "Manage configurations" to "Manage configuration", as the latter sounds much better to me. And we always call it "charm configuration" (singular) or "charm config", not "charm configs".

docs: configurations -> configuration

---

.github/workflows/validate-pr-title.yaml
HACKING.md

Per discussion at the sprint, we consider Ops too small a repo to use scopes, and no automation uses them, so we decided not not use scopes, and have validation error if you use one.
Fixes #1727

ci: remove explicit scopes and update HACKING.md

---

.github/workflows/observability-charm-tests.yaml

Now that https://github.com/canonical/alertmanager-k8s-operator/pull/329 has been merged, updating the charm's unit tests to use Scenario 7, this PR re-enables this charm in the Observability Charm Tests, and updates the pinned commit to include the updated unit tests.

ci: re-enable alertmanager-k8s-operator in observability charm tests

---

.github/workflows/tiobe.yaml
.gitignore
tox.ini
tracing/ops_tracing/_api.py

A collection of changes to fix reporting to TIOBE after the addition of the ops-tracing package:
* The TIOBE run needs all the dependencies explicitly installed, so add the new ones of importlib-metadata and opentelemetry-api. Presumably when we shift over to using `uv` for dependency management we can clean this up.
* Add a new tox environment for running unit tests with coverage for tracing, and split off the reporting part of the existing coverage environment, and add a new environment for combining and report. This is very messy, but works for now, and will presumably be able to be cleaned up when we do the planned repository restructuring.
* Fix one of the issues identified by TIOBE (oddly not by our regular tooling), where an f-string is used with logging.

ci: fix reporting to TIOBE after ops-tracing addition

---

testing/src/scenario/state.py

In `ops.testing`, `scenario.state` contains logic that removes a suffix string from the event name. With the previous `rsplit` based implementation, suffix removal would fail if the suffix occurred multiple times in the string, since it would split the string into more than two parts.
For example, this would lead to failure when running `ctx.on.action('my-action')`, as the string `my_action_action` would be split into `'my', '', ''`, and the code expected the result of splitting to always be two items (the prefix, and an empty string).
This PR sets `maxsplit=1` for `rsplit` to handle this case.

fix: correctly remove suffix from event string in ops.testing

---

.github/workflows/tiobe.yaml

TIOBE gives this error in two of the tracing modules:
> [ERROR 5073] The following error(s) occurred while 'pylint' was running: 'E0401:20:0:Unable to import 'opentelemetry.sdk.resources'. Module 'opentelemetry.sdk.resources' not installed or specified on PYTHONPATH in the TICS configuration.
Fix this by installing the dependencies for ops-tracing as well, when running the TIOBE action.

ci: install the ops[tracing] dependencies for the TIOBE action

---

.github/workflows/tiobe.yaml

This seems to have been missed when we added ops-scenario into the TIOBE checks - the error doesn't seem to show up anywhere except in the ops/testing.py results (which just show outdated results).
As well as explicitly installing ops-scenario, also install ops-tracing, for consistency.

ci: add ops-scenario and ops-tracing as explicit installs for TIOBE

---

.github/workflows/update-charm-tests.yaml

This workflow is failing due to a permissions error on the `git push`. Remove the `persist-credentials: false` line on checkout.

ci: persist credentials for update-charm-pins workflow

---

testing/src/scenario/state.py

Testing code such as `container = testing.Container("db", check_infos={check_info})` was failing type checks, with this error:
```
error: Argument of type "set[CheckInfo]" cannot be assigned to parameter "check_infos" of type "frozenset[CheckInfo]" in function "__init__"
"set[CheckInfo]" is not assignable to "frozenset[CheckInfo]" (reportArgumentType)
```
This PR fixes the type annotation of `check_infos` so that non-frozen sets are acceptable.

fix: fix type annotation of container check_infos in ops.testing

---

docs/explanation/tracing.md

I must have moved this block from a docstring at some point.
This PR updates the link format from MD to RST.

docs: fix external OTLP link

---

tracing/pyproject.toml

The newest release broke our code.
This is a quick fix that we could release to the charmers.
Upstream: https://github.com/open-telemetry/opentelemetry-python/issues/4616

fix: restrict the version of a dependency, opentelemetry-sdk

---

ops/_private/harness.py
ops/model.py

Removes an outdated (or perhaps always wrong) check in Harness that prevents accessing the remote app databag during relation-broken events. Juju does allow this, so Harness should have the same behaviour.
This check is specific to Harness and there's no equivalent check in Scenario.
Fixes #888

fix: Juju allows access to the remote app databag in relation-broken, so Harness should too

---

testing/src/scenario/_runtime.py

This changes the UncaughtCharmError message and puts the message on the same source line as the "raise", so that when using "pytest --pdb" to debug a charm exception, it shows more clearly what to do.
In Python 3.13 the [`exceptions [n]`](https://docs.python.org/3/library/pdb.html#pdbcommand-exceptions) command was added to pdb, which allows you to go back up the exception cause stack. For example:
```
$ pytest --pdb
...
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> PDB post_mortem (IO-capturing turned off) >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> /home/ben/.cache/uv/archive-v0/gz1Vrbxq-976wQzrfehra/lib/python3.13/site-packages/scenario/_runtime.py(345)exec()
-> raise UncaughtCharmError(f'Uncaught {type(e).__name__} in charm, try "exceptions [n]" if using pdb on Python 3.13+. …
```

docs: improve testing.errors.UncaughtCharmError message

---

docs/howto/manage-the-charm-version.md

Inspired by the [parca-k8s charm](https://github.com/canonical/parca-k8s-operator/blob/afdc784503a0ea7ac52172f417fd0a379b137632/charmcraft.yaml#L26), include an example in the how-to guide for managing the charm version of using a override-build step in the parts to automatically set the version.

docs: in the "manage the charm version" how-to, give an example of using override-build

---

test/smoke/test_smoke.py

In #1782, we removed Charmcraft 2.x from the smoke test matrix. However, the smoke test code was still specifying that 20.04 and 22.04 should use Charmcraft 2, so when the test ran a `KeyError` would be raised.
This PR changes those bases to use Charmcraft 3.
[The branch runs successfully in my fork](https://github.com/tonyandrewmeyer/operator/actions/runs/15601083025) - I must have missed testing that last time.

ci: use Charmcraft 3.x for smoke testing 20.04 and 22.04

---

tox.ini

#1804 introduced a false positive to pebble tests: pytest failures are ignored.
This PR updates tox to modern pattern (commands_pre/commands/commands_post) where the errors are surfaced correctly.

chore: fix pebble tests

---

tox.ini

https://matrix.to/#/!eNCNzcteYUDDYpStsu:ubuntu.com/$3VbbgdzBttKnsqO8bDK2okMs6E-W3rM_lUF3135DIFY?via=ubuntu.com&via=matrix.org&via=laquadrature.net
`tox -e unit` runs correct environment
`tox -e py3.10-unit` oddly installed `ops` from PYPI
Upstream discussion: https://github.com/tox-dev/tox-uv/discussions/212
This plugs the hole, though we don't have RCA yet.

chore: fix magic tox py3.X-unit environments

---

tox.ini

We think that [xdist was disabled accidentally](https://github.com/canonical/operator/pull/1819/commits/775168b6a7e723638151b9b217c48ecf4a35f07e). Turn it back on again.

ci: enable xdist for the 'unit' tox environments

---

docs/howto/write-and-structure-charm-code.md

This PR fixes some mistakes in [How to write and structure charm code > Handle status](https://ops.readthedocs.io/en/latest/howto/write-and-structure-charm-code.html#handle-status).
When I originally added the sample code, I wrote `self.on_collect_unit_status` instead of `self.on.collect_unit_status`, and similarly for app status.

docs: fix on_collect mistake in sample code

---

testing/src/scenario/mocking.py
testing/tests/test_e2e/test_relations.py

This PR filters out the current unit from being returned by Scenario in the case of a peer relation, to align with Juju.
This PR assumes that the behavior reported in the issue is consistent across Juju versions.
Fixes #1827

fix: Do not return this unit in a mocked peer relation

---

testing/src/scenario/_consistency_checker.py
testing/src/scenario/_runtime.py
testing/src/scenario/mocking.py
testing/src/scenario/state.py
testing/tests/test_consistency_checker.py
testing/tests/test_e2e/test_relations.py

The intention of Scenario's `PeerRelation` is that it defaults to no peers (the charm only has the one unit). In addition, `PeerRelation.peers_data` should only contain unit data for the *peers*, not for the unit that is under test - that is found in `local_unit_data`.
We were breaking these rules when creating a `PeerRelation` without an explicit `peers_data`. We would add in the default Juju relation data - but that was already present in `local_unit_data`, and we used `0` as the unit ID. In most cases, `0` is the unit being tested, so this data was mostly ignored and unable to be reached, although it was the underlying cause of the bug fixed in #1828. The worse situation is if someone provides a unit ID to `Context`, other than 0, and has a `PeerRelation` with default `peers_data`, the …

fix: testing.PeerRelation properly defaults to no peers

---

docs/howto/write-integration-tests-for-a-charm.md

https://documentation.ubuntu.com/juju/3.6/reference/charm/charm-development-best-practices/ got removed, this PR only removes our link to it.
https://matrix.to/#/!eNCNzcteYUDDYpStsu:ubuntu.com/$TOBCq_ZtQq1C7a5Jf4VxqiCwhgpJcPsvX1zMjx6o9r0?via=ubuntu.com&via=matrix.org&via=laquadrature.net
https://matrix.to/#/!xzmWHtGpPfVCXKivIh:ubuntu.com/$n9LO8ckFZgZts0TkZAzc8HYk2q_NYFFVxLmw110ToY0?via=ubuntu.com&via=matrix.org&via=xentonix.net

chore: drop stale juju doc link

---

docs/howto/write-integration-tests-for-a-charm.md
docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/create-a-minimal-kubernetes-charm.md
examples/httpbin-demo/tox.ini
examples/k8s-1-minimal/tox.ini
examples/k8s-2-configurable/tox.ini
examples/k8s-3-postgresql/tox.ini
examples/k8s-4-action/tox.ini
examples/k8s-5-observe/tox.ini

Per https://github.com/canonical/charmcraft/pull/2312#discussion_r2163084188 and discussion within Charm Tech, we decided that `{posargs}` should come at the end of `pytest` command lines in tox.ini files. This to match expectations when doing `tox -e some-env -- extra args`.
This PR updates tox.ini files in our docs and example charms.

docs: move {posargs} to the end of pytest command lines in tox.ini

---

ops/_private/harness.py
ops/charm.py
ops/model.py

This PR starts work on #1783. In the interests of making progress, I've kept the scope focused on docs related to `self.app` and `self.unit`.
I've updated several docstrings to hopefully steer people away from using `Model.app` and `Model.unit` when `CharmBase.app` and `CharmBase.unit` are appropriate. While I was doing this, I also updated some of the wording to be more consistent.
Main updated parts:
- Descriptions of [`Application`](https://ops--1856.org.readthedocs.build/en/1856/reference/ops.html#ops.Application), [`Model.app`](https://ops--1856.org.readthedocs.build/en/1856/reference/ops.html#ops.Model.app), and [`Model.get_app()`](https://ops--1856.org.readthedocs.build/en/1856/reference/ops.html#ops.Model.get_app)
- Descriptions of …

docs: be consistent with recommending self.app and self.unit

---

.github/workflows/observability-charm-tests.yaml
.github/workflows/published-charms-tests.yaml
ops/version.py
pyproject.toml
testing/pyproject.toml
tracing/pyproject.toml
uv.lock

Bump versions to `.dev0` in the 2.23 maintenance branch, also ported the CI fix for failed o11y charm tests.

chore: version bump for 2.23 maintenance branch and fix observability ci charm tests

---

.github/workflows/framework-tests.yaml
.github/workflows/hello-charm-tests.yaml
.github/workflows/publish-ops-scenario.yaml
.github/workflows/publish-ops-tracing.yaml
.github/workflows/publish-ops.yaml
pyproject.toml
testing/pyproject.toml
tox.ini
tracing/pyproject.toml
tracing/tox.ini
uv.lock

Remove Python 3.8.
- Bump Python version to 3.10 in `pyproject.toml`
- Update tags that trigger publish to `3.*`
- Remove Python 3.8 (and 3.9 for some tests) from GitHub Actions
- Update pyright config to 3.10

chore: remove 3.8 and update to 3.10

---

.github/workflows/charmcraft-pack.yaml
.github/workflows/hello-charm-tests.yaml
.github/workflows/observability-charm-tests.yaml

To be resolved by:
* Pack (hello-kubecon): https://github.com/canonical/operator/issues/1876
* Observability compatibility tests: https://github.com/canonical/operator/issues/1877
We're confident that nothing will have changed in Ops that breaks these, and they aren't required to merge, but we should get them green (by explicitly disabling them, as here) before we do the next release.

ci: disable non-essential checks that need adjustments to work with a Python 3.10 minimum

---

testing/tests/test_e2e/test_trace_data.py
tracing/ops_tracing/_api.py
tracing/pyproject.toml
uv.lock

In #1853, I argue that non-trivial charm library init should be wrapped in a span.
This PR does so for our first party `ops.tracing.Tracing` charm lib.

chore: create a span for ops.tracing.Tracing init

---

HACKING.md

In https://github.com/canonical/charmcraft/pull/2312 we're switching Charmcraft profiles to use `pyproject.toml` for dependencies - specifically Ops - and include `uv.lock` in generated charms. After discussion within Charm Tech, we decided that we should update the deps and lockfile whenever there's a major new feature of Ops or we resolve a dependency issue.
This PR updates the Ops release process in HACKING.md with instructions for doing that.

docs: update HACKING.md with how to bump Ops version in Charmcraft profiles

---

docs/custom_conf.py

This PR changes the title of the docs site to "Ops documentation" ([discussion in Matrix](https://matrix.to/#/!eNCNzcteYUDDYpStsu:ubuntu.com/$m7_sO5haoQoPm5SXSfBc5HEP53O-JPfNVZ03y9mT-g0?via=ubuntu.com&via=matrix.org&via=laquadrature.net)).
**[Preview build](https://ops--1890.org.readthedocs.build/en/1890/)**

docs: change title of docs site

---

pyproject.toml
tracing/pyproject.toml
uv.lock

Bumps pytest to the latest version. All tests still pass, no changes seem required. None of the [changes](https://docs.pytest.org/en/stable/changelog.html) seem particularly relevant to anything we are using (other than the dropped Python 3.8 support).
Fixes #1841

chore: bump pytest version

---

.github/workflows/zizmor.yaml
.pre-commit-config.yaml

Bumps Zizmor to 1.11 both in pre-commit and the workflow. There are various [new checks](https://docs.zizmor.sh/release-notes/) as well as a fix mode, but no new issues are found with our workflows.

chore: bump zizmor to 1.11

---

docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/create-a-minimal-kubernetes-charm.md
docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/expose-operational-tasks-via-actions.md
docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/integrate-your-charm-with-postgresql.md
docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/make-your-charm-configurable.md
docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/observe-your-charm-with-cos-lite.md
examples/k8s-1-minimal/src/charm.py
examples/k8s-2-configurable/src/charm.py
examples/k8s-3-postgresql/src/charm.py
examples/k8s-4-action/src/charm.py
examples/k8s-5-observe/src/charm.py

1. In the config chapter, we add a config class (with the single option) and add validation for it. I've put the loading into the pebble layer property, as that's (initially) the only place that it's used and it seemed cleanest for the tutorial. The invalid value handling is then moved to a small except block in the update and restart code.
2. In following chapters, continue with the approach for config, but when we move to collect-status also add validation of the value there. In the observability chapter, also handle getting the config for metrics.
3. In the actions chapter, we add an action class (with the single parameter of the action), and use it when loading the parameters. This is a very minimal change, but demonstrates the use of the feature, and encourages continuing with it …

docs: Use config and action classes in the Kubernetes tutorial

---

ops/model.py

`Model.app` should always be set (and code comments explicitly state that). However, [a Juju bug where JUJU_REMOTE_APP is not set](https://bugs.launchpad.net/juju/+bug/1960934) means that is not always true.
We work around this [elsewhere](https://github.com/canonical/operator/blob/a15646475eab8d243ef03c31d0e76ccb02941050/ops/charm.py#L570), so we should do it when potentially adding in the departing unit as well. Once the upstream issue is solved, we should be able to remove this.

fix: if self.app is not actually set avoid a new crash location

---

.github/workflows/charmcraft-pack.yaml
.github/workflows/update-charm-tests.yaml

This PR uses the [httpbin](https://github.com/canonical/operator/tree/main/examples/httpbin-demo) demo charm for the "Charmcraft Pack Test" check.
Since the charm doesn't use pyproject.toml (yet? see https://github.com/canonical/operator/issues/1805), I've kept the step that modifies requirements.txt. And since we're getting the `ops` package from a git repo, I've added a step that adds git as a build package in charmcraft.yaml. The hello-kubecon charm already had git specified as a build package.

ci: use httpbin demo charm for the Charmcraft pack test

---

docs/tutorial/index.md

The tutorials for building charms are split between ops (machine charms, K8s charms that aren't built using a common web framework) and charmcraft (12-factor style K8s charms using common frameworks). This means that when a new charmer lands on one of those sets of tutorials, they may miss that there are other ones.
To help address this, this PR adds links to the Charmcraft 12-factor tutorials from our tutorial index page.

docs: link out to the 12-factor tutorials from the tutorial index page

---

HACKING.md

This PR updates HACKING.md after ops3 release.
Python 3.8 -> 3.10
Ops 2.x -> 3.x

chore: update HACKING.md for ops 3.x

---

ops/_private/harness.py
ops/log.py
ops/pebble.py
pyproject.toml
test/test_pebble.py
test/test_testing.py
testing/src/scenario/_ops_main_mock.py
testing/src/scenario/_runtime.py
testing/tests/helpers.py
testing/tests/test_context.py
testing/tests/test_e2e/test_actions.py
testing/tests/test_e2e/test_cloud_spec.py
testing/tests/test_e2e/test_pebble.py
testing/tests/test_e2e/test_play_assertions.py
testing/tests/test_e2e/test_relations.py
testing/tests/test_e2e/test_secrets.py
testing/tests/test_e2e/test_state.py
testing/tests/test_runtime.py

Fix a variety of small type annotation issues.
These are found with `ty` and missed by `pyright` but should be fixed both because they are issues and because it would be good to be more prepared for a stronger type checker in the future.  (Note that we can't move to `ty` yet because (a) it's marked as not ready, and (b) there are a bunch of false positives still.)

chore: minor type checking fixes

---

.github/workflows/observability-charm-tests.yaml

Replace Python version to 3.10 for observability charm tests.
See discussion [here](https://github.com/canonical/operator/issues/1877#issuecomment-3026362687).
Closes https://github.com/canonical/operator/issues/1877.
Also, the logic for handling `requirements.txt` is removed, since all three charms from observability teams don't use it any more.

test: replace Python version to 3.10 for observability charm tests

---

docs/explanation/testing.md

The files in the promtheus-k8s repository have moved around, breaking the example link the testing explanation doc.
This PR replaces that link, but rather than update it to the new prometheus-k8s location, uses the ubuntu-manpages charm instead. That charm should be more stable, the tests are much simpler (which better matches this specific part of the docs, which are explaining the basics), and the charm *only* uses Scenario, unlike prometheus-k8s, which has a mix of Harness and Scenario.
Fixes #1910

docs: replace broken link in testing explanation

---

.github/workflows/tiobe.yaml

We've been [asked](https://chat.canonical.com/canonical/pl/yku51kozbtbdmbnaodxzgitkwh) to move the TIOBE workflow to self-hosted runners.
This is meant to optimise the time and bandwidth usage of Canonical's TICS pipelines for static code analysis in GitHub. Two thirds of the GitHub TICS pipelines under Canonical org are using them, but they want it to be closer to 100%.
I've used the `tiobe` runner (medium sized) as it seems like the static analysis for this repo shouldn't need large/2xlarge.

ci: move TIOBE workflow to self-hosted runners

---

docs/howto/manage-storage.md

The [Juju "Storage events" doc](https://documentation.ubuntu.com/juju/3.6/reference/storage/#storage-events) is being removed (as it's focused on charm development, rather than Juju users). Most of the content is already present in our reference and how-to docs, but there are some notes about storage locations that aren't there, so this PR copies those across (with some minor adjustments to fit into the existing how-to guide).

docs: expand the Storage how-to with content from Juju docs scheduled for removal

---

ops/_main.py
ops/model.py
test/test_model.py

We inject the `JUJU_REMOTE_UNIT` unit into the relation's unit so that the databag is available during relation-departed events. When this was added in #1364 the thinking was that it was cleaner to just always add that unit rather than check for the specific events. However, that was not correct: this means that the unit may be added before the data is available (in relation joined, for example).
This PR changes the injection so that it only happens in relation departed and relation broken events.
In addition, we inserted the unit into the relation *after* setting up the relation's `.data`, which meant that the data would not be accessible for the inserted unit. The PR adjusts the ordering so that the inserting is done first.
Fixes #1917

fix: only add the remote unit for departed and broken relation events, fix ordering

---

testing/src/scenario/_runtime.py
testing/src/scenario/context.py
testing/tests/test_context.py
testing/tests/test_runtime.py

Two changes, to allow tests to access the (mocked) app name and unit ID:
* Change `Context._unit_id` to `Context.unit_id`
* Change `Context._app_name` to `Context.app_name`, and resolve it to the app name from the charm metadata inside of the `Context` `__init__` rather than in `Runtime`, so that it's available before the event is run.
Fixes #1911

feat: add add_name and unit_id attributes to testing.Context

---

.github/workflows/update-charm-tests.yaml

The CLA check fails if we use a @github.com address and the name "github-actions'. Instead, use the name of the bot (with `[bot]` appended, which seems to be Canonical practice) and its email address.

ci: update the name and email when updating the charm pins

---

ops/model.py
test/test_model.py

In #1364 (to address #1109) we added the departed unit to `Relation.units` so that charms could access the relation data in the relation-departed event.
This was followed up by #1897, to fix an issue where the app was not available, and then #1918, to add the unit before populating `Relation.data`, and to only add the unit for `relation-departed` and `relation-broken`, rather than all events.
A problem that the original solution introduces is a subtle behaviour change in what `Relation.units` means. It's not explicit in the documentation, but previously it was always the same as the `relation-list` output. Changing which units are included could cause issues for holistic or reconcile charms that would now see the departed or broken unit as still part of the relation, until the event after …

fix: add the remote unit to Relation.data but not Relation.units

---

.github/workflows/charmcraft-pack.yaml

If the charmcraft pack workflow fails, we get output like:
```
Run sudo charmcraft pack --verbose
Starting charmcraft, version 3.5.2
Logging execution to '/root/.local/state/charmcraft/log/charmcraft-20250730-063104.414518.log'
Launching managed ubuntu 20.04 instance...
Creating new instance from remote
Creating new base instance from remote
Creating new instance from base instance
Starting instance
Starting charmcraft, version 3.5.2
Logging execution to '/tmp/charmcraft.log'
Initialising lifecycle
Installing build-packages
Failed to refresh package list: failed to run apt update.
Failed to execute charmcraft in instance.
Full execution log: '/root/.local/state/charmcraft/log/charmcraft-20250730-063104.414518.log'
Error: Process completed with exit code 1.
```
This doesn't really tell us …

ci: store the charmcraft logs if packing fails

---

.github/workflows/tiobe.yaml

The TIOBE analysis tool checks everything in the repository, so that includes [release.py][./release.py] as well as the three packages. Some of the analysis is failing because the dependencies (the `github` package) aren't available.
This PR adds the `release` group to the TIOBE dependencies to install.

ci: Install release dependencies for the TIOBE analysis

---

CONTRIBUTING.md
README.md
docs/custom_conf.py
docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/create-a-minimal-kubernetes-charm.md
docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/expose-operational-tasks-via-actions.md
docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/integrate-your-charm-with-postgresql.md
docs/tutorial/from-zero-to-hero-write-your-first-kubernetes-charm/make-your-charm-configurable.md
examples/README.md
examples/k8s-1-minimal/src/charm.py
examples/k8s-2-configurable/src/charm.py
examples/k8s-3-postgresql/src/charm.py
examples/k8s-4-action/src/charm.py
examples/k8s-5-observe/src/charm.py
ops/_private/harness.py
ops/testing.py
pyproject.toml
test/integration/conftest.py
test/integration/test_tracing.py
test/smoke/test_smoke.py
testing/README.md
tracing/README.md
tracing/pyproject.toml

This PR changes all hardcoded doc links to point to https://documentation.ubuntu.com/ops/latest/ instead of https://ops.readthedocs.io/en/latest/. In addition to switching to documentation.ubuntu.com, we're dropping `en` from URLs.
This PR also changes the Sphinx config to make sure that all styles can be loaded.
---
Related PR targeted at 2.23-maintenance: https://github.com/canonical/operator/pull/1942. As soon as both PRs have merged, I'll set up redirects from ops.readthedocs.io to documentation.ubuntu.com/ops.

docs: update links and config for switch to documentation.ubuntu.com/ops

---

README.md
docs/custom_conf.py
docs/index.md
ops/_private/harness.py
pyproject.toml
testing/README.md
tracing/README.md
tracing/pyproject.toml

This PR changes _selected_ hardcoded doc links to point to https://documentation.ubuntu.com/ops/2.23/ or https://documentation.ubuntu.com/ops/latest/ (as appropriate) instead of https://ops.readthedocs.io/en/latest/.
Since the changes are targeted at 2.23-maintenance, I wanted to avoid unnecessary doc and code changes. So I'm only adjusting the links that people would first encounter in the README/PyPI/docs.
This PR also changes the Sphinx config to make sure that all styles can be loaded.
---
Related PR targeted at main: https://github.com/canonical/operator/pull/1940. As soon as both PRs have merged, I'll set up redirects from ops.readthedocs.io to documentation.ubuntu.com/ops.

docs: for 2.23, update links and config for switch to documentation.ubuntu.com/ops

---

CONTRIBUTING.md
README.md

Two minor doc changes following on from the 3.0 release:
* Update the minimum Python version in the README.
* We do publish separate docs for separate versions of Ops now, but only major versions, and we don't generally backport doc changes.
Fixes #1941, #1943

docs: Update the required Python version and note the 2.x documentation site

---

HACKING.md
release.py

A few bug fixes and refactoring of the release automation script.
Fixed:
- Mention how to create a token (either using `gh` or creating a classic token).
- When waiting for user input, use bold text, add ":" at ethe nd of the explanation line, and a "> " on the next line waiting for input.
- Remove "Unexpected category" logs.
- Before printing "Formatted release notes", flush stdout/stderr to avoid intermingled outputs from other subprocesses.
- Fix a typo "draftrelease".
- Changed the double blank lines to a single one in `CHANGES.md`.
- Fix PR description capitalization.
- Add a version for the post-release branch (`post-release-*` now).
- When releasing from a maintenance branch, track upstream instead of origin.
- Some other minor updates to `HACKING.md`.
Closes …

chore: refactor and bug fix

---

pyproject.toml

As per [the guide](https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license-and-license-files) so that third-party tools can figure out the license in the modern way.

chore: add license and license-files fields in pyproject.toml

---

release.py

f-strings shouldn't be used in calls to logging.log. In practice, this isn't going to cause issues in this specific case, but it's good to stick to best practice, and this avoids complaints by linters.

chore: don't use f-strings in logging in the release script

---

tox.ini

Contrary to [my claim in #1951](https://github.com/canonical/operator/pull/1951#discussion_r2253104136), the [published sitemap](https://documentation.ubuntu.com/ops/latest/sitemap.xml) still has URLs containing `MANUAL`. The starter pack config expects `READTHEDOCS_VERSION` to be set, but we're not passing that env variable through to sphinx-build. This PR fixes the issue.

docs: fix broken URLs in sitemap

---

docs/howto/legacy/turn-a-hooks-based-charm-into-an-ops-charm.md
docs/howto/legacy/write-legacy-unit-tests-for-a-charm.md
docs/howto/manage-libraries.md
ops/model.py

This PR finishes work on #1783. There are a few places in old docs where we're using classes from `ops.<submodule>` instead of directly from `ops`.
Drive-by: Pre-commit removed some whitespace. Best to hide whitespace when reviewing.

docs: use classes from ops instead of ops.<submodule>

---

tox.ini

Error pages in the docs are broken. For example:
https://documentation.ubuntu.com/ops/latest/foo
The problem is that the page is trying to load static assets from the wrong URLs:
```
https://documentation.ubuntu.com/ops/_static/styles/furo.css
https://documentation.ubuntu.com/ops/latest/_static/styles/furo.css
```
The URLs are wrong because the `READTHEDOCS_CANONICAL_URL` environment variable is not set at build time. The canonical-sphinx extension [needs the variable to be set](https://github.com/canonical/canonical-sphinx/blob/d63d89416434e213aefec84b8f09886dbf45597b/canonical_sphinx/config.py#L146-L148) to correctly build URLs of static assets.
This PR fixes ( :crossed_fingers: ) the issue by passing `READTHEDOCS_CANONICAL_URL` through to sphinx-build in our custom tox environment.

docs: fix unstyled error pages

---

pyproject.toml
testing/pyproject.toml
tracing/pyproject.toml

In #1949 the license metadata was updated for ops, but not ops-tracing or ops-scenario; this PR completes.
`uv build` also warns about the `ops._private` and `ops.lib` packages inclusion being ambiguous, so the PR makes that explicit.
Fixes #1965

chore: clean up build settings

---

docs/index.md

This PR improves the docs homepage as a jumping-off point into Ops and related charming resources. Highlights:
- The "In this documentation" section now contains links to some important pages.
- Added a Releases section
- Refocused the "Project and community section", being more explicit that we expect charmers to go to Matrix for support
- Added a "Looking for more?" section that links to more learning materials for charmers.
**[Preview](https://canonical-ubuntu-documentation-library--1964.com.readthedocs.build/ops/1964/)**

docs: refresh docs homepage with more context about Ops

---

release.py

The release notes and changelog currently ignore any commits that are `refactor`, `perf`, `revert`, or `chore`. We are deliberately ignoring 'chores', as those are deemed uninteresting and not relevant to consumers of the packages.
There are two cases for "revert". One is reverting a commit that is also in the same release; in this case we should remove both the original commit and the reverting commit to have a cleaner list of changes - doing this automatically is tricky, so having the revert listed in the changes makes it simpler to do this in the human review. The other case is reverting a change from a previous release: consumers of the packages should definitely be told about these.
Performance improvements are typically interesting to users, so it makes sense to mention those in the …

chore: add refactor, perf, and revert to the changelog/release note categories

---

docs/index.md

James and I decided to move Charmlibs docs to documentation.ubuntu.com sooner rather than later, before doc URLs start propagating. This PR updates the link from Ops docs. (There's a redirect, but as usual we prefer to keep the doc source in good shape.)

docs: update link to Charmlibs docs

---

.github/workflows/publish.yaml

This fixes the two open code scanning alerts. It's unclear how the failing workflow managed to get merged despite the failures (it doesn't appear to be due to a difference in Zizmor version, or an override, and the history in the scanning alerts does not seem correct).
This moves the permissions (particularly attestations:write and id-token:write) to the build-and-publish job, rather than applying to the entire workflow. In practice, this means that the secscan job doesn't have those permissions.

ci: adjust permissions block in publish workflow

---

docs/conf.py
pyproject.toml
uv.lock

The [sitemap](https://documentation.ubuntu.com/ops/latest/sitemap.xml) for Ops contains pages that are generated by Sphinx or our automodule setup:
- 404/
- genindex/
- py-modindex/
- _modules/ops/main/, etc
- search/
These pages aren't discoverable through the site, so they also shouldn't appear in the sitemap. This PR removes the pages from the sitemap.
**[Preview of updated sitemap](https://canonical-ubuntu-documentation-library--1979.com.readthedocs.build/ops/1979/sitemap.xml)**
To exclude everything under `_modules/`, I'm using the new wildcard support in sphinx-sitemap version 2.8. See https://github.com/jdillard/sphinx-sitemap/pull/113 and https://github.com/jdillard/sphinx-sitemap/releases/tag/v2.8.0. I've updated our dependencies to require a compatible version of sphinx-sitemap.

docs: remove unnecessary pages from sitemap

---

.github/workflows/integration.yaml

I noticed that Tempo charms don't seem to be using the same work-around as we do.
They are also on Concierge 1.0.4.
This is trial and error to see if the work-around can be removed.
Edit: instead of removing the work-around, I'm restricting it to Canonical K8s.
This works: https://github.com/canonical/operator/actions/runs/16896879217?pr=1976

chore: remove the Concierge work-around

---

docs/howto/log-from-your-charm.md
docs/howto/manage-stored-state.md
docs/howto/run-workloads-with-a-charm-machines.md

We're using "best practice" blocks to mean "required for public listing on charmhub". That implies that they should be items that are reasonable to review & resolve at that time, rather than earlier in the charm development process. We're generally using "tip" blocks for suggestions that occur earlier.
This PR changes some "best practice" blocks to tips:
* `logger.info(f"foo {bar}")` rather than `logger.info("foo %s", bar)` (in practice this also doesn't tend to make a lot of difference in the charming case, although it is more correct)
* Absolute paths in `subprocess` calls (this is also less relevant in the charming context than in general Python code)
* Avoid running subprocesses via the shell.
[More context](https://github.com/tonyandrewmeyer/charmhub-listing-review/issues/3).

docs: change some best practices to tips

---

examples/httpbin-demo/tests/integration/test_charm.py

This PR expands the integration tests of the httpbin demo charm. The charm has a config option for specifying the log level, and the charm blocks if the configured log level is invalid. I'm adding an integration test for this behaviour.

docs: add integration test for invalid config in httpbin charm

---

test/test_testing.py

Fixes #1822 
I've re-tested with `-n` from `1` to `16`.
Confirming Tony's comment that the bug was fixed in #1701.

chore: reenable one assert in harness tests

---

.github/workflows/sbom-secscan.yaml

The sbomber repository is now public, so we do not need a GitHub token to clone it in the workflow.

ci: remove the token for SBOM and secscan on publish

---

pyproject.toml
release.py
uv.lock

This PR adds coloured output for the logging in the `release.py` script, using `rich.logging`. This will be especially nice for the draft release, as it will more clearly separate the logging output visually from the release notes being printed. I tested this change by generating the post-release PR using this version of the script. I also tested that it runs cleanly for the draft release, bailing out with a keyboard interrupt on user input.
Before:
After:

ci: nicer logging output in the release script using rich

---

.github/workflows/charmcraft-pack.yaml
.github/workflows/example-charm-tests.yaml
examples/httpbin-demo/charmcraft.yaml
examples/httpbin-demo/pyproject.toml
examples/httpbin-demo/requirements.txt
examples/httpbin-demo/tox.ini
examples/httpbin-demo/uv.lock

This PR completes #1805. Changes:
- Put charm dependencies in `pyproject.toml` instead of `requirements.txt`
- Put testing dependencies `pyproject.toml` instead of `tox.ini`
- Add `uv.lock`
- Switch `charmcraft.yaml` to use the uv plugin
- Update CI to support/expect a uv-based charm:
- Example Charm Tests
- Charmcraft Pack Test
For both `pyproject.toml` and `tox.ini`, I'm using the setup that will come from `charmcraft init` in Charmcraft 4. If anything needs adjusting, we should consider adjusting the templates too.
:heavy_check_mark: all charm tests have passed, including integration tests

docs: use uv for testing and packing the httpbin charm

---

docs/howto/manage-relations.md
docs/reference/ops-testing.rst

Resolves #1826. This PR makes a few small improvements to the intro of the `ops.testing` reference:
- Mention that how-to guides have info about testing each feature
- Link to the unit testing how-to guide and the testing explanation (moved from the end of the intro)
- Mention the term "unit tests" much earlier
- Move the "previously known as 'Scenario'" part to the end of the intro, as Scenario is already mentioned in the title
**[Preview doc](https://canonical-ubuntu-documentation-library--2023.com.readthedocs.build/ops/2023/reference/ops-testing/)**
---
Not implemented:
- In [#1826](https://github.com/canonical/operator/issues/1826), I mentioned possibly adding a link from [`Relation`](https://documentation.ubuntu.com/ops/latest/reference/ops-testing/#ops.testing.Relation) to the …

docs: improve intro to ops.testing reference

---

examples/httpbin-demo/tests/integration/conftest.py
examples/httpbin-demo/tests/integration/test_charm.py
examples/httpbin-demo/tox.ini

This PR updates the integration tests of the httpbin charm to include an environment variable `CHARM_PATH`:
- If `CHARM_PATH` is not set, `tox -e integration` looks for a `.charm` file, deploys that charm, then runs the tests.
- If `CHARM_PATH` is set, `tox -e integration` deploys the specified charm file then runs the tests. For example:
```
CHARM_PATH=mycharm.charm tox -e integration
```
In either case, `charmcraft pack` needs to have been run before `tox -e integration`.

docs: in httpbin charm integration tests, add env var for charm file to deploy

---

docs/tutorial/index.md
docs/tutorial/write-a-machine-charm-for-tinyproxy.md

This PR starts work on a new machine charm tutorial. The purpose of the new tutorial is to teach modern charming practices with a real (but not complex) workload.
**The new tutorial is not ready to be used by charmers yet.** But early feedback is extremely welcome. To avoid dropping a huge PR for the team to review, this is the first PR in a sequence. Subsequent PRs will fill in the TODOs and make any changes coming from this initial review. Also, the tutorial won't be ready to use until Charmcraft 4 and `charmlibs-apt` are released.
Focus for reviewing this PR:
- Overall structure and topics covered in the tutorial
- Code review, including unit tests
**[Preview doc](https://canonical-ubuntu-documentation-library--1999.com.readthedocs.build/ops/1999/tutorial/write-a-machine-charm-for-tinyp …

add first draft of new machine charm tutorial

---

tox.ini

This PR should fix https://github.com/canonical/operator/issues/2015, which was causing the release script to fail for James.

chore: pass SSH_AUTH_SOCK to release script

---

ops/model.py

Add a note to the `Relation.data` docs that points out that peer relation data cannot be used during the `install` event.
Fixes #1452

docs: note that the peer databag isn't usable during the install event

---

docs/howto/manage-actions.md

A tiny PR to fix the testing code in "How to manage actions":
* `ops.ActionFailed` should be `ops.testing.ActionFailed`. But since the sample code already imports `testing` from `ops`, I'm switching to `testing.ActionFailed`.
* Fix the quoting of a string
Preview: https://canonical-ubuntu-documentation-library--2054.com.readthedocs.build/ops/2054/howto/manage-actions/#write-unit-tests

docs: fix testing code in actions how-to guide

---

tracing/ops_tracing/_buffer.py
tracing/ops_tracing/_export.py

This change ensures that the tracing data file has same minimal permissions as the unit state file.
fly-by: `path|str --> path` type change in the private api
not included: custom exceptions, I figured if sqlite can connect to the path, then chmod should work as well.
note that we don't care about `:memory:` paths because tracing is mocked out at a different level in `ops[testing]` and is disabled completely in legacy unit testing framework.
Fixes #1950

chore: secure permission bits on the tracing database file

---

testing/src/scenario/mocking.py

Previously, `_MockModelBackend.relation_get` returned the same `dict` object associated with the `Relation` objects it managed, rather than a copy. This meant that when `ops.RelationDataContent` was instantiated, it was passed this `dict` to use as its local cached copy. This meant that our proxy for Juju's relation data store and the local cache were the same exact `dict` object in testing.
At runtime, when relation data is updated, first `relation_set` is called to update the Juju data, and then the local cached copy is updated to match. During testing, this hid a subtle bug in our mock `relation_set` logic -- entries were not deleted as expected, but this error was 'corrected' by `RelationDataContent`'s update of its local cached copy (the same `dict`) deleting the entries.
This PR …

fix: `_MockModelBackend.relation_get` will return a copy of the relation data

---

release.py

I noticed that the release script missed some items when parsing the release notes generated by GitHub. The username matching was too strict. E.g., it didn't match usernames containing `-`. I've loosened the matching.

chore: fix release note parsing in release script

---

docs/howto/manage-interfaces.md

In "How to manage interfaces" we have some links to a repo that demonstrated the code shown in the doc. But over time some of the links have broken. In a team discussion we decided to remove the references and keep the links to examples that are in active use.
This PR updates the references. In the future, we may need to make more substantial changes as interfaces move to the [charmlibs](https://github.com/canonical/charmlibs) repo.
**[Preview doc](https://canonical-ubuntu-documentation-library--2068.com.readthedocs.build/ops/2068/howto/manage-interfaces/)**
Drive-by: pre-commit cleaned up some whitespace. I suggest reviewing with whitespace hidden.

docs: update referenced examples for managing interfaces

---

test/charms/test_relation/charmcraft.yaml
test/charms/test_tracing/charmcraft.yaml

PyYAML is a compiled dependency, this change makes the tests faster:
11m5s --> 8m41s
13m46s --> 8m50s
Runs:
- old: https://github.com/canonical/operator/actions/runs/18183586135/job/51763852983
- new: https://github.com/dimaqq/operator/actions/runs/18183591438/job/51763867160
Fly-by: fix yaml indentation and dangling space

chore: make integration tests slightly faster
